docs/spfx/set-up-your-developer-tenant.md, docs/spfx/set-up-your-development-environment.md, docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md, docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md, docs/spfx/web-parts/get-started/connect-to-sharepoint.md, docs/spfx/web-parts/get-started/deploy-web-part-to-cdn.md, docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md, docs/spfx/web-parts/get-started/use-fabric-react-components.md
The numbered indentations is causing issues in rendering. One of the reasons the current docs in the wiki do not use numbered indentations. 
I also fixed few issues with the setup your development doc as well.
=> Fixed MD indentations and code format

docs/spfx/web-parts/basics/design-considerations-for-web-parts.md
| content fix?        | Yes
| New article?        | No
| Related issues?     | No
Clarifies that Fabric Core styles (typography, colors, icons, etc.) are loaded onto the page by default. Web parts do not need to import anything to make use of these styles.
=> Clarify that Fabric is included by default

docs/spfx/web-parts/basics/add-an-external-library.md
Updated the documentation to mention installation of microsoft.ajax typings along withJSOM typings. The JSOM typings have a dependency on microsoft.ajax typings and the project cannot be built without including both.
=> updated docs to add typings for microsoft.ajax

docs/spfx/set-up-your-development-environment.md
| Related issues?     | I opened no issue
The problem is that we currently have two LTS versions of NodeJS
- v4.6.1 LTS
- v6.9.0 LTS
SPFx might fail with version 6.9.0 LTS but works for sure with v4.6.1 LTS. Using NodeJS Version reverences just by using LTS is not enough.
=> Update on LTS and added version information

docs/spfx/set-up-your-developer-tenant.md
| Q | A |
| --- | --- |
| content fix? | yes |
| New article? | no |
| Related issues? | none |
Updated the section on how to upload the workbench to your dev site. There was some customer feedback that this was confusing. I think the close proximity of "upload" and "download" back-to-back was confusing, so hopefully this makes more sense now.
Also attempting to fix a rendering issue with bullets near the top of the doc with an extra line return.
=> making uploading the workbench less confusing

docs/apis/webhooks/sharepoint-webhooks-using-azure-functions.md
The 2 images used in the section that explains how to obtain the webhook URL were in the wrong order. Fixed now.
=> Switched 2 images

docs/spfx/roadmap.md
Fix typo of componen to component under Developer Experience section.
Fixed typo in existing article.
=> Fix typo of componen to component under Dev Exp

docs/spfx/toolchain/optimize-builds-for-production.md
Updated the path to the webpack vizualizer "./temp/stats/[solution-name].statshtml" instead of  "./dist/..."
Fixed outdated webpack vizualizer path
=> Updated the path to the webpack vizualizer

docs/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties.md
Updated this.refreshPropertyPane() to this.context.propertyPane.refresh(); as is the case with RC0 onwards as the documentation was misleading on this.
Updated this.refreshPropertyPane() to this.context.propertyPane.refresh(); as is the case with RC0 onwards as the documentation was misleading on this.
=> Updated refreshPropertyPane => context.propertyPane.refresh();

docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md
The "Replace an expiring client secret in a SharePoint Add-in" page has a broken link to the "Create or update client IDs and secrets in the Seller Dashboard" page.  Fixing that.
| Related issues?     | not aware of any
A fix to a broken link from the "Replace an expiring client secret in a SharePoint Add-in" page to the "Create or update client IDs and secrets in the Seller Dashboard" page.
=> Fix a broken link to seller dashboard documentation

docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md
The link to "Known Issues" is dead - probably it would make sense to point it to the Web Parts Known issues. The same applies to each of the 6 Extensions tutorials.
=> The link to "Known Issues" is dead

docs/spfx/extensions/guidance/using-custom-dialogs-with-spfx.md, misc/SharePointDocumentationToc.xml
| Related issues?     | None
I updated the TOC title for the dialog box topic.
=> TOC update to align with title update.

docs/spfx/web-parts/basics/integrate-with-property-pane.md
The "Handling field changes" chapter describes the two modes but don't actually mention how to turn on the non-reactive mode... I needed to do some researches to figure out how. Maybe it can help people to just write the solution here because the solution is not obvious.
=> Updated the SPFX property pane documentation with the code to turn on the non-reactive mode

docs/spfx/web-parts/guidance/office-ui-fabric-integration.md
…t all, to 2.34.2 which is the latest v2 release.
If you don't think 2.34.2 is the best, at least use 2.0.1 or 2.0.2 which exists.
Changed which version of Office UI Fabric to include as 2.0.0 is non-existent.
=> Changed office-ui-fabric-react version from 2.0.0 which don't exist

docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md
There was some inconsistency in the "Getting access to page placeholders" section that still referred to the header/PageHeader identifier although the example code was for the Bottom placeholder.
=> Cleaned up references for placeholder example

docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md
One of the code sections in this page had incorrect whitespace in the markup, causing the boundary backticks to show through in the rendered page and also for the non-code line of text after the code to be rendered as code. I have fixed the whitespace so the content should be rendered correctly.
This is also currently visible on the published document: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions
=> Fix malformed ```ts section

docs/toc.yml
The TOC entry "Deploy to a Azure CDN" was grammatically incorrect. I have fixed it by changing "a" to "an".
=> Fix grammar in "Deploy to an Azure CDN"

docs/spfx/web-parts/guidance/call-microsoft-graph-from-your-web-part.md
Proposing a change to this guidance document to reflect bug fix pull request to the source code repository. Pull Request: https://github.com/SharePoint/sp-dev-fx-webparts/pull/312
| Related issues?     | related to [pull request in source code repo](https://github.com/SharePoint/sp-dev-fx-webparts/pull/312)
This update replaces the incorrect semi-colon separator with the correct comma separator. Without a correction, it is possible to encounter issues such as token renewal timeout or token renewal silent failure. Testing included turning on logging in adal-angular.js to observe changes.
When the existing array _renewStates is cast as a string (at the string.prototype.split() …
=> fix bug by correcting the separator character

docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md
| Related issues?     | ~~fixes #X, partially #Y, mentioned in #Z~~
See the code block about `_renderPlaceHolders` method in [this page](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions) is not rendering correctly.
Not sure if this could resolve the formatting problem correctly.
=> Try to fix the render code block in Microsoft doc.

docs/general-development/sharepoint-search-rest-api-overview.md
Just updating some of the examples in the search rest api overview document to be consistent. Most lines where `'property':'value'` but there were a few lines that were `'property'='value'`. This change sets all as `'property':'value'`.
=> making examples consistent in search rest api overview

docs/design/themes-colors.md
I added quotes around the number 3 in the rowspan tag
I added quotation marks around the #3. Even though this is appearing correctly in preview, it doesn't appear correctly on staging. The source code for the rowspan row gets messed up and looks like this, causing it to not render.
&lt;td rowspan=3 style=&quot;font-weight:bold; vertical-align:middle; color:white; background-color:#d13438&quot;&gt;themePrimary: #d13438
Expected (plus fix): <td rowspan="3" style="font-weight:bold; vertical-align:middle; color:white; background-color:#d13438">themePrimary: #d13438</td>
=> Attempt #3 to fix "rowspan" tag

docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md
Included the -StartDate and -EndDate arguments in New-MsolServicePrincipalCredential PowerShell sample as these are mandatory, so a direct copy/paste doesn't work. It also nicely will show how to extend to last 3 years, which is what most customers prefer as I've noticed.
=> Included the StartDate and EndDate arguments in sample

docs/apis/alm-api-for-spfx-add-ins.md
The API URL to add a solution package seems to only be called with `tenantappcatalog/Add` instead of `AvailableApps/GetById('xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx')/Add`.
=> Updated the API URL to add a solution package

docs/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries.md
There are some SPFx behavior changes that, the `groupId` property is for modern page toolbox only, and the `group` property is for classic SharePoint page web part picker only. The doc is updated to reflect the changes.
=> Update the doc for the groupId and group properties

docs/apis/alm-api-for-spfx-add-ins.md
Fixed a wrong command **Get-PnPAvailableApp** with the right one **Get-PnPApp**
The cmdlet Get-PnPAvailableApp is documented to get a list of available apps, however the right command is Get-PnPApp.
=> Fixed a wrong command

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
| content fix?        | sort of?
- too many don't seem to understand how GitHub does checkbox lists, so added some docs
- added "delete this paragraph" to parts that are
docs for submitting issues / PR's and made all blockquote to easier read
- updated PR template to be consistent with Issue template
=> update GitHub templates with improved instructions & consistency

docs/sp-add-ins/publish-sharepoint-add-ins.md
DevX required branding change. "Office Store" is now AppSource.
=> Change Office Store to AppSource

docs/spfx/office-ui-fabric-integration.md
File is named `_References.scss` (starts with underscore)
Updated type on file reference to OUIF, filename starts with `_` underscore
=> Fixed typo

docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md
Added clarification inside of a note block on requirement of */CLIENTSIDEASSETS origin. If this origin is not present and the public CDN is enabled, requests for SPFx bundles will contain the token spclientsideassetlibrary. 
This could potentially be a bug, as it is feasible for tenants to desire to use the CDN functionality in a limited capacity (say for a central /CDN origin) and disable the out-of-box origins to reduce overall exposure.
Related issue reported: #1505
=> Clarify note on */CLIENTSIDEASSETS origin requirement

docs/general-development/how-to-use-the-content-enrichment-web-service-callout-for-sharepoint-server.md
BCS data source has a null rawdata property by design. Sample will not work property for BCS data source, so I recommend putting in a note to that effect.
> 
> 
> 
> adding  a note about missing RawData property when datasource for crawl is external (BCS)
> 
> …
=> CEWS doesn't have RawData for BCS item

docs/declarative-customization/site-design-json-schema.md
Review the location of supposed first-level action (createContentType and createSiteColumn) that were included as sub titles of createSPList and thus appeared to be subactions
=> Fix some bad location for 1st level actions

docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md
Update to the documentation. In case no reference to the `style` variable was made in the code the style sheet doesn't get added to the page. Happened to me sometimes and maybe others too.
=> Add notice to always use ${style.*} reference in code

docs/community/community.md, docs/general-development/sharepoint-development-overview.md, docs/general-development/sharepoint-glossary.md, docs/index.md, docs/schema/schema-reference-for-sharepoint.md, docs/solution-guidance/Office-365-development-patterns-and-practices-solution-guidance.md, docs/sp-add-ins/sharepoint-add-ins.md, docs/spfx/sharepoint-framework-overview.md, docs/toc.yml
- Converted SharePoint glossary from MSDN to markdown
- Added glossary to Development overview section
- Added glossary link in See also on top-level pages
- Added glossary link on Index page and fixed broken links on Index
- Added glossary link on TOC
=> Add SharePoint glossary

docs/spfx/web-parts/guidance/build-custom-property-pane-controls.md, docs/spfx/web-parts/guidance/tutorial-share-data-between-web-parts-global-variable.md
It seems typescriptx isn't supported in many markdown formatters but tsx is.
Syntax highlighting works better after these small changes in those two code blocks.
=> Use tsx instead of typescriptx as formatting option

docs/general-development/keyword-query-language-kql-syntax-reference.md
Add info about potential effect on performance
> 
> 
> 
> 
> _(DELETE THIS PARAGRAPH AFTER …
=> Update info about XRANK

docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md
Step 4 under 'Enhance the ListView Command Set rendering' was missing the instruction to add. Moreover with the current latest version the import is already present anyway, thus does not need to be added manually. Changed the instruction to validate that it is indeed present. Order of imports doesn't seem to matter according to my tests.
=> Adding missing instruction

docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md
Adds clarification to elements.xml section regarding RegistrationIds. The elements.xml currently provided is the default from the yeoman generator and will only work with lists when deployed, not document libraries. Based on the behavior when running localhost, it is easy to make the assumption that the custom action will be applied to both lists and document libraries, but that is not the case once deployed.
=> improves cmdset elements.xml explanation

docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
It's not clear what "register" means in "register and use  AppID and AppTitle."  Our experience in support has been that as soon as people add the User Agent, they experience far less throttling.  This should probably be check with the PG and maybe better verbiage applied.  The note:
[!NOTE]
> If you are developing front end components executing in the browser, most of modern browsers don't allow overwritting the user agent string and you don't need to implement this.
...is confusing.  I suspect some developers may think this means the User Agent header is optional if there is any kind of Add-in the executes from a browser.  Straight AJAX calls from JavaScript should allow this header, likewise with any kind of managed HTTPWebRequest.
- Related issues: fixes #X, partially #Y, mentioned in …
=> Language is unclear and we are seeing ISV's not following the guidance.

docs/apis/migration-api-overview.md
added capability in prime from the ip team.
> 
> 
> 
> 
> _(DELETE THIS PARAGRAPH AFTER …
=> Updated for label migration

docs/general-development/modify-sharepoint-components-for-mds.md
- Related issues: fixes #1908 
Namespace typo previously corrected didn't fully fix the issue (as per issue #1908). Actual class is [`Microsoft.SharePoint.WebControls.MdsCompliantAttribute`](https://msdn.microsoft.com/en-us/library/office/microsoft.sharepoint.webcontrols.mdscompliantattribute_members.aspx)
=> Further Namespace correction

docs/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator.md
Fining typo in help and command line section and arguments
=> fixing typo in available command line options

docs/apis/webhooks/overview-sharepoint-webhooks.md
- Related issues: fixes #2164 
Generally, 6 months corresponds to roughly 180 days but it is not exact and can cause errors when taken literally (as explained in issue #2164). So changing to 180 days to make this more explicit and obvious.
=> Changed expiration from 6 months to 180 days

docs/spfx/office-ui-fabric-integration.md
Fix Office UI Fabric docs to as CSS core project was implied as a dev dependency when it's not in the latest generator
=> office ui fabric core is a dependency not a DEV dependency in 1.5.1

docs/declarative-customization/column-formatting.md
- Related issues: mentioned in #1250 
Added clarification for referencing other fields to call out need to use internal field names. This was mentioned previously within an example in the article, but needed to be more explicit in the relevant detailed syntax section.
=> Clarified use of internal field names

docs/apis/alm-api-for-spfx-add-ins.md
Office365 CLI project moved from SharePoint profile on GitHub to PnP profile. So, all the urls to documentation were incorrect.
I've updated them.
=> Urls to Office365 CLI were updated for Application Lifecycle Management (ALM) APIs page

docs/declarative-customization/column-formatting.md
- Related issues: mentioned in #2256 
The column formatting schema is now redirecting from the `en-us` version to a more generic address. This causes an error in VS Code since it doesn't follow the redirect. So, I've updated all instances of the schema reference to prevent others from having the error.
=> Fixed schema address

docs/solution-guidance/modern-experience-customizations-customize-sites.md
This article still mentioned SPFx Extensions to be in dev preview. As per https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview#whats-next they're already in GA. Added link to the article with more information on SPFx Extensions.
=> Removed notice about SPFx Extensions being in preview

docs/spfx/dynamic-data.md
Renamed `IDynamicDataController` to `IDynamicDataCallables` as the interface changed between 1.5.1-plusbeta and 1.6.0-plusbeta.
=> Renamed IDynamicDataController to IDynamicDataCallables

docs/general-development/common-error-messages-in-sharepoint-workflow-development.md
Modify the link `Deployment guide for Microsoft SharePoint` to `https://download.microsoft.com/download/1/F/6/1F6D3BE4-1174-4320-A1D1-C0E2681CCCF3/Deployment-guide-for-SharePoint-2013.pdf `
- Related issues: #2686 
Change the Link of  `Deployment guide for Microsoft SharePoint` from `https://download.microsoft.com/download/1/F/6/1F6D3BE4-1174-4320-A1D1-C0E2681CCCF3/Deployment-guide-for-SharePoint.pdf ` to `https://download.microsoft.com/download/1/F/6/1F6D3BE4-1174-4320-A1D1-C0E2681CCCF3/Deployment-guide-for-SharePoint-2013.pdf `
=> Chanage the Link

docs/general-development/sharepoint-search-rest-api-overview.md
Described default scope for queries.
Described the default query scope for SharePoint Online. Added the new parameter ContentSetting, which only applies to SharePoint Online.
You only need to use the ContentSetting parameter if you use the SharePoint Server search API to power a search experience where your users expect to get results from SharePoint Online and OneDrive for Business, including their private OneDrive for Business content.
=> Added ContentSetting parameter

docs/solution-guidance/modern-experience-customizations-provisioning-sites.md
Since a few months, it is possible to create a modern teamsite which is not connected to a Group.
- [x ] New article
Added the possibility to create a modern site using the STS#3 template and also by utilizing the SharePoint Online Management Shell
> 
=> It is possible to create modern sites without a Group

docs/declarative-customization/view-formatting.md
- Related issues: fixes #2847 
Changed the detailed syntax to use `hideColumnHeader` from `hideListHeader`. Although both work, the preferred/supported syntax is `hideColumnHeader`
=> Property Correction

docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
If there were details on installing a developer certificate in the set up article, they are not there now. At any rate, in my test, no more details were needed.
One sentence removed for clarity
Article updated for clarity by removing an outdated sentence
=> Removed reference to set up article

docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md
The web part name was left as src\webparts\helloWorld\HelloWorldWebPart.ts, it should have been src\webparts\myFirstTeamTab\MyFirstTeamTabWebPart.ts
Minor correction to Building Microsoft Teams tab using SharePoint Framework - Tutorial
=> Corrected web part name

docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md
Correct the PowerShell given in the "Generate a report that lists each add-in and the date that its secret expires..." step. The current script simply outputs a static date (today) instead of the expiration date of the secret.
Previous script did not produce expected results. This correction gives the output expected according to the paragraph written before it.
=> PowerShell correction

docs/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties.md
The getter of the property propertyPaneSettings was
changed to a method named getPropertyPaneConfiguration.
Additionally, the getter returned a IPropertyPaneSettings type,
while the new method returns a IPropertyPaneConfiguration type.
Updates reference to property getter propertyPaneSettings in "docs\spfx\web-parts\guidance\use-cascading-dropdowns-in-web-part-properties.md". Should instead be a method getPropertyPaneConfiguration.
=> Updates reference to get propertyPaneSettings

docs/declarative-customization/column-formatting.md
- Related issues: fixes #2961 , partially #Y, mentioned in #Z
Modify the Json Code From 
`"color": "=if([$DueDate] <= @now, '#ff0000', ''"` to
"color": "=if([$DueDate] <= @now, '#ff0000', '')"
=> Modify the code

docs/spfx/extensions/guidance/using-custom-dialogs-with-spfx.md
- Related issues: mentioned in #2988 #3043 
Adding workaround for a known issue with opening multiple dialogs.
Documentation update.
=> Add onAfterClose override to the ColorPickerDialog example

docs/solution-guidance/modern-experience-customizations-provisioning-sites.md
Added information to the section describing how to create "modern" team sites via the Groups API in Microsoft Graph including a sample POST request.
Added content to the section on creating a "modern" team site via REST via the Microsoft Graph "Groups" API. Included a sample POST request for group creation. Included information about how the team site URI is determined.
=> Added information on creating "modern" team site via REST

docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md
Added notes for how to call Lookup column via REST API which has been changed for SP2016.
> While working on code migration from SP2013 to SP2016, everything was working as expected except for one following REST API call which includes Lookup Columns:
```
SP2013: /_api/web/lists/getbytitle('ListName')/Items?&$filter=LookupColumn_x003a_ID eq 1
```
>After some hit and trial I was able to get it to work by referring the Lookup Column's display name (without referring to the lookup column’s internal name):
```
SP2016: /_api/web/lists/getbytitle('ListName')/Items?&$filter=LookupColumnId eq 1
```
=> Lookup Column Changes for SP2016

docs/spfx/set-up-your-development-environment.md
Remark what need to be done to be able to launch local workbench especially for SharePoint 2016 projects.
Additional remark for web part development that targets on-premises environments
=> Update on NODE_NO_HTTP2 = 1

docs/spfx/dynamic-loading.md
Removed duplicate "it" words in the documentation.
=> Grammar correction for dynamic-loading.md

docs/declarative-customization/site-design-rest-api.md
Adding the new AddSiteDesignTaskToCurrentWeb endpoint to the documentation. This is an alternative to ApplySiteDesign to support more than  30 actions in a site script.
Added the new AddSiteDesignTaskToCurrentWeb endpoint. 
Changed a typo in for id, to siteDesignId
Added a break between sections
=> Documentation Updates - New Endpoint and Typos

docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md
Added side note about the need to have the SPO site backing the target Team in order to being able to host the SPFx custom tab.
Added instructions about how to initially provision the SPO site backing a Microsoft Team, in order to host the SPFx custom Teams tab.
=> Added a side note about adding the team tab built with SPFx

docs/spfx/connect-to-anonymous-apis.md
The documentation mentioned to be having the same call into the weatherservice while in fact the sample was calling into the Typicode service. Updated the text so it's aligned with the sample.
=> Changed weatherservice mention to Typicode

docs/apis/webhooks/overview-sharepoint-webhooks.md
"Server notification UR" must be "Server notification URL"
> 
> 
> 
> 
> _(DELETE THIS …
=> fix missing L from URL word

docs/declarative-customization/site-theming/sharepoint-site-theming-rest-api.md
There are two "RestRequest" function call's in the 'DeleteTenantTheme' code sample, the second of which passes a 'UpdateTenantTheme' request with a blank 'themeJson' property, which is unneeded in the delete context and causes the theme engine to error if executed.  
Also updated the theme name in the delete example, to match the theme name used in the other examples, 'Sounders Rave Green'.
=> Removed unnecessary function from Delete sample

docs/spfx/use-theme-colors-in-your-customizations.md
Small typo fixed in the theme color table
=> Typo in theme color table

docs/declarative-customization/column-formatting.md
Adding department and jobTitle, both fields are available on the person field for column formatting.
- Related issues: fixes #3515
Updated documentation to include two properties available on person field
=> Updating properties available on the person field

docs/spfx/set-up-your-development-environment.md
- Related issues: mentioned in #2603 
Switching between different generator version might be possible in the past but right now with the current versions, this is impossible.
All generator reference always to the global installations. So the local install won't have any effect.
An issue that describes this problem too can be found: https://github.com/SharePoint/sp-dev-docs/issues/2603
=> Switching between different versions of the generator removed

docs/spfx/toolchain/update-latest-packages.md
Related issues: 
- closes #1561
- after updating a package dependency, sometimes it's best to delete node_modules
- added step recommending this
=> add extra details about deleting node_modules

docs/declarative-customization/get-started-create-site-design.md
The provided PowerShell sample with the sample JSON file could not be copy/pasted into PowerShell. It would leave it in the edit mode in PowerShell. With this minor update, you can safely copy/paste the sample into PowerShell and hit enter to load the sample JSON up into the $site_script variable
=> Fixed PowerShell sample

docs/general-development/sharepoint-development-overview.md
Updating the topic links to point to docs.microsoft.com. Fixing the first link  "Set up a development environment for SharePoint Add-ins on Office 365" because it was broken.
- Related issues: fixes #3784
Fixing the broken link in 3784 and also  just updating the other link references to docs.microsoft.com
=> Updating Links in Documentation

docs/declarative-customization/column-formatting.md
Changed "childern" to "children", in response to #3855
> 
> 
> 
> 
> _(DELETE THIS …
=> Spelling fix

docs/spfx/integrate-with-teams-introduction.md
The "the" in the "Note" section at the bottom was missing an "e".
=> Misspelling in "Note" at the end of document

docs/spfx/set-up-your-development-environment.md
I verified the installation of NodeJS 10 on Ubuntu and Fedora that these installations are not required anymore. The installation of NodeJS comes automatically with the node-gyp package that contains compiler for Python and C++ components.
This was also tested on the latest version of Linux Subsystem for Windows and Ubuntu. Only the installation of NodeJS 10 was required.
=> Removed obsolete section for Fedora and Ubuntu

docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md
The link to `Create Microsoft Teams manifest manually for a web part and deploy it to Microsoft Teams.` was broken due to incorrect relative URL.
Correct URL is `../guidance/creating-team-manifest-manually-for-webpart`
=> Fix broken link to "creating manifest manually"

docs/sp-add-ins/include-a-custom-button-in-the-provider-hosted-add-in.md
- closes #3950
Fixed typo in the "Local Employees" list. Two instances missing space in URL.
=> Typo fix in list URL (#3950)

docs/spfx/use-aad-tutorial.md
- closes #3959
Add additional details to the SPFx AAD tutorial doc explicitly guiding user where to add methods (before it was just implied to put them in the same file they had been working in).
=> Add more detail to docs on where to add methods (#3959)

docs/transform/modernize-userinterface-site-pages-webparts.md
Added "not" to correct the explanation of Sandbox web parts, which are no longer supported.
=> Added "not" to correct Sandbox explanation

docs/sp-add-ins/get-a-quick-overview-of-the-sharepoint-object-model.md
- fixes #3949 
The variable selectedLocalEmployee is renamed to localEmployee, as it is declared before and used after the using scope.
The variable reference is corrected.
=> Corrected Variable name mismatch

docs/declarative-customization/site-design-json-schema.md
Note mentions Hub sites to roll out in March 2018. They are rolled out WW already by now, so the remark is no longer needed
N/A
Note mentions Hub sites to roll out in March 2018. They are rolled out WW already by now, so the remark is no longer needed
=> Removing note on hub sites being new and potentially not yet available

docs/spfx/dynamic-loading.md
The link is updated to actual Content instead of Content Source.
Updated link
to actual content (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/optimize-builds-for-production)
instead of content source (https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/toolchain/optimize-builds-for-production.md)
Updated link "Optimize SharePoint Framework builds for production" to actual content instead of content source
=> Updated link "Optimize SharePoint Framework builds for production"

docs/declarative-customization/site-design-pnp-provisioning.md
N/A
There has been a rename in the UI for accessing the Azure Function Environment Variables. I had a bit of a hard time finding them because of the changed name. Updating this article to make it reflect how it currently can be found.
=> Matching explanation on Azure Function environment variables to match current UI

docs/sp-add-ins/get-started-creating-sharepoint-hosted-sharepoint-add-ins.md
- fixes #3883
Screenshot on doc shows Add-ins in Testing, but older dev sites may say Apps in testing. Updated docs to reflect it.
=> Fixed references to "apps/addins in testing" list

docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md
- fixes #1916
- Fixed error in tutorial steps that were incomplete & incorrect. Removed step that was implying to install `@microsoft/sp-dialog` when it was no longer necessary
- Fixed markdown formatting errors
=> Correct error in tutorial steps

docs/declarative-customization/column-formatting.md
- fixes https://github.com/sharepoint/sp-dev-docs/issues/3846
Under the section "Create a button to launch a Flow", corrected information about flow launch panel.
On the page, https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#create-a-button-to-launch-a-flow
Under the section "Create a button to launch a Flow", corrected information about flow launch panel.
=> Corrected information about flow launch panel

docs/solution-guidance/Migrate-InfoPath-forms-to-SharePoint.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/4296
On the page https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/migrate-infopath-forms-to-sharepoint
Removed the recommended option of Access Applications as an InfoPath replacement.
Removed the recommended option of Access Applications as an InfoPath replacement.
=> Removed Access Applications option

docs/toc.yml
CONTENT FIX:   Changed case on TOC entry to lower case:  migration-isv-guidance (previously the ISV was in caps)
The entry on the TOC for this topic is currently broken, and I am surmising this has to do with the use of upper case letters.
=> Fixing broken link in TOC -- Update toc.yml

docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
- mentioned in #3033
- mentioned in #2333
- mentioned in #148
The documentation around listening ports is incorrect.
gulp serve sets up a node server to listen on port 4321 and then the workbench on ports 5432. This is not included in the docs.
In addition, where port 5432 is the default port for postgres, and could be used by other applications. There is no indicator that the port is not available when starting the application. The existing note only refers to certificate issues in the browser. Modern browsers show the connection failure as a possible TLS issue, therefore, enhance the documentation by suggesting that the user may also wants to confirm that the port is available. 
Whilst i'd personally use tcpview from sysinternals, I've suggested an approach using built in windows 10 …
=> Improve documentation around listening ports

docs/apis/alm-api-for-spfx-add-ins.md
Add a comment about Parallel package deployments not being supported as per https://github.com/SharePoint/sp-dev-docs/issues/4022
Add a comment about Parallel package deployments not being supported as per https://github.com/SharePoint/sp-dev-docs/issues/4022
=> Parallel package deployments not supported

docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md
Adding '?' for proper Odata Syntax. Fixes #4580
- fixes #4580 
Fixes a typo in URI for proper OData syntax
=> Fixing Typo in Documentation

docs/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/4243
Updated page title as Use @pnp/sp (PnPJS) library with SharePoint Framework web parts.
This should show (PnPJS) library although @pnp/sp is escaped.
Updated page title as Use @pnp/sp (PnPJS) library with SharePoint Framework web parts.
This should show (PnPJS) library although @pnp/sp is escaped.
=> Updated page title

docs/features/site-footer.md
N/A
According to MC 186030 (https://admin.microsoft.com/AdminPortal/home?switchtomodern=true#/MessageCenter?id=MC186030) it has rolled out WW by the end of July 2019 already, so the notice about it not being available yet can be removed.
=> Removing note that the site footer hasn't rolled out WW yet

docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md
> Removing --save from npm install command(s)
As per NPM install docs (https://docs.npmjs.com/cli/install), by default, npm install will install all modules listed as dependencies in package.json. This seems to be the case since npm 5 release according to this official blog post (https://blog.npmjs.org/post/161081169345/v500) dated May 2017.
=> Remove --save from npm install command(s)

docs/sp-add-ins/use-the-sharepoint-javascript-apis-to-work-with-sharepoint-data.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/4531
Instead of using code:
employeeList.getItemById(itemArray[i].get_id()).deleteObject();
we can use only this:
itemArray[i].deleteObject();
because we've already got these items by the previous clientContext.executeQueryAsync(deleteCompletedItems, onGetCompletedItemsFail), and that's enough.
Updated code sample as Getting items by ID is unnecessary.
=> Getting items by ID is unnecessary

docs/solution-guidance/security-apponly.md
NA
This PR adds a content fix. 
Communication sites creation is now supported in app-only context. In this scenario, the owner property is required. This update fixes that in the documentation and also points to the correct documentation to create communication sites.
=> Fix: Docs update for creating communication sites in app-only context

docs/apis/export-amr-api.md
- fixes #4602
Changed 
The SAS token must have been created with only Read, List and Write permissions or the asynchronous metadata read job will fail.
To
The SAS token must have been created with only Read and Write permissions or the asynchronous metadata read job will fail.
=> Edited azureContainerManifestUri SAS permission

docs/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator.md
SharePoint Framework v1.9.1 on wards supports library component. Included library in the type of supported component.
SharePoint Framework v1.9.1 on wards supports library component. Included library as the type of supported component for "yo @microsoft/sharepoint" as a command line option.
Included library as the type of supported component for "yo @microsoft/sharepoint" as a command line option.
=> Included library as supported component

docs/spfx/web-parts/basics/integrate-with-property-pane.md
The sample was incorrect as the property name according to the explanation was targetProperty. Updated the sample. Also included the use of escape(...) around it as that is a recommended practice for user input fields rendered on the screen.
=> Corrected sample property and added escape

docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md
#added snippet on how to get ListItemEntityTypeFullName
- fixes #3859 
> The [note on the page ](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#create-list-item ) mentions a about ListItemEntityTypeFullName but there isn't an example include in the guides anywhere on how to get it.
=> Updated working-with-lists-and-list-items-with-rest.md to include snippet to get 

docs/transform/modernize-scanner.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/4768
Under the section "Scan a defined list of site collections", the Tenant admin center URL is corrected to https://contoso-admin.contoso.com
Under the section "Scan a defined list of site collections", the Tenant admin center URL is corrected to https://contoso-admin.contoso.com
=> Tenant admin center URL is corrected

docs/spfx/extensions/get-started/build-a-hello-world-extension.md, docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md, docs/spfx/extensions/get-started/building-simple-field-customizer.md, docs/spfx/extensions/get-started/hosting-extension-from-office365-cdn.md, docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md, docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md, docs/spfx/set-up-your-developer-tenant.md, docs/spfx/set-up-your-development-environment.md, docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md, docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md, docs/spfx/web-parts/get-started/connect-to-sharepoint.md, docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md, docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md, docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md, docs/spfx/web-parts/get-started/use-fabric-react-components.md
Added custom tags to the getting started documentation highlighted by Vesa. These tags allow the docs to be pulled into our automated process for recommending content to members of the Office Developer Program.
Once these changes go live, the recommendation engine will pull these documents into the pipeline and begin analyzing them. SharePoint developers in the dev program will begin seeing the content once we turn on recommendations.
=> Adding custom tag for content recommendation

docs/schema/fieldbind-element-workflowinfo.md
Addresses #4899 Documentation used GitHub asterisk annotation for bold. However, this doesn't work in HTML tables. Replaced Github annotation to use html strong tags inside the HTML table.
Fixes #4899
Replacing double asterisk with html strong element inside of the HTML tables for better readability
=> Updating readability of tables

docs/declarative-customization/column-formatting.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/4866
Spelling correction for "required" under "button elements" para
Spelling correction for "required" under "button elements" para
=> Corrected typo in "button elements" para

docs/declarative-customization/site-design-json-schema.md
Added info about how to get the hubSiteId:
[!NOTE] To get the hubSiteId, sign in to a site by using the Connect-PnPOnline cmdlet, and then run:
```PowerShell
$hubSiteName = "My Hub Site"
Get-PnPHubSite | Where-Object { $_.Title -eq $hubSiteName }
```
This returns information about the current site's Hub Site. The hubSiteId is returned as the SiteId.
=> Added info about how to get the hubSiteId

docs/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/4757
Under the section - Create a Microsoft Teams app manifest, the JSON should have id parameterized as {{SPFX_COMPONENT_ID}} instead of hard-coded value
Under the section - Create a Microsoft Teams app manifest, the JSON should have id parameterized as {{SPFX_COMPONENT_ID}} instead of hard-coded value
=> SPFX_COMPONENT_ID is parameterized

docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
We have confirmed, that sometimes the exception handling returns a null client wrapper. When this circumstance happens, and it has several times for us, the code goes into an infinite loop because the wrapper remains null and is never set again. Moving the retry attempts increment before the retry (and outside of the exceptions) prevents this infinite loop.  Executing the Query as normal when a wrapper is unavailable also ensures a retry is made when the wrapper is null.
> 
- …
=> Prevent an infinite loop

docs/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart.md
SPFx 1.10 now supports personal tabs. Updating the teams manifest sample with the url to use in case of an SPFx based personal tab.
=> Updated manifest sample with personal tab url

docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md
In the approaches list, Azure Pipelines (Multi stage) was wrongly referred as this article.
This article was referred to as Azure yaml pipelines implementation. Rather this article explains the GUI part. Fixed the link accordingly.
=> Fix link for Azure Pipelines in approaches list

docs/spfx/web-parts/get-started/using-microsoft-graph-apis.md
Just a small typo - I guess too much 'graph' in this article caused the author to type 'graph' in place of 'grant'.
Just a small typo - I guess too much 'graph' in this article caused the author to type 'graph' in place of 'grant'.
=> Typo: "graph" should be "grant"

docs/spfx/web-parts/guidance/localize-web-parts.md
- fixes #3739
The spelling of the locales in the example code has been fixed. An additional block to emphasize the importance of the correct spelling in the manifest has been added.
According to issue #3739 in the sp-dev-docs issue list the locales must use the correct capitalization to work properly:
https://github.com/SharePoint/sp-dev-docs/issues/3739#issuecomment-579523419
Even though this requirement might change at some point in the future it won't get incorrect to use the correct spelling.
=> Corrected spelling of the locales in the manifest

docs/general-development/get-started-using-the-client-object-model-with-external-data-in-sharepoint.md
- fixes #5207
Fixes the code samples in the article to remove the following potentially confusing points:
1. The original code samples do not demonstrate how to obtain a LobSystemInstance (the `lsi` variable just magically appears in the code);
2. The sample code for setting the filter values is incorrect and will not even compile, as CSOM does not have a `FilterValue` property on the `Filter` class. Neither it is necessary to create a modified filter collection as shown in the original code samples.
=> Address inaccuracies in the code samples

docs/spfx/web-parts/guidance/connect-to-sharepoint-using-jsom.md
`SPComponentLoader` is now part of `@microsoft/sp-loader` module that should be installed implicitly.
=> Change SPComponentLoader section

docs/spfx/library-component-tutorial.md
I noticed that I was not able to import the library module into another webpart project unless I run "gulp build" 1st. If you dont run such command, you will get a tsc error "module is not found" since there is no "lib" folder at all.
It is just a description of a missing step that I consider other developers may found when trying to import the library module while using the npm link command. Developer needs to compile the library project at least once prior any attempt to import.
Dont know what to input in this section, sorry.
=> Missing step to be able to import after running npm link

docs/general-development/how-to-convert-an-html-file-into-a-master-page-in-sharepoint.md
Just like a .aspx file and .master file are called .aspx and .master, Consistently use the term:  .html file.
Sometimes on this page and other pages it refers to HTML file.
This makes it more clear when the item that is being referred to is the actual .html file.
=> Consistently use the term: .html file

docs/solution-guidance/security-apponly-azuread.md
The date format is ISO not US.
=> security-apponly-azuread.md: correct description of date format

docs/spfx/set-up-your-development-environment.md
The portion in this document about the Node version is misleading: it says "ensure you have the latest version" when actually (as indicated in the note immediately below that line) SPFx is not compatible with the latest version of Node. It is only compatible with Node 10.
Modified a few words in the documentation to provide more precise language (see explanation above).
N/A
=> Correct wording regarding node version

docs/spfx/extensions/basics/tenant-wide-deployment-extensions.md, docs/spfx/tenant-scoped-deployment.md
- fixes #5396
The tenant-scoped-deployment article targets broadly the concept of centrally deployed components. This fix and adds reference and guidance with respect to tenant wide site extensions and clarifies the steps for updating centrally deployed solutions.
I added the missing `features` attribute to the json example since it is generated by the yeoman generator and adding it allows ClientSideInstances.xml to be better referenced later in the article.
=> add references to tenant wide extensions list. correct typos

docs/spfx/set-up-your-development-environment.md
If external tools like Cmder or Oh My Zsh are mentioned, the Windows Terminal - while still in preview - certainly has to be on this list too...
=> Included the Windows Terminal as optional tool

docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md, docs/spfx/web-parts/get-started/office-addins-tutorial.md, docs/spfx/web-parts/guidance/use-existing-javascript-libraries.md, docs/spfx/web-parts/overview-client-side-web-parts.md
Changed letter 'c' to capital in Visual Studio Code.
Updated check box to checkbox (no space)
1. Changed letter 'c' to capital letter 'C' in Visual Studio Code.
2. Updated check box to checkbox (no space)
=> Corrected case mistakes

docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md
Make clear that personal tabs don't expose the web part property pane, as discussed in the Teams channel on 27/02/2020.
=> Teams Personal Tab clarification

docs/solution-guidance/modern-experience-customizations-customize-sites.md
N/A
The sample PowerShell on applying a theme to SharePoint was still using CSOM while native PnP commands are available now to set a theme. Updated the sample to use this cmdlet.
=> Updated PnP PowerShell on applying a theme

docs/declarative-customization/get-started-create-site-design.md
Subaction "setDescription" failed due to the capitalization of the verb.
Updated from "SetDescription" to "setDescription"
=> Removed capitalization on "setDescription"

docs/spfx/web-parts/guidance/intercepting-query-changes-in-webparts.md
window.location.search is a better method to get the URL search query string
A better approach to get the url search query
=> windows.location.query is a bit outdated

docs/spfx/web-parts/guidance/intercepting-query-changes-in-webparts.md
- partially #4557
I have proposed these changes beacuse: 
- When trying to leverage this on my spfx extension, using yeoman, I had issues on the code and the solution was to implement arrow functions. Also, it makes the code more understable.
- I have noticed that when using the back/forwards browser history buttons, doesnt have any effect, when the conditionally page load is in place ( aka page transition ). For instance, you can go to a library, and start to browser among the folders. You will notice that clicking on back/forward doesnt have any effect on page content load.
- I have documented how you can pass the url info change to the event handler
- This approach can help users to track down which folder the user is browsing, on a list/library
=> Leverage Arrow functions. Browser history nav button issue

docs/spfx/library-component-overview.md
From the initial article content, one may think you can only render spfx library components from the tenant app catalog, however, I have been testing and this is not correct. You can also host these components on a site app catalog. This may be very useful in the sense that you can have a site collection for developement purpouses, where you have a more dev version of your spfx library.
=> Mention that library can be hosted from site app catalog

docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md
Updating the headers in this example, to fix #5665 . Passing in the __metadata property in the request without specifying verbose, results in a 400 error "The property '__metadata' does not exist on type 'SP.Data.ListItem". 
Updating the headers of this sample to support the body that is being passed in the request.
- fixes #5665 
Updated sample to include proper headers when specifying __metadata on the request object. Otherwise, this sample returns a 400 error.
=> Updating Create List Item Example

docs/declarative-customization/site-theming/sharepoint-site-theming-json-schema.md
Replacing theme object name with palette as represented by the actual JSON for theming
Fix for issue #5691
=> Fix for theme JSON representation

docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md
Fix a note block that is now rendered as a code block.
Fixes a note block in `create-a-map-view-for-the-geolocation-field-in-sharepoint.md` that is now rendered as a code block but should be rendered as a quote.
=> Fix markdown formatting of a note block

docs/spfx/web-parts/guidance/build-custom-property-pane-controls.md
Removed shrink wrap step from the steps of setting up a new project.  Not needed in new npm versions. package-lock.json available instead.
=> remove unneeded shrink wrap

docs/spfx/library-component-tutorial.md
In order to compile library component, we should do "gulp build" instead of "gulp serve", since library component does not have any visual appearance.
=> Build command instead of Serve for library component

docs/general-development/site-collection-app-catalog.md
The link is to an article on managing the App Catalog for the Organization (the single app catalog for the tenant), not a site collection app catalog (the per site collection app catalog). I updated the link to so it is not misleading.
none
A change to the link in the 'see also' section at the bottom
=> Change the link in the 'see also' section

docs/spfx/use-msgraph.md
Add a known issues section which includes mention of implicit auth calls failing when calling a Microsoft Graph endpoint that requires Azure AD roles to be assigned.   Share links to supporting documentation and Office 365 usage reports which is currently known to exhibit this behavior.
- mentioned in #5845 
Content update to include Known Issues section to document.  Call out the use of implicit authentication flow which currently does not include the "wids" claim for Azure AD roles assigned.
=> Add known issue implicit auth fail no AAD roles

docs/solution-guidance/how-to-provide-add-in-app-only-tenant-administrative-permissions-in-sharepoint-online.md
This article is was not explicit enough to whether the .app needs to be uploaded to site collection or tenant catalog, even though it is implicit by the step:
Move to appinv.aspx page under your tenant admin site
- URL: *https://[tenant]-admin.sharepoint.com/_layouts/15/appinv.aspx*
NA
This article is was not explicit enough to whether the .app needs to be uploaded to site collection or tenant catalog, even though it is implicit by the step:
Move to appinv.aspx page under your tenant admin site
- URL: *https://[tenant]-admin.sharepoint.com/_layouts/15/appinv.aspx*
So, adding extra level of detail to avoid ambiguity hence confusion by stating the .app needs to be deployed at tenant level app catalog and not site collection catalog
=> Adding extra level of detail to avoid ambiguity

docs/apis/migration-api-overview.md
- [ X] Content fix
Updated changes as we are no longer saving migration log files into “Maintenance Logs” doclib to save cogs and perf.
=> update migration api overview

docs/spfx/extensions/get-started/build-a-hello-world-extension.md, docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md, docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md, docs/spfx/office-addins-create.md, docs/spfx/web-parts/basics/integrate-with-property-pane.md, docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md, docs/spfx/web-parts/get-started/use-fabric-react-components.md
- fixes #5921
- NPM packages should be bold, not use inline code formatting
- need to escape the `@` for package references
=> Fix-up markdown references to NPM packages

docs/declarative-customization/column-formatting.md
Corrected following grammar, casing and spelling
paramaterized to parameterized
arthmetic  to arithmetic 
occurence to occurrence  
indicies to indices
doesnt  to doesn’t 
preceeded to preceded 
url to URL
=> Corrected grammar, casing and spelling

docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
Fixed missing space between words. In addition to that the line "You can preview and test your client-side web part locally on your questions." doesn't look correct "on your questions"? does it mean on your workbench, i think this needs to be corrected.
=> Fixed missing space between words

docs/spfx/extensions/get-started/build-a-hello-world-extension.md, docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md, docs/spfx/extensions/get-started/building-simple-field-customizer.md
- fixes #5937
- previously removed the 2nd question in the SPFx generator
- added back to specify "SPO" as the option to select so the user sees the extension component type
=> Add "which baseline packages" question to extension projects

docs/toc.yml
Updates the TOC link title from 'Setup Office 365 tenant' to 'Setup Microsoft 365 tenant' to match the content page that it is linked to.
=> Update TOC to reflect page title change

includes/snippets/developer-preview-notice.md
Fixed broken link to preview documentation.
Fixed broken link in this snippet.
To reproduce, open this page: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-addins-create 
Then try to click on the link that says: "Try SharePoint Framework preview capabilities", the target url is broken.
=> Fix url for spfx preview docs

docs/declarative-customization/view-formatting.md
- fixes  #6107
It adds the '$' in the code examples for JSON schema.
=> $ missing in JSON schema

docs/spfx/set-up-your-development-environment.md
None that I could find.
This PR fixes an issue in the link to the SPFx 'getting started' tutorial in the [setting up your environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#trusting-the-self-signed-developer-certificate) section of the docs. The link was not formatted properly and appears incorrectly in the markdown.
=> fix link to tutorial in environment setup

docs/spfx/publish-to-marketplace-checklist.md
Adds a section to explicitly call out the requirement to only manipulate the DOM via the provided domElement and context.
none
Adds a section discussing the requirement to only manipulate the page via the supplied DOM element and context.
=> Add requirement for domElement and context in SPFx app store guidance

docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
The official label of the framework selection is 'No JavaScript framework' ad not 'No JavaScript web framework'
Content update in framework selection. It is labelled as 'No JavaScript Framework' and not 'No JavaScript web framework'
=> Fixing framework selection label

docs/spfx/web-parts/guidance/localize-web-parts.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/6149
Removed locale 2074: 'sr-Latn-CS' as it is no longer supported by SharePoint Online.
=> Removed locale 2074: 'sr-Latn-CS'

docs/spfx/extensions/get-started/query-suggestion-tutorial-building.md, docs/spfx/web-parts/get-started/using-microsoft-graph-apis.md, docs/spfx/web-parts/guidance/build-client-side-web-parts-with-angular-1-x.md, docs/spfx/web-parts/guidance/migrate-angular-1-x-applications-to-sharepoint-framework.md, docs/spfx/web-parts/guidance/migrate-jquery-datatables-script-to-spfx.md, docs/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx.md, docs/spfx/web-parts/guidance/reference-third-party-css-styles.md
> Correct the typo - framework option should be 'No JavaScript framework' (not 'No JavaScript **web** framework')
=> Correct the typo - framework option should be 'No JavaScript framework'

includes/snippets/developer-preview-notice.md
The link was with the ending .MD, while on the site the resource has the following URL: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/try-preview-capabilities (without .MD, indeed). I'm not sure if this is a typo in this document or a more general bug in the engine managing remapping of links, which occurs when the document is included into another .MD file (like it is for this specific document). I bet the second option.
Thanks.
A fix to the content.
=> Fixed URL to a docs.microsoft.com document

includes/snippets/open-source/pnp-provisioning-engine.md
Links to these pages are broken when viewed from: 
1- https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-provisioning-framework
2- https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-remote-provisioning
Removed .md extension
=> Removed the markdown extension from the page link

docs/declarative-customization/site-design-powershell.md
-
N/A
Removing PnP PowerShell supportability notice as it doesn't make sense to include this with the SPO Management Shell, which is being supported by Microsoft.
=> Removing PnP PowerShell supportability notice

docs/solution-guidance/multigeo-managedmetadata.md
For term sets and terms to be replicated across geo locations, they need to be set as Available for Tagging (Available for Tagging needs to be enabled), as per confirmation with Taxonomy and MultiGeo Product Group - from a support ticket.
For term sets and terms to be replicated across geo locations, they need to be set as Available for Tagging (Available for Tagging needs to be enabled on them), as per confirmation with Taxonomy and MultiGeo Product Group - from a support ticket (ICM 205115223).
=> Replication of Term sets and terms

docs/declarative-customization/site-design-json-schema.md
- mentioned in #3037
Modifies the documentation for 'activateSPFeature' to add the 'scope' parameter, enabling users to configure a feature activation at either a web or site level. 
This feature was previously undocumented, and picked up from the JSON schema. I have tested the new guidance and confirmed it works.
=> activateSpFeature -  updated to match schema

docs/declarative-customization/column-formatting.md
- Custom formatter documentation update
The PR captures the following updates -
1. Added sample data for Image field 
2. `displayValue` support for Currency columns
3. Column formatting on **Currency** and **Location** columns can now be set using the modern UX
4. Support for `viewBox` and `preserveAspectRatio` for SVG
5. Support for field metadata
=> Custom formatter documentation update

docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md
This proposed change addresses a few issues in the document:
- There was an inconsistency between the one-year client secret script and the three-year script - namely that the first script adds 1 year to the current date on three different lines, while the second calculates the end date first, and uses it. I have made the first script consistent with the second, which is the cleaner and DRY-er of the two.
- The information about deleting old keys was confusing and more complicated than it needed to be:
- It instructed the user to manually copy & paste the key ids in their script, but the line where they needed to be pasted was listed immediately after the line that retrieved them, and lacked anything to even output them to the console so they could be copied.
- Manually copy/pasting them …
=> Improve key deletion script and consistency

docs/features/groupify/groupify-csom.md
Changed article reference from "GetAllTenantThemes" to "CreateGroupForSite" methods.
Changed Microsoft.Online.SharePoint.TenantAdministration.Tenant class description that was also talking about themes instead talking about Create Group for site.
Updating documentation that was describing the wrong method. Article describes code to create Microsoft 365 group for a site, however there are references to Tenant Themes method.
=> Change reference to right method

docs/features/hub-site/create-hub-site-with-powershell.md
On instruction to set Hub Site properties, the parameter "LogoUrl" is pointing to a different URL, mentioned on step 1 (`https://contoso.sharepoint.com/sites/marketing/SiteAssets`)
On instruction to set Hub Site properties, the parameter "LogoUrl" is pointing to a different URL, mentioned on step 1 (`https://contoso.sharepoint.com/sites/marketing/SiteAssets`)
=> Updated LogoUrl parameter value

docs/spfx/use-aadhttpclient-enterpriseapi.md
Typo "Azure function"→"Azure Function"
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi
=> Typo "Azure function"→"Azure Function"

docs/spfx/web-parts/basics/add-an-external-library.md
- fixes #6623
- previous commit removed tip in doc due to a broken link
- maintainer of link updated referenced issue with the correct link
- this commit adds the tip back with the corrected link
=> revert previous commit, replacing text with valid link

docs/declarative-customization/list-form-configuration.md
- fixes #6643
In the body format, displayname is made lowercase.
=> Body format displayname should be lowercase

docs/business-apps/power-automate/get-started/create-your-first-flow.md
The tutorial is for sending emails when adding an item to a SharePoint List. However,  the title says it's when an Item is Created or Modified. This is not correct. I have updated to reflect this. Fixed #6634
- fixes #6634 
Updating text to better reflect the tutorial which is adding a new item to a list. Not for modifying an item in a list.
=> Updating Title to match the tutorial

docs/solution-guidance/configuring-the-pnp-provisioning-engine.md
- mentioned in [Add-PnPDataRowsToProvisioningTemplate : The property or field 'Id' has not been initialized #1838](https://github.com/pnp/PnP-Sites-Core/issues/1838)
Fixed the PowerShell example
- Configuration file needs to be specified as .json file. See parameter specification of `-Configuration` in [Get-PnPProvisioningTemplate - Parameters](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpprovisioningtemplate?view=sharepoint-ps#parameters)
- changed the file names in example to better distinguish configuration file and template file based on [Get-PnPProvisioningTemplate - Examples](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpprovisioningtemplate?view=sharepoint-ps#examples)
=> Configuration file needs to be specified as .json file

docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md
None
**Issue**
The doc is directing users to download the legacy version of PnP PowerShell without reference to the new version or that it is now retired/no longer being maintained.
**Fix**
This PR resolves this by stating that it is legacy and providing a link to the new cross platform version of PnP PowerShell. I have left the link to the old legacy version as it is useful for those using on-premises SharePoint.
=> Fix reference to old version of PnP PowerShell

docs/transform/modernize-userinterface-site-pages-dotnet.md
Update the link to Modernization.PageTransformation sample on GitHub to the correct location. Previous link went to https://github.com/SharePoint/PnP/tree/dev/Samples/Modernization.PageTransformation link should actually now go to https://github.com/pnp/PnP/tree/master/Samples/Modernization.PageTransformation instead.
Update to link to Modernization.PageTransformation sample on GitHub to stop a 404 when the link is clicked.
=> Update Modernization.PageTransformation link

docs/declarative-customization/list-form-conditional-show-hide.md
Fixed typos in article and improved formatting of conditional formulas
=> Fixed typos and improved formatting

docs/spfx/developer-preview-beta-features.md, docs/spfx/release-1.12.1.md, docs/spfx/web-parts/get-started/deploy-web-part-to-cdn.md
- references #6847
- updated instructions for installing spfx dev preview:
- replaced real version numbers & SHA's with fakes
- changed install steps to use `@next` instead of a specific
version to address devs who may copy-paste instructions
- update spfx v1.12.1 release docs & related topic docs for
changes introduced to **./config/deploy-azure-storage.json**
=> Docs update for 1.12.1 & SPFx dev preview installs

docs/declarative-customization/list-form-conditional-show-hide.md
- fixes #6917 
Before submitting this pull requests, I have researched the way lookup column validation works. Results are as follows:
```
=if([$LookupField.name]=='London', 'true', 'false')
```
and this won't work either:
```
=if([$LookupField.lookupValue]=='London', 'true', 'false')
```
and this:
```
=if([$LookupField]=='London', 'true', 'false')
```
This is how lookups look like in the JSON formula validation function:
As a result, the lookup values can be references this way in the JSON formula
```
=if([$LookupField]=='1;#London', 'true', 'false')
```
So, when referencing a lookup value, we need to use this format: `<Lookup ID>;#<Lookup Value>`
=> Added a code sample for lookup columns

docs/declarative-customization/list-form-configuration.md
- mentioned in https://github.com/SharePoint/sp-dev-docs/issues/6684
Removed "debugMode" attribute from sample JSON.
When using `"debugMode": true` while applying JSON to form header/footer from "New form", it shows error message which is confusing to users.
=> Removed "debugMode" attribute from sample JSON

docs/spfx/set-up-your-development-environment.md
- n/a
Update "getting started - setup environment" page to reflect the current version of SPFx (missed in the release notes for the 1.12.1 release)
=> Update SPFx setup doc

docs/spfx/release-1.12.1.md
- fixes #6964
- added missing deprecation notice about the "gulp serve" task with a
fix for those upgrading pre-v1.12.1 projects to SPFx v1.12.1
=> add deprecation note to spfx v1.12.1 release notes

docs/spfx/compatibility.md
- fixes #7009
- added entry for SPFx v1.12.1
- indicated v1.12.0 deprecated
- removed from version numbers because they imply some versions are supported when they arent... for instance, Node LTS v10.x isnt' accurate... LTS for v10 was v10.13.0+
=> update spfx compat doc

docs/general-development/pagination-for-large-result-sets.md
Added a CSOM example and made it important to include the brackets when using the sortlist. Otherwise, queries might fail in certain scenarios
Added a CSOM example on how to add sorting in the keyword query. 
Added a note that it is important the when using the sortlist property, the fieldname must be enclosed by brackets
=> Updated pagination for large results set

docs/business-apps/power-automate/guidance/manage-list-flows.md
Also updating SharePoint list to say Microsoft list
Updating guidance on list permissions needed for run-only users to run flows on the list. Also updating "SharePoint list" to "Microsoft list" to reflect the new product branding.
=> Update list permissions level for run-only flow users

docs/spfx/toolchain/sharepoint-framework-toolchain.md
None, noticed it when reading the docs
Simple typo for a property of the `developer` section on sharepoint `package-solution.json` file. Based on the schema found [here](https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json), it should be `termsOfUseUrl` but the document omits the `s` in `terms`
=> Typo: `termOfUseUrl` -> `termsOfUseUrl`

docs/schema/field-element-list.md
- fixes #7014
Very small typo was raised in #7014
I've added the missing quotation mark.
=> Fixed small typo in data types definition

docs/solution-guidance/Introducing-the-PnP-Provisioning-Engine.md
Add missing closing tags for NavigationNodes and Controls under section 3 / ThreeColumn
> **DELETE THIS LINE BEFORE SUBMITTING** | *Please describe the changes in this …
=> Missing closing-tages

docs/declarative-customization/view-formatting.md
- fixes #7078 
JSON Doesn't allow line-breaks. 
Meaning when a user copies a code example and uses it within SPO they will get an error.
I removed the line-breaks and added an extra ')' to the strings because they were missing one closing char.
There is a side effect to this fix. It diminshes the readability of the example.
=> Remove Line-breaks in code

docs/spfx/viva/get-started/advanced-quick-view-functionality.md
The code reported in the documentation doesn't manage the index property of the IListItem object showed in the details view and so, when the user open the QuickView and click on one items, nothing happen beacause the ${index} in the DetailedQuickViewTemplate.json isn't mapped to any valid attribute and so, the action passed to the QuickView.onAction method, containes ${index} as newIndex.
=> Add steps to allow the DetailedQuickView to works

docs/declarative-customization/column-formatting.md, docs/declarative-customization/formatting-syntax-reference.md
- Documents #6731 
Support approval status column. 
The @currentField and [$_ModerationStatus] will resolve to internal code and @currentField.displayValue and [$_ModerationStatus.displayValue] will resolve to the localized string.
=> Support approval status

docs/spfx/sharepoint-2016-support.md, docs/spfx/sharepoint-2019-support.md, docs/toc.yml
- fixes #7601
- update docs for SharePoint Server 2016 & 2019 to indicate specific versions of Node, Yeoman, SPFx generator that should be installed
=> Clarify install guidance for SharePoint on-prem SPFx dependency versions

docs/declarative-customization/formatting-advanced.md, docs/declarative-customization/formatting-syntax-reference.md
- Minor updates to documentation that covers the recent fixes in formatter
The pull request covers the following -
1. Support replace operator for multi choice and multi user fields
2. Approval Status fields now support numeric as well as text comparisons
3. Allow setting empty value for user and date fields
=> Formatting documentation fixes

docs/declarative-customization/column-formatting.md
Fixed issue with JSON sample under "Add an action button to a field (advanced)" section. `style` property of the `a` element was misplaced in the JSON sample. Hence, styling was not getting applied as expected after using this JSON. 
So, corrected the JSON by removing `style` block under `attributes` and adding it at right place below `a` element.
=> Fixed issue with JSON sample

docs/general-development/site-collection-app-catalog.md
This PR added the prefix `m365` for the commands related to CLI for Microsoft 365 in the command consoler. CLI for Microsoft 365 Commands for adding / removing Site collection was missing the prefix `m365` in the command section. When users copy and paste the command, this may cause the failure and users may not realize the reason for the same
=> Prefixed m365 for `CLI for Microsoft 365` command.

docs/spfx/sharepoint-2019-support.md
I think we are missing the "modern" description at the top of the text. Or maybe i did not get the whole context :)
No related issues
Only a small change at the top of the content. i do really think we are missing the "modern" text at the very first line.
=> Missing modern at the top of the text

docs/business-apps/power-automate/guidance/working-with-get-items-and-get-files.md
An investigation found that these functions aren't supported (by design)
-------
cc: @VesaJuvonen
Removal of section regarding date and time functions as our API (and thus the connector) does not support filtering with these functions.
=> Removing date and time functions

docs/declarative-customization/column-formatting.md
Missing "text-decoration": "none" in the ## Formatting multi-value fields section.
Without this, the text is underlined and does not match the example image that is displayed.
Added missing property "text-decoration": "none" to match the sample image of the JSON output.
=> Fixed basic text formatting due to missing property

docs/spfx/release-1.10.0.md
Removing these lines 35 - 40:
- Create Office Add-Ins using SPFx web parts (dev preview)
- [Docs: Create Outlook add-ins using SharePoint Framework](office-addins-create.md)
- [Tutorial: Create Outlook Web Access extension using SharePoint Framework](web-parts/get-started/office-addins-tutorial.md)
> [!NOTE]
> The Outlook Web Access support is being currently rolled out and can take until end of the release week (10th of January), before it's fully functional in your tenant
Note: The redirects aren't working, and the target content is hard to find. Asking the author for additional information
=> [BrokenLinksH2] Fix path in link

docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md
Updated the PowerShell script for exporting ServicePrincipalCredentials more readable so it is clear to the reader what it is doing.
Also used an object and exported it to CSV instead of a text file
=> Updated export of ServicePrincipalCredentials

docs/spfx/sharepoint-2019-support.md
SharePoint 2019 supports assets developed using SPFx v1.4.1. The existing document indicates that SPFx v1.4.1 is compatible with Node.js v1.10.x and instructs the reader to install this version on Node.js when setting up a SPFx development environment for SharePoint 2019. This is incorrect - SPFx v1.4.1 is not compatible with Node.js v1.10.x, it is only compatible with Node.js v6.x and v8.x. This updates made in this PR correct the information contained in the document in this regard.
=> SharePoint Framework development with SharePoint Server 2019 & SharePoint Server SE - Correct guidance on compatible Node.js versions

docs/declarative-customization/site-design-scoping.md
Note added about SharePoint Admin permissions. Testing indicates that SharePoint Admins will see all Site Templates defines, regardless of any scoping that is done.
=> Update site-design-scoping.md to clarify admin rights

docs/spfx/compatibility.md
Updated versions of Nodejs to include 16 for SPFx 1.15
=> Fixed nodejs compatibility for SPFx 1.15

docs/index.yml
- n/a
- remove global setting for `ms.product` in front mattter
- global setting for this repo doesn't make sense due to mix of
SharePoint Online (& other cloud services) & SharePoint Server (the
on-prem version)
- removing from the global setting as this triggers MSDOCS error as
pages can't have both `ms.product` & `ms.service` present
- ideally we would default to `ms.service` for SPO, but setting globally
is additive
- will add to individual pages as necessary
=> ♻️ update ms.prod/service

docs/solution-guidance/security-apponly-azureacs.md, docs/solution-guidance/security-apponly-azuread.md
The security docs for App-Only connections refers to the `SharePointPnPCoreOnline` NuGet package which has been considered legacy for a while now.
The docs and code samples have been updated to use the new `PnP.Framework` library.
A migration guide from PnP Sites Core to PnP Framework can be found [here](https://github.com/pnp/pnpframework/blob/dev/docs/MigratingFromPnPSitesCore.md).
=> Update security docs to use PnP Framework

docs/spfx/debug-in-vscode.md
- fixes #8178
- removed references to installing Chrome & Edge debugging tools
as the included JS debugger handles this without need for additional
extensions
- remove references to local workbench
- update configuration for chrome to use PWA & incognito which is
the default in SPFx v1.15+ projects
=> Update debugging doc to current state

docs/declarative-customization/formatting-syntax-reference.md
"Content fix" category selected, given that it's an existing content update and no issues are related to this pull request. Available for clarification and further changes.
New toDateString() operator short description, including a basic example. This addition has been implemented by taking the existing content as a writing style reference.
=> toDateString() new operator - Microsoft Official Docs update

docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
- Add links to the Graph dev center where "Microsoft Graph" is mentioned in this document, except for the existing people search link.
- Add links to the Graph dev center and Graph throttling guidance in the "See also" section
=> Add links to Microsoft Graph documentation in throttling document

docs/declarative-customization/formatting-advanced.md
Updated the spelling in the txtContent property of the customCardProps example json. 
from: customCarProps 
to:     customCardProps
N/A
Spelling fix in example Json
=> Updated spelling in txtContent

docs/spfx/use-msgraph.md
Update article "Use the MSGraphClient to connect to Microsoft Graph" to use MSGraphClientV3 instead of MSGraphClient.
=> Update article Use the MSGraphClient to connect to Microsoft Graph to use MSGraphClientV3 instead of MSGraphClient

.github/CONTRIBUTING.md
Fix CONTRIBUTING.md to reference the correct default branch (`main` instead of `master`).
=> Fix CONTRIBUTING.md to reference the correct default branch

docs/apis/webhooks/lists/update-subscription.md
- fixes #7670
Property is displayed as `client-clientState`, this should be `clientState` (validated it with API call).
=> Fixes wrong parameter name in update webhook docs

docs/declarative-customization/column-formatting.md, docs/declarative-customization/formatting-syntax-reference.md
Updating the column formatting developer documentation for the SharePoint Server Subscription Edition Version 22H2 feature update.
Updating column formatting developer documentation for the SharePoint Server Subscription Edition Version 22H2 feature update.
=> Update column formatting dev docs for SPSE 22H2

docs/apis/syntex/rest-applymodel-method.md, docs/apis/syntex/rest-batchdelete-method.md, docs/apis/syntex/rest-createclassificationrequest.md, docs/apis/syntex/rest-createfolderclassificationrequest.md, docs/apis/syntex/rest-createmodel-method.md, docs/apis/syntex/rest-getbytitle-method.md, docs/apis/syntex/rest-getbyuniqueid-method.md, docs/apis/syntex/rest-getmodelandlibraryinfo.md, docs/apis/syntex/rest-updatemodelsettings-method.md, docs/apis/syntex/syntex-model-rest-api.md, docs/apis/webhooks/get-started-webhooks.md, docs/apis/webhooks/lists/create-subscription.md, docs/apis/webhooks/lists/delete-subscription.md, docs/apis/webhooks/lists/get-subscription.md, docs/apis/webhooks/lists/overview-sharepoint-list-webhooks.md, docs/apis/webhooks/lists/update-subscription.md, docs/apis/webhooks/overview-sharepoint-webhooks.md, docs/apis/webhooks/sharepoint-webhooks-using-azure-functions.md, docs/apis/webhooks/webhooks-reference-implementation.md, docs/docfx.json
- n/a
- validation errors with `ms.prod` frontmatter prop:
- invalid value set - value for `ms.service` used as `ms.prod` value
- can't have both `ms.prod` & `ms.service`: mutually exclusive
- removed value from docs & moved to docfx.json for mass set
- added missing `ms.date`
- fixes to other docs to account for above changes
=> 🐞📚 fix errors with frontmatter for syntex docs

docs/declarative-customization/get-started-create-site-design.md
none known
Fix to sample code to match schema.
Including "binddata" and "version" in a Site Script caused it to fail.
Changing the schema reference at the top allowed VSCode to highlight the error, indicating that those aren't allowed.
Removing them resolved the issue.
Seems the schema is being 'more-enforced' than in the past.
=> Update to sample Site Script code

docs/spfx/set-up-your-development-environment.md
In line #45, SharePoint framework vesion number was mentioned as 1.18. instead of 1.18 it should be 1.16 so updated the same
=> updated correct SharePoint framework version - Line #45

docs/spfx/set-up-your-development-environment.md
Just a minor documentation fix (SPFx version 1.16.0 instead of 1.18.0)
=> Wrong SPFx version in docs file (1.18.0 instead of 1.16.0)

docs/solution-guidance/multigeo-userprofileexperience.md
Make it clear that custom profile properties must be set in at least the geo in which a profile is mastered in order to be displayed in people search results.
=> Clarify MG custom profile props behaviour for search

docs/general-development/how-to-set-the-bing-maps-key-at-the-web-and-farm-level-in-sharepoint.md
In the section "### To set the Bing Maps key at the web level with SharePoint PnP PowerShell", the code lines were marked as `csharp`, when they are actually `powershell`. Additionally, in Step 4, the cmdlet shown was not the PnP.PowerShell cmdlet (as indicated in the header), so I've updated it.
=> Corrected code language & updated script

docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md
In the section "To add the Geolocation column to a list using PnP PowerShell", the script lines were shown as `csharp`. I changed them to `powershell`.
=> Changed Code Type

docs/spfx/viva/get-started/advanced-quick-view-functionality.md
N/A
The references to _Advanced CardView Tutorial_ were linking to _Advanced QuickView Tutorial_ which was incorrect. This PR fixes this.
=> Fixed Advanced CardView tutorial references

docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
Removing the atom code editor as the project itself is no longer maintained and archived 
- https://github.blog/2022-06-08-sunsetting-atom/
=> Remove `atom.io` editor

docs/general-development/create-a-workflow-with-elevated-permissions-by-using-the-sharepoint-workflo.md, docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md, docs/general-development/creating-a-workflow-by-using-sharepoint-designer-and-the-sharepoint-wo.md, docs/general-development/custom-content-processing-with-the-content-enrichment-web-service-callout.md, docs/general-development/custom-word-breakers-in-sharepoint-server.md, docs/general-development/developing-with-duet-enterprise-2-0.md, docs/general-development/discovery-in-excel-services-rest-api.md, docs/general-development/excel-services-best-practices.md, docs/general-development/excel-services-known-issues-and-tips.md, docs/general-development/external-events-and-alerts-in-sharepoint.md, docs/general-development/how-to-access-external-data-with-rest-in-sharepoint.md, docs/general-development/how-to-add-a-device-channel-panel-snippet-in-sharepoint.md, docs/general-development/how-to-add-a-security-trim-snippet-in-sharepoint.md, docs/general-development/how-to-add-a-web-part-zone-snippet-in-sharepoint.md
- n/a
- markdown lists should not have explicit numbers (ie: 1,2,3,4)
- ever bullet should be `1.` & let the rendering engine number accordingly... if not working, it's a indentation issue
- this commit is a partial cleanup of this incorrect use of markdown
- fixed other markdown issues found when addressing the numbering issue
=> 🧼 cleanup markdown numbered list

docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md
Removed the "When a file is created or modified in a folder (properties only)" trigger since it doesn't exist. Added verbiage to the "When a file is created or modified (properties only)" description to clarify how to target a specific folder.
=> Remove non-existent trigger and update another trigger's description

docs/spfx/set-up-your-development-environment.md
- fixes #9023
- doc referenced a specific Node version range... we don't need this level of detail in the docs as it makes it cumbersome to maintain, instead, just refer to the Node version and let the reader refer to the Node site/docs for the actual LTS version range for the major version we reference
- fixed numerous typos, grammatical, & formatting issues
=> 🐞 remove unnecessary specifics from doc

docs/spfx/release-1.15.2.md, docs/spfx/use-aadhttpclient.md
- n/a
Add docs explaining how to grant permissions to SPO for an AAD app defined in another tenant from the SPO tenant. To do this, you must create the app's service principal in the SPO tenant. This capability was added in SPFx v1.15.2... these docs update the existing app registration docs with instructions & additional references.
Also updated the SPFx v1.15.2 release notes to point to the new content
=> 📜 add docs for granting permission to apps defined in other AAD tenants

docs/spfx/sharepoint-2019-and-subscription-edition-support.md
N/A
Update SPFx development guidance of SharePoint Server 2019 and Subscription Edition to support Node v16
Signing off by SharePoint Server PG, POC: Wesley Wu
=> Update SPFx dev guidance of SP19 & SPSE to support Node 16

docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md
- fixes #9170 
The base64 decode may fail for some generated client secret from AAD. Use a safe way encode it again to avoid such cases.
=> Fix decode base 64 may fail for some client secret

docs/sp-add-ins/determine-sharepoint-rest-service-endpoint-uris.md
This commit adds the missing bullets to the elements of the bulleted list that appears in the "Tip" info box at the top of the page.
Fixes a formatting issue by adding bullets to items which are meant to be part of a bulleted list
=> Add missing bullets to the list of resources

docs/general-development/how-to-create-a-page-layout-in-sharepoint.md, docs/general-development/how-to-make-custom-css-files-themable-in-sharepoint.md
In reviewing instances of the soon to be disallowed head HTML tag across Learn, I found that this article refers to head without escaping it. Learn doesn't know what to do with this tag, so it results in content loss.
n/a
Changed references to the head HTML tag to inline code. I didn't update ms.date because this isn't a substantive update.
=> wrapped head tags in code so they aren't stripped from output

docs/spfx/office/overview.md
Added the "teamsmodern" value for host.name to include the new Microsoft Teams client option.
The original document was missing the "TeamsModern" option and as such code would fail in the new Microsoft Teams client.
I simply added the "teamsmodern" option to the case switch.
=> Update overview.md to include "TeamsModern" option

docs/embedded/concepts/app-concepts/limits-calling.md
Added clarity that SharePoint Embedded limits are preview limits only and are subject to change and can be changed per requested. This is in response to feedback from two customer inquiries.
- n/a
Added clarity that SharePoint Embedded limits are preview limits only and are subject to change and can be changed per requested. This is in response to feedback from two customer inquiries.
=> SPE preview limit clarity

docs/spfx/build-for-teams-meeting-app.md
Small fix to a Teams manifest.json file. With the given version value there's an error when validating the manifest because the expected format of the version is "x.x.x" and not, like the example, "1.0".
=> Fix teams manifest in sample code

docs/index.yml
- fix #9477
fix broken links on spdev docs landing page to spe tutorials moved > ms learning
=> 🐞 change links for spe tutorials > msl modules

.openpublishing.redirection.json
- n/a
Noticed some external links not under this repo's control created hard links to previously relocated content (sharepoint embedded learning modules). This PR includes redirects from the old path => new path.
=> Add redirects for moved SPE MSL modules

docs/spfx/toolchain/configure-sass.md
Correct spelling of Sass, which is the official spelling and now seems to be established usage in the wider web development community.
Changes to spelling of Sass (from SASS).
=> Change capitalization from SASS to Sass

docs/spfx/viva/features/focus-feature/FocusFeatureTutorial.md, docs/spfx/viva/get-started/actions/geolocation/GeolocationTutorial.md, docs/spfx/viva/get-started/actions/media-upload/MediaUploadTutorial.md, docs/spfx/viva/get-started/build-data-visualization-adaptive-card-extension.md, docs/spfx/viva/get-started/build-first-sharepoint-adaptive-card-extension.md, docs/spfx/viva/get-started/build-people-search-adaptive-card-extension.md, docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
- n/a
Multiple docs incorrectly referneced the `{tenantdomain}` placeholder in the serve.json configuration. This comment removes those incorrect statements.
=> ♻️ remove incorrect statements about `{tenantdomain}`

docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md
import { override } from '@microsoft/decorators'; is not used in this sample
import { override } from '@microsoft/decorators'; is not used in this sample.  Removed line.
=> Removing import { override } from '@microsoft/decorators';

docs/embedded/concepts/app-concepts/auth.md
No issue reported.
Remove references to Sites.FullControl.All from SPE auth docs
SPE container type management operations are only exposed via
PowerShell cmdlets at the moment. The SharePoint PowerShell module
is configured to request the right access to perform container type
operations. Clarified that the user executing the cmdlets must be
either a SPE administrator or a global administrator.
Add Graph link for SPE container permissions
In the SPE auth docs, added a link to the container create add
permissions endpoint when talking about container permissions.
=> [SPE] Remove references to Sites.FullControl.All from SPE auth docs

docs/solution-guidance/applying-pnp-templates.md
- mentioned in #9708
As mentioned in #9708, in the examples of Invoke-PnPSiteTemplate, the connection was assigned to the SharePoint admin site, which is incorrect. According to the PnP PowerShell documentation, for this cmdlet, the target web should be connected. https://pnp.github.io/powershell/cmdlets/Invoke-PnPSiteTemplate.html
Minor wording fixes.
=> Fix connection url for Invoke-PnPSiteTemplate - applying-pnp-template.md

docs/apis/webhooks/webhooks-reference-implementation.md
N/A
This fixes a broken link caused by misplaced backticks.
I'm not sure if I need to update `ms.date` for an inconsequential change.
=> Fix webhook renewal link

docs/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries.md
- fixes #9657
As mentioned in issue #9657, there was an incorrect path to the webpart props. The IHelloWorldProps interface is created in the same file as HelloWorldWebPart (HelloWorldWebPart.ts).
=> Change Webpart props paths in simplify-adding-web-parts-with-preconfigured-entries.md

docs/declarative-customization/site-design-o365cli.md
N/A
This pull request fixes the faulty URL for **Logging in to Office 365** which was in the section, [Getting Started](https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-o365cli#getting-started)
=> Fixed the broken URL for CLI M365 Login

docs/embedded/concepts/app-concepts/containertypes.md, docs/embedded/concepts/content-experiences/user-experiences-overview.md
- [x Example checked item (*delete this line*)
- fixes unclear explanation of M365 discoverability and Copilot.
- fixes unclear explanation on container type for trial.
Explicitly call out default behavior of M365 discoverability for SPE is to hide SPE app content from M365 surfaces, and the default behavior includes hiding these content from M365 Copilot grounding.
Explicitly call out to create a new container type for trial, all containers of an existing container type must be permanently deleted, including the ones in the deleted container collection.
=> Update user-experiences-overview.md and containertypes.md

docs/declarative-customization/formatting-syntax-reference.md
- fixes #9411
There were some changes in the way image fields are stored on the server. They don't have the properties `serverUrl`, `id` etc anymore. Only the filename is present. Updating the custom formatter documentation to reflect the same.
=> Update custom formatter docs[Image field]

docs/declarative-customization/site-theming/sharepoint-site-theming-json-schema.md
The info tag previously only listed that the generator does not present the "error" and "accent" key/value pairs for color slots in a SharePoint site theme palette.
This update provides the full list of key/value pairs of color slots, so that users are better equipped to create their palettes.
=> Updated Generator 'Info' For "SharePoint site theming: JSON schema"

docs/embedded/concepts/app-concepts/auth.md
Added a link to the Entra PowerShell cmdlet they can use to add app permissions, and also to the Azure CLI command. A customer thought they can only perform this action by editing the application manifest as text. This makes it explicit that there are other options for them to add app permissions.
=> Add note to Entra PS and az CLI in SPE auth page

docs/spfx/extensions/guidance/using-custom-dialogs-with-spfx.md
- fixes
- partially
- mentioned in #8795
Adds a console command to the tutorial that installs the correct React and React-dom version
Following the tutorials with SPFx 1.20, can cause it to target 17.0.2 instead of 17.0.1 causing the extension to fail.
I think the issue of needing to specify the version is known since last year https://github.com/SharePoint/sp-dev-docs/issues/8795#issuecomment-1450319157
=> Adds to the tutorial the requirement of installing the correct React version

docs/embedded/concepts/app-concepts/limits-calling.md
Number of containers of a container type is a limit per consuming tenant. Storage per container type is also a limit per consuming tenant. That was not clear from the documentation, as it just said "per tenant" and there are two possible tenants involved in SPE, owning and consuming. And the previous limits were for the owning tenant, so customers were confused.
=> Clarify the SPE limits that apply to consuming tenants

docs/declarative-customization/site-design-json-schema.md, docs/declarative-customization/site-design-overview.md
- fixes -
- partially - 
- mentioned in - 
Removed properties ("version", "bindata") in the json because they are not part of the linked schema.json and the example json is not valid like that. Please either fix the doku (e.g. with this PR), fix the schema to match the given examples or describe a use case for this fields. Maybe more pages need to be fixed?
=> SharePoint site scripts - Invalid properties in json examples

docs/apis/webhooks/sharepoint-webhooks-using-azd-template.md, docs/apis/webhooks/sharepoint-webhooks-using-azure-functions.md
Proposing a new article to create Azure functions for SharePoint webhooks using an azd template
=> New article - Create Azure functions for SharePoint webhooks using an azd template

docs/apis/webhooks/sharepoint-webhooks-using-azd-template.md, docs/toc.yml
Article https://learn.microsoft.com/en-us/sharepoint/dev/apis/webhooks/sharepoint-webhooks-using-azd-template is not referenced in the menu, and when viewing the article, it is not integrated to the navigation.
I assume this might be a problem with the markdown header, so I open this PR to try to fix it
=> Fix the navigation for article "SharePoint webhooks using azd"

docs/declarative-customization/view-commandbar-formatting.md
Some keys in the commandBarCustomization schema have been updated. Updating the documentation with new keys.
```javascript
'new' (Dropdown) → 'newComposite'
'upload' -> 'uploadCommand'
'sync' → 'syncCommand'
'addShortcut' → 'addShortcutToOneDriveCommand'
'pinToQuickAccess' → 'PinToQuickAccessCommand'
```
> - When changing a page, ensure you update the `ms.date` front matter wih the current …
=> Updated keys for command bar customization.

docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
Added table of existing limits into the article to reduce confusion.
=> Update to sharepoint throttling page

docs/declarative-customization/list-form-configuration.md
🎯 Add documentation for Custom Formatter Read-Only Fields in Microsoft Lists
📝 Description:
This PR introduces detailed documentation for the new Custom Formatter for Read-Only Fields feature in Microsoft Lists. The formatter allows fields to appear as read-only in various form views — enhancing usability for AI-generated content and preventing accidental edits.
✅ Key Highlights:
Introduction and Purpose: Explains the need for read-only fields, especially in AI-driven list item creation.
Field Settings: Defines name and readonly properties for easy configuration.
Behavior Breakdown: Details how the formatter behaves across New Item, Edit Form, and Edit All modes.
Example Use Cases: Illustrates practical scenarios like CRM bot-generated tickets.
📌 Why It Matters:
Enables users to view …
=> Added a new feature in Custom formatter for making fields readonly

docs/embedded/development/auth.md
- fixes n/a
- partially n/a
- mentioned in n/a
Mention the exceptional access pattern required for the SharePoint Embedded copilot experience.
=> Add SPE exceptional access pattern for SPE copilot

docs/embedded/development/tutorials/spe-da-vscode.md
Updated SDK version to v1.0.8
Updated SDK version to v1.0.8
=> Update SDK version to v1.0.8

docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md, docs/general-development/site-collection-app-catalog.md
- Updated PnP PowerShell connection instructions across the documentation to use interactive login (`-Interactive`) and Client ID (`-ClientId`), replacing the [deprecated](https://pnp.github.io/blog/pnp-powershell/pnp-powershell-v3-0-0/#:~:text=UseWebLogin%20has%20been%20removed,more%20modern%20ways%20of%20authenticating) `-UseWebLogin` method.
- Ensured that all references to login methods aligned with the latest authentication practices, including the use of a registered Azure AD (Entra ID) application.
=> Update PnP PowerShell connection instructions to use interactive login with Client ID

.github/label-actions.yml, .github/workflows/label-actions.yml
None
An automated workflow to close and respond to issues when they are labeled with `type:archive-orld-issue` as discussed with @vesajuvonen.
=> Added automated issue closing for archived.

docs/spfx/debug-in-vscode.md, docs/spfx/debug-modern-pages.md, docs/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions.md, docs/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions.md, docs/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions.md
> debug manifests.js file path reference updated
=> debug manifests.js file path reference updated

docs/spfx/release-1.21.1.md
I am super sorry for opening a PR without a related issue but I just wanted to do a quick and small fixup in the release notes tip where I think we mention version 1.17.1 by mistake 
It most probably should be 1.21.1
=> Minor fixup in 1.21.1 release notes

docs/embedded/development/tutorials/spe-da-vscode.md
Update SDK to v1.0.9 to resolve session health issues.
=> Update SDK to version v1.0.9

docs/embedded/development/auth.md
Some SPE APIs still require a user licence to work in user-delegated mode. These are now documented in the Auth article.
=> Clarify exceptional access pattern for SPE requiring user licenses

docs/embedded/development/limits-calling.md
Updates the container type limit per tenant to 25.
=> SPE: Update Container Type limit per tenant

docs/declarative-customization/formatting-syntax-reference.md
🎯 Update Important Notice on CSS Support in Microsoft Lists Custom Formatter
🔧 Changes Made
Updated the formatting guidance to highlight that float style prop no longer supported in custom formatter
Introduced an CAUTIONcallout using [!CAUTION] Markdown syntax to improve visibility and clarity for users.
Recommended Gallery View as a more stable alternative for users relying on unsupported styling.
📌 Why This Change?
Ensures users are aware of the deprecation of float in custom formatter styles.
Encourages a smoother transition by suggesting a more reliable solution (Gallery View).
Enhances readability and provides a clear, visually distinct warning.
=> Deprecating float style prop in custom formatter

docs/embedded/development/auth.md, docs/embedded/development/declarative-agent/spe-da-adv.md, docs/embedded/development/tutorials/spe-da-vscode.md
Updates SharePoint Embedde copilot to SharePoint Embedded agent for improved clarity.
=> Update SharePoint Embedded copilot to agent

docs/embedded/development/auth.md, docs/embedded/development/content-experiences/office-experience.md
Documents user license requirements for @mentions in Office documents for SPE.
=> Document user license requirements for @-mentions in SPE docs

docs/spfx/extensions/get-started/building-simple-field-customizer.md
I'm not sure on the wording, but there SHOULD be a warning on the page ensuring that people are aware of the upcoming retirement
N/A
A retirement warning for SPFx field customizers
=> Added retirement warning on Field customizers

docs/spfx/toolchain/sharepoint-framework-toolchain-rushstack-heft.md, docs/spfx/toolchain/sharepoint-framework-toolchain.md, docs/toc.yml
- n/a
Documents the transition from gulp-based to Rush Stack/Heft-based toolchain, starting with SPFx v1.22.
Add doc explaining the rationale for the change, migration timeline, and impact on existing projects. Updates existing toolchain documentation to clarify that it applies to pre-v1.22 versions and adds cross-references between the two approaches.
Additional doc(s) will include migration guidance
=> add doc for SPFx Rush Stack + Heft + Webpack toolchain

docs/spfx/web-parts/basics/notes-on-solution-packaging.md
Update notes around using features and correctly state what will happen if the features is left as an empty array
- fixes #10423
Update the documentation around 'features'. Specifically, leaving features as an empty array will not show your webparts when you upload the sppkg
```
"features": []
```
This should probably be addressed in the sppkg build pipeline. But until that happens, it should be outlined in the docs
=> Address incorrect documentation around 'features'
