SharePoint/sp-dev-docs

- README.md
I have also added the tags in SharePoint.StackExchange.com with descriptions, and tagged a few questions.
> Fixed broken link and added links to stackexchange tags

- misc/SharePointDocumentationToc.xml
Removed release notes folder from TOC for webhooks release.
> removed release notes folder for webhooks release.

- docs/apis/webhooks/webhooks-reference-implementation.md
Updated reference implementation article with the right links to GitHub sample and classes. Fixed few unordered list bullets to render properly in dev.office.com.
> updated GitHub links and unordered lists.

- .github/CONTRIBUTING.md
Updated contribution guidelines to address SPFx folder structure and added webhooks folder structure as well.
> Updates to contribution guidelines

- docs/spfx/web-parts/developer-guide/connect-client-side-web-parts-to-aad-secured-resources.md
Guidance around using OAuth with implicit flow in SharePoint Framework web parts.
> Added OAuth implicit flow guidance

- docs/spfx/web-parts/developer-guide/connect-client-side-web-parts-to-aad-secured-resources.md
Additional information about OAuth implicit flow and Internet Explorer security zones
> Added information about IE security zones

- docs/spfx/web-parts/developer-guide/connect-client-side-web-parts-to-aad-secured-resources.md
Updated content based on tech writer's feedback.
> Updated based on tech writer's feedback

- README.md
- docs/spfx/sharepoint-framework-toolchain.md
| Related issues?     | #242 
- The README is updated with Drop 5 information.
- Added a new documentation explaining the SharePoint Framework Toolchain.
> Update to main README and New Doc on SPFx Toolchain

- README.md
- docs/spfx/sharepoint-framework-toolchain.md
- misc/SharePointDocumentationToc.xml
| Q | A |
| --- | --- |
| content fix? | yes? |
- SharePoint Framework Toolchain doc updated after voice review.
- Updated TOC to include SharePoint Framework Toolchain.
> Updates to SharePoint Framework Toolchain doc after voice review

- docs/spfx/sharepoint-framework-toolchain.md
Updated SharePoint Framework Toolchain doc with more information around build tasks and fixed formatting issues.
> Updates to SharePoint Framework Toolchain doc

- docs/spfx/set-up-your-developer-tenant.md
- docs/spfx/set-up-your-development-environment.md
- docs/spfx/web-parts/basics/use-visual-studio.md
- docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
- docs/spfx/web-parts/get-started/connect-to-sharepoint.md
- docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md
- misc/SharePointDocumentationToc.xml
Updated docs to latest drop changes.
> Updated docs to latest drop changes.

- docs/spfx/set-up-your-developer-tenant.md
- docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md
- docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
* Updated the docs to reflect sp-webpart-base API changes
* Modified the section to add property pane fields in HelloWorld tutorial to a better flow.
> Updated the docs to reflect sp-webpart-base API changes

- docs/spfx/sharepoint-framework-toolchain.md
Correct the package name of "@microsoft/office-ui-fabric-react-bundle".
Correct the package name of "@microsoft/office-ui-fabric-react-bundle".
> Correct a package name.

- docs/spfx/web-parts/guidance/team-based-development-on-sharepoint-framework.md
Added guidance on team-based development.
> Guidance team development

- docs/spfx/web-parts/guidance/share-data-between-web-parts.md
Added information about using SharePoint Framework services for sharing data between web parts to the existing article.
> Added information about using SPFx services

- docs/spfx/web-parts/get-started/use-fabric-react-components.md
…Fabric and Fabric React with SPFx.
Fixed the tutorial to work with latest updates and guidance in using Fabric and Fabric React with SPFx.
> Fixes to using Fabric React with SPFx

- docs/spfx/web-parts/get-started/use-fabric-react-components.md
Fixed the tutorial to work with latest updates and guidance in using Fabric and Fabric React with SPFx.
> Fixes to: Using Fabric and Fabric React with SPFx doc

- docs/apis/webhooks/get-started-webhooks.md
Some details were missing. I tried to add clarity around those.
> Added some clarity around application registration.

- docs/spfx/web-parts/guidance/build-custom-property-pane-controls.md
Updated tutorial with latest version of SharePoint Framework
> Update build-custom-property-pane-controls.md with latest version of framework

- docs/spfx/toolchain/provision-sharepoint-assets.md
- misc/SharePointDocumentationToc.xml
Update TOC to include provision sharepoint items and yeoman generator docs.
> Update TOC to include provision sharepoint items and yeoman generator docs

- docs/spfx/web-parts/guidance/use-existing-javascript-libraries.md
Updated the guidance on using external libraries to match SPFx GA.
> Updated external libraries guidance to GA

- docs/spfx/web-parts/guidance/share-data-between-web-parts.md
Global variables is not best practice, anywhere!
Until this article is revised to show another pattern, we should atleast include this disclaimer.
> Added a note re: Global variables

- docs/spfx/web-parts/guidance/call-microsoft-graph-from-your-web-part.md
Updated guidance on calling MS Graph to SPFx GA
> Updated guidance on calling MS Graph to SPFx GA

- docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md
fixed the filename to the correct one.
a fix for an incorrect filename
> wrong filename - seems to be a copy&paste problem

- docs/spfx/web-parts/guidance/call-microsoft-graph-from-your-web-part.md
| Related issues?     | https://github.com/SharePoint/sp-dev-fx-webparts/issues/150
Updated ADAL JS patch code snippet with code to resize the ADAL JS iframe to fix https://github.com/SharePoint/sp-dev-fx-webparts/issues/150
> Updated MS Graph guidance with the latest ADAL JS patch

- docs/spfx/web-parts/guidance/migrate-script-editor-web-part-customizations.md
Added guidance on migrating Script Editor Web Part customizations
> Added guidance on migrating Script Editor Web Part customizations

- docs/spfx/debug-in-vscode.md
Update for the debug documentation. The first line of the webpack config should also contain the src directory.
> Small fix for the webpack config

- reference/spfx/sp-core-library/log.md
- reference/spfx/sp-core-library/urlqueryparametercollection.md
- reference/spfx/sp-core-library/validate.md
Added sample on how to use the functionality
> Added usage samples

- docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md
Small update of guidance instructions - wording
> minimal updates to instructions

- docs/spfx/web-parts/get-started/deploy-web-part-to-cdn.md
Changed 'updaging' to 'updating'
Fixed spelling error.l
> Fixed typo on Deploying to CDN page

- docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md
Fixed type value for the sample Site Column
> Fixed sample Site Column type to OutcomeChoice

- docs/spfx/extensions/get-started/build-a-hello-world-extension.md
| Related issues?     | None
Minor grammatical updates
> Minor grammatical updates

- docs/spfx/toolchain/integrate-gulp-tasks-in-build-pipeline.md
This article incorrectly references 3 images within it.
> Incorrect Image references on wiki page

- docs/spfx/toolchain/sharepoint-framework-toolchain.md
There is no "nuke", but "clean"
| Related issues?     | -
Documentation fix
> Corrected gulp parameter

- docs/spfx/toolchain/sharepoint-framework-toolchain.md
Fixed broken relative image path
| Related issues?     | -
Fixed broken relative image path (I suspect more of those might be in the docs if some restructuring has been going on...)
> Fixed broken relative image path

- docs/spfx/team-based-development-on-sharepoint-framework.md
Minor fix: updated links to external resources
> Updated links to external resources

- docs/spfx/sharepoint-framework-overview.md
- docs/spfx/web-parts/overview-client-side-web-parts.md
| content fix?         |  yes
| Related issues?   | not applied
misunderstanding of what is stated in the beginning of the article and what is stated at the end. // Fixing  404 error
> clarify idea expressed in the text // Fixing 404 error 

- docs/spfx/web-parts/guidance/migrate-jquery-datatables-script-to-spfx.md
- docs/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx.md
Added links to the source code of the projects used in tutorials
> Added links to the source code of the projects used in tutorials

- docs/sp-add-ins/authorization-and-authentication-of-sharepoint-add-ins.md
- Fix broken formatting in authorization-and-authentication-of-sharepoint-add-ins.md
- Fix a few spelling issues - "adc-in" => "add-in", add missing spaces, etc.
> Fix formatting in authorization-and-authentication MD document

- docs/spfx/call-microsoft-graph-using-graphhttpclient.md
| Related issues?     | #621 
Added guidance on using the GraphHttpClient
> Added guidance on using the GraphHttpClient

- docs/spfx/sharepoint-framework-overview.md
I've provided some grammar and information changes (such as the framework no longer being just in preview)
> Grammar / information changes to SPFx intro page

- docs/spfx/web-parts/basics/add-an-external-library.md
- Some code snippets had no indentation making readability sub-optimal.
- Type def acquisition used outdated TSD utility; switched to using scoped types with NPM (`@types`).
- One part referred to a library (validator) & incorrectly said it didn't have a type definition, but it does. Modified to say it does but for the sake of argument, reworded to be more accurate for article.
> update formatting & type def acquisition

- docs/spfx/known-issues-and-common-questions.md
> fixed typos

- docs/spfx/extensions/guidance/using-custom-dialogs-with-spfx.md
| Related issues?    | fixes #X, partially #Y, mentioned in #Z
Updated the text to use "dialog box" instead of dialog for clarity/consistency/globalization. Made other edits to the text for readability and consistency with MS standards.
> Edit pass to update dialog box terminology.

- docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md
It is required two underscores __ instead of one _ in the request to add list item.
metadata property contains incorrect ListItem type
> Fix bugs in code

- docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md
See https://blog.mastykarz.nl/typescript-version-sharepoint-framework-projects/?utm_content=buffer382a2&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer. We need to explicitly downgrade to v2.
| content fix?        | yes?
> SPFx does not support jQuery v3

- docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md
| content fix?        | ]yes
Fixes small typo in docs for deploying UI Extensions.
> fix typo in deployment steps

- docs/general-development/sharepoint-search-rest-api-overview.md
| Related issues?     | fixes QueryText parameter POST sample
The original sample would return an error. This fix should work, but needs to be tested to confirm.
> fixed QueryText parameter POST sample

- docs/spfx/extensions/overview-extensions.md
- docs/spfx/toolchain/sharepoint-framework-toolchain.md
> Edit pass.

- docs/apis/webhooks/sharepoint-webhooks-using-azure-functions.md
- docs/spfx/extensions/overview-extensions.md
- docs/spfx/toolchain/sharepoint-framework-toolchain.md
Quick additional explanation in the Azure functions for SharePoint webhooks article to explain a different approach for getting your SharePoint web hook function anonymously accessible.
> small update to explain potential fix for difference in Azure function webhooks

- docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md
> Fixed Typo for Understanding

- docs/spfx/web-parts/basics/add-an-external-library.md
- docs/spfx/web-parts/basics/integrate-with-property-pane.md
- docs/spfx/web-parts/basics/notes-on-solution-packaging.md
- docs/spfx/web-parts/basics/working-with-requestdigest.md
- docs/spfx/web-parts/guidance/reference-third-party-css-styles.md
- docs/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries.md
- docs/spfx/web-parts/guidance/use-existing-javascript-libraries.md
Updated SPFx Basics guidance to reflect the API changes from the latest version of SPFx
> Updated SPFx Basics guidance

- docs/spfx/css-recommendations.md
> Added CSS recommendations guide

- docs/spfx/extensions/changes-between-dev-preview-and-rc.md
Fixed link to updated placeholder tutorial. There was an extra "." in the MD syntax that prevented the link from rendering.
> Fixed link to updated placeholder tutorial

- docs/spfx/web-parts/guidance/build-custom-property-pane-controls.md
- docs/spfx/web-parts/guidance/connect-to-sharepoint-using-jsom.md
- docs/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties.md
- docs/spfx/web-parts/guidance/validate-web-part-property-values.md
Updates to web parts guidance to align it with the latest version of SPFx.
> Updates to web parts guidance

- docs/spfx/web-parts/guidance/migrate-jquery-datatables-script-to-spfx.md
- docs/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx.md
- docs/spfx/web-parts/guidance/share-data-between-web-parts.md
- docs/spfx/web-parts/guidance/tutorial-share-data-between-web-parts-global-variable.md
Updated guidance to match the latest version of the SharePoint Framework
> Updated guidance

- docs/spfx/css-recommendations.md
Changes for readability.
Minor amends to the first paragraph of css-recommendations.md for readability.
> Minor amends to the first paragraph of css-recommendations.md

- docs/spfx/enterprise-guidance.md
Simple typo fix. Changed "proove" to "prove"
> Typo: change proove to prove

- docs/spfx/extensions/overview-extensions.md
> Spelling type corrected

- .openpublishing.publish.config.json
- docs/design/grid-and-responsive-design.md
> Added link to SharePoint toolkit.

- docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md
Fix code snippet that displayed not correctly.
> Fix Code Snippet

- docs/spfx/extensions/overview-extensions.md
Fixed simple misspelling of "Framework" in first line of the document
> Fix misspelling of "Framework" in first line

- docs/declarative-customization/site-theming/sharepoint-site-theming-csom.md
- docs/declarative-customization/site-theming/sharepoint-site-theming-json-schema.md
- docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md
- docs/declarative-customization/site-theming/sharepoint-site-theming-powershell.md
- docs/declarative-customization/site-theming/sharepoint-site-theming-rest-api.md
- docs/spfx/call-microsoft-graph-using-graphhttpclient.md
- docs/spfx/overview-graphhttpclient.md
- docs/toc.yml
> Edit pass on GraphHttpClient and Site theming topics.

- docs/declarative-customization/site-theming/sharepoint-site-theming-csom.md
- docs/declarative-customization/site-theming/sharepoint-site-theming-json-schema.md
- docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md
- docs/declarative-customization/site-theming/sharepoint-site-theming-powershell.md
- docs/declarative-customization/site-theming/sharepoint-site-theming-rest-api.md
- docs/spfx/call-microsoft-graph-using-graphhttpclient.md
- docs/spfx/overview-graphhttpclient.md
- docs/toc.yml
> Merge to publish.

- docs/declarative-customization/site-theming/sharepoint-site-theming-csom.md
> Sync branches.

- docs/sp-add-ins/sharepoint-add-ins.md
| Related issues?     | NA
Fix minor grammatical errors and typos in **sp-dev-docs/docs/sp-add-ins/sharepoint-add-ins.md**.
Also change on-premise to on-premises.
> Fix minor grammatical errors and typos

- docs/general-development/search-connector-framework-in-sharepoint.md
The broken link to MyFileConnector sample is fixed
> Broken link to MyFileConnector sample fixed

- docs/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator.md
Fixed typographical error in table.
> Fixed typo

- docs/spfx/toolchain/extending-webpack-in-build-pipeline.md
| New article?        | no?
| Related issues?     | fixes #927 
This updates the documentation around extending webpack in SPFx projects.
> Updating the "Extending Webpack" documentation.

- docs/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts.md
Updated tutorial on using SP PnP JS with SPFx to the latest version of SPFx.
> Updated tutorial on using SP PnP JS with SPFx

- docs/general-development/incoming-claims-signing-into-sharepoint.md
Simple text correction:
"SharePoint Serverthen does"... was changed to "SharePoint Server then does"
> Simple text correction on line 68

- docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md
Light copy edits. Added numbered lists, edited sentences for clarity, corrected punctuation and capitalization errors. Changes made per Task 1811839.
> Edit complete

- docs/spfx/extensions/get-started/hosting-extension-from-office365-cdn.md
Added numbered lists, corrected punctuation and grammar, corrected links. Per Task 1811840.
> Edit complete.

- docs/spfx/team-based-development-on-sharepoint-framework.md
Updated team-based development guidance
> Updated team-based development guidance

- docs/spfx/sharepoint-2016-support.md
Updated guidance on SPFx development for SP2016 FP2
> Updated guidance on SPFx development for SP2016 FP2

- docs/spfx/overview-graphhttpclient.md
Updated the GraphHttpClient guidance to the latest version of the SharePoint Framework
> Updated the GraphHttpClient guidance

- docs/spfx/set-up-your-development-environment.md
Fixed typos and updated the development environment setup guide
> Updated the development environment setup guide

- docs/spfx/extensions/get-started/build-a-hello-world-extension.md
- docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md
- docs/spfx/extensions/get-started/building-simple-field-customizer.md
- docs/spfx/extensions/guidance/using-custom-dialogs-with-spfx.md
- docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md
- docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
- docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md
- docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md
- docs/spfx/web-parts/get-started/use-fabric-react-components.md
- docs/spfx/web-parts/guidance/build-client-side-web-parts-with-angular-1-x.md
- docs/spfx/web-parts/guidance/build-custom-property-pane-controls.md
- docs/spfx/web-parts/guidance/connect-to-sharepoint-using-jsom.md
- docs/spfx/web-parts/guidance/localize-web-parts.md
- docs/spfx/web-parts/guidance/migrate-angular-1-x-applications-to-sharepoint-framework.md
- docs/spfx/web-parts/guidance/migrate-jquery-datatables-script-to-spfx.md
- docs/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx.md
- docs/spfx/web-parts/guidance/reference-third-party-css-styles.md
- docs/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries.md
- docs/spfx/web-parts/guidance/tutorial-share-data-between-web-parts-global-variable.md
- docs/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties.md
- docs/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts.md
- docs/spfx/web-parts/guidance/validate-web-part-property-values.md
Added npm shrinkwrap to all tutorials
> Added npm shrinkwrap to all tutorials

- docs/spfx/extensions/get-started/building-simple-field-customizer.md
Created a section for query parameter details so it wouldn't mess up the numbered list
> moved Query Para details to its own section

- docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md
Moved "More details about query parameters" to own section to avoid messing up table
> Moved Query Para details to own section

- docs/spfx/update-latest-packages.md
Updated the guidance on updating SharePoint Framework packages
> Updated the guidance on updating SharePoint Framework packages

- docs/design/themes-colors.md
I'm not sure if my last pull request went through; please use this version to merge with master and push to staging
Fixes to update tables
> New changes to table

- docs/design/themes-colors.md
First time, I didn't do it right; this should be right now. The "rowspan" lines were missing an end </td>
These should be the correct fixes for these tables.
> Second table fix

- docs/spfx/extensions/get-started/building-simple-field-customizer.md
Steps 9 and 10
Fixed spacing/numbering in Debug, #9 and #10
> Fixed numbering/spacing issue in Debug section

- docs/spfx/extensions/get-started/hosting-extension-from-office365-cdn.md
> Error in PowerShell command

- docs/toc.yml
Reorganized table of contents to better accommodate the documentation contents
> Reorganized TOC

- docs/general-development/how-to-build-and-deploy-workflow-custom-actions.md
Fixed the link to https://code.msdn.microsoft.com/SharePoint-2013-workflow-41e5c0f9
Fixed the link to https://code.msdn.microsoft.com/SharePoint-2013-workflow-41e5c0f9
> Broken link

- docs/spfx/office-ui-fabric-integration.md
Added missing ~ when linking in styles from OUIF react.
> Added ~ for import statement

- docs/solution-guidance/portal-rollout.md
Corrected typos
Corrected typos in the text
> Typos in portal-rollout.md

- docs/solution-guidance/sharepoint-metadata-site-navigation-and-publishing-site-features.md
PnP Responsive UI is the recommanded way to make a classic site Responsive.
Added a link to PnP Responsive UI sample
> Added PnP Responsive UI as an example

- docs/design/accessibility.md
> Converted images to HTML tables.

- docs/spfx/roadmap.md
> Fix some typos.

- docs/spfx/known-issues-and-common-questions.md
> Minor improvement for improved readability

- docs/solution-guidance/Branding-and-site-provisioning-solutions-for-SharePoint.md
Nothing changed in branding and site provisioning between 2013 and 2016 so this article also applies to SharePoint Server 2016
> Added SharePoint Server 2016

- docs/declarative-customization/site-theming/sharepoint-site-theming-rest-api.md
- docs/sp-add-ins/access-sharepoint-data-from-add-ins-using-the-cross-domain-library.md
- docs/sp-add-ins/complete-basic-operations-using-javascript-library-code-in-sharepoint.md
- docs/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code.md
- docs/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints.md
- docs/sp-add-ins/determine-sharepoint-rest-service-endpoint-uris.md
- docs/sp-add-ins/develop-sharepoint-add-ins.md
- docs/sp-add-ins/explore-the-app-manifest-structure-and-the-package-of-a-sharepoint-add-in.md
- docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md
- docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md
- docs/sp-add-ins/navigate-the-sharepoint-data-structure-represented-in-the-rest-service.md
- docs/sp-add-ins/set-custom-permissions-on-a-list-by-using-the-rest-interface.md
- docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md
- docs/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery.md
- docs/sp-add-ins/url-strings-and-tokens-in-sharepoint-add-ins.md
- docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md
- docs/sp-add-ins/working-with-folders-and-files-with-rest.md
- docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md
Working in sp-add-ins > Develop topics; also fixed some broken dev.office.com links
> Final edit pass through sp-dev-docs

- docs/spfx/call-microsoft-graph-using-graphhttpclient.md
| Related issues?     | just fixes a typo, nothing related.
Changed the typo "the the" to "to the"
> Change "the the" to "to the"

- docs/general-development/modern-pages-maintenance-mode.md
- docs/toc.yml
Updated maintenance mode guidance to include classic pages
> Updated maintenance mode guidance to include classic pages

- docs/sp-add-ins/create-add-in-parts-to-install-with-your-sharepoint-add-in.md
- docs/sp-add-ins/create-custom-actions-to-deploy-with-sharepoint-add-ins.md
- docs/sp-add-ins/customize-a-list-view-in-sharepoint-add-ins-using-client-side-rendering.md
- docs/sp-add-ins/highlight-content-and-enhance-the-functionality-of-sharepoint-hosted-sharepoint.md
- docs/sp-add-ins/include-a-web-part-in-a-webpage-on-the-add-in-web.md
- docs/sp-add-ins/office-web-widgetsexperimental-license-terms.md
- docs/sp-add-ins/office-web-widgetsexperimental-overview.md
- docs/sp-add-ins/use-a-sharepoint-website-s-style-sheet-in-sharepoint-add-ins.md
- docs/sp-add-ins/use-the-client-chrome-control-in-sharepoint-add-ins.md
- docs/sp-add-ins/use-the-client-side-people-picker-control-in-sharepoint-hosted-sharepoint-add-in.md
- docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md
- docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md
Ongoing edit pass of Developer section of sp-add-ins
> Linda editor 12 20

- docs/sp-add-ins/register-sharepoint-add-ins.md
> clarify AppRegNew.aspx is site collection relative

- docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md
- docs/sp-add-ins/context-token-oauth-flow-for-sharepoint-add-ins.md
- docs/sp-add-ins/convert-an-autohosted-sharepoint-add-in-to-a-provider-hosted-add-in.md
- docs/sp-add-ins/create-a-sharepoint-add-in-that-contains-a-document-template-and-a-task-pane-add.md
- docs/sp-add-ins/create-provider-hosted-sharepoint-add-ins-to-access-sap-data-by-using-the-sap-ga.md
- docs/sp-add-ins/create-sharepoint-add-ins-that-can-be-used-by-anonymous-users.md
- docs/sp-add-ins/creating-sharepoint-add-ins-that-use-high-trust-authorization.md
- docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md
- docs/sp-add-ins/creating-sharepoint-add-ins-that-use-the-cross-domain-library.md
- docs/sp-add-ins/handle-security-tokens-in-provider-hosted-low-trust-sharepoint-add-ins.md
- docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md
- docs/sp-add-ins/three-authorization-systems-for-sharepoint-add-ins.md
- docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md
Ongoing edits for Develop sp-add-ins
> Final edit pass for Develop sp-add-ins

- docs/general-development/fast-query-language-fql-syntax-reference.md
we can't use the term olympics in our docs.
> fixing terms

- docs/general-development/create-a-workflow-with-elevated-permissions-by-using-the-sharepoint-workflo.md
- docs/toc.yml
Updated doc per customer request: https://docs.microsoft.com/en-us/sharepoint/dev/general-development/create-a-workflow-with-elevated-permissions-by-using-the-sharepoint-workflo
Updated TOC to shorten titles in sp-add-ins section
> TOC updates and one doc fix

- docs/declarative-customization/site-design-json-schema.md
Editing the command to setDescription
> Command - site description is case sensitive.

- docs/solution-guidance/Set-external-sharing-on-site-collections-in-Office-365.md
Since ** Set External Setting ** has been changed in Office 365, I modify the information according to my steps.
> Set External Setting has been changed currently

- docs/toc.yml
Edited all the titles in the sp-dev-docs TOC to make them more readable (shortened and lowercased as needed).
> Complete edit of sp-dev-docs TOC

- docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md
polishing
Removed a simple repetition
> Repetition removed

- docs/declarative-customization/site-design-pnp-provisioning.md
Fixes some content issues with the PnP Provisioning documentation
> Updates to PnP Site Design doc

- docs/spfx/web-parts/basics/configure-web-part-icon.md
- docs/spfx/web-parts/basics/integrate-with-property-pane.md
- docs/spfx/web-parts/basics/working-with-requestdigest.md
- docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md
- docs/spfx/web-parts/guidance/connect-to-sharepoint-using-jsom.md
- docs/spfx/web-parts/guidance/migrate-angular-1-x-applications-to-sharepoint-framework.md
- docs/spfx/web-parts/guidance/migrate-jquery-datatables-script-to-spfx.md
- docs/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx.md
- docs/spfx/web-parts/guidance/migrate-script-editor-web-part-customizations.md
- docs/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries.md
- docs/spfx/web-parts/guidance/validate-web-part-property-values.md
- docs/toc.yml
Edited Web Parts > Concepts > Migrate existing customizations (6 topics), and Web Parts > Basics (4)
> Edit pass of SPFx docs

- docs/spfx/web-parts/basics/integrate-with-property-pane.md
- docs/spfx/web-parts/guidance/build-custom-property-pane-controls.md
- docs/spfx/web-parts/guidance/integrate-web-part-properties-with-sharepoint.md
- docs/spfx/web-parts/guidance/migrate-angular-1-x-applications-to-sharepoint-framework.md
- docs/spfx/web-parts/guidance/share-data-between-web-parts.md
- docs/spfx/web-parts/guidance/tutorial-share-data-between-web-parts-global-variable.md
- docs/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties.md
- docs/toc.yml
Final edit for SPFx docs and some TOC updates
> Final edit for SPFx docs

- docs/spfx/extensions/get-started/build-a-hello-world-extension.md
- docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md
- docs/spfx/extensions/get-started/building-simple-field-customizer.md
- docs/spfx/extensions/get-started/hosting-extension-from-office365-cdn.md
- docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md
- docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md
- docs/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions.md
- docs/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions.md
- docs/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions.md
- docs/spfx/extensions/guidance/migrate-jslink-to-spfx-extensions.md
- docs/spfx/extensions/guidance/migrate-user-customactions-to-spfx-extensions.md
- docs/spfx/extensions/guidance/using-custom-dialogs-with-spfx.md
- docs/spfx/extensions/overview-extensions.md
- docs/spfx/web-parts/basics/integrate-with-property-pane.md
- docs/spfx/web-parts/guidance/build-custom-property-pane-controls.md
- docs/spfx/web-parts/guidance/integrate-web-part-properties-with-sharepoint.md
- docs/spfx/web-parts/guidance/migrate-angular-1-x-applications-to-sharepoint-framework.md
- docs/spfx/web-parts/guidance/share-data-between-web-parts.md
- docs/spfx/web-parts/guidance/tutorial-share-data-between-web-parts-global-variable.md
- docs/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties.md
- docs/toc.yml
Edit pass of SPFx Extensions section
> Edit pass of SPFx Extensions section

- docs/solution-guidance/Embedding-JavaScript-into-SharePoint.md
Updated link to a related article after domain change
> Updated old link to a related resource

- docs/spfx/office-ui-fabric-integration.md
Updated a small type in the content.
> Small typo fix

- docs/spfx/web-parts/overview-client-side-web-parts.md
Added the modern pages and removed the "Developer" tenants
Added the modern pages and removed the "Developer" tenants
> Added the modern pages and removed the "Developer" tenants

- docs/design/accessibility.md
- docs/design/authoring-pages.md
- docs/design/design-a-web-part.md
- docs/design/design-guidance-overview.md
- docs/design/grid-and-responsive-design.md
- docs/design/placeholders-and-fallbacks.md
- docs/design/reactive-and-nonreactive-web-parts.md
- docs/design/showcase-web-part.md
- docs/design/themes-colors.md
- docs/design/ui-text-for-web-parts.md
- docs/design/web-part-titles-and-descriptions.md
> Edit of Design topics 1-23-18

- docs/spfx/css-recommendations.md
- docs/spfx/extensions/guidance/using-custom-dialogs-with-spfx.md
- docs/spfx/office-ui-fabric-integration.md
- docs/spfx/use-theme-colors-in-your-customizations.md
- docs/spfx/web-parts/basics/design-considerations-for-web-parts.md
> Edit of SPFx Design topics

- docs/spfx/web-parts/basics/add-an-external-library.md
- docs/spfx/web-parts/guidance/build-client-side-web-parts-with-angular-1-x.md
- docs/spfx/web-parts/guidance/reference-third-party-css-styles.md
- docs/spfx/web-parts/guidance/use-existing-javascript-libraries.md
- docs/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts.md
Ongoing edit of SPFx docs - 5 topics under Concepts > External libraries
> Edit of external libraries section

- docs/apis/alm-api-for-spfx-add-ins.md
Removed small typos from code snippets (quotes and semicolons)
> Removed small typos from code snippets

- docs/spfx/toolchain/integrate-gulp-tasks-in-build-pipeline.md
Small change to the rig implementation to have comments consistency and TypeScript name update.
> Small change to the rig implementation

- docs/declarative-customization/site-design-pnp-provisioning.md
Powershell code has missing quotation marks around string value
> Added missing quote marks in Powershell code

- docs/toc.yml
Consolidated some entries to move them up a level and make them more visible to the user.
> TOC updates for SPFx section

- docs/toc.yml
Moved all items under SPFx Concepts up a level to make TOC easier to browse.
> SPFx TOC updates

- docs/apis/alm-api-for-spfx-add-ins.md
- docs/apis/communication-site-creation-rest.md
- docs/apis/webhooks/get-started-webhooks.md
- docs/apis/webhooks/lists/create-subscription.md
- docs/apis/webhooks/lists/delete-subscription.md
- docs/apis/webhooks/lists/get-subscription.md
- docs/apis/webhooks/lists/overview-sharepoint-list-webhooks.md
- docs/apis/webhooks/lists/update-subscription.md
- docs/apis/webhooks/overview-sharepoint-webhooks.md
- docs/apis/webhooks/sharepoint-webhooks-using-azure-functions.md
- docs/apis/webhooks/webhooks-reference-implementation.md
- docs/toc.yml
Ongoing edit of SharePoint docs - completed SharePoint API section, which includes redirects of REST topics to Add-ins location (yesterday)
> SharePoint APIs edit pass

- docs/spfx/use-aad-tutorial.md
I added the link to the source code in the PnP sp-dev-fx-webparts repo.
> Added link to source code of tutorial sample Web Part

- docs/spfx/use-aad-tutorial.md
Fixed tutorial to show the commands without the 'sh' at the start.
Before:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#CreatingInitialSolution
After:
> Fixed command: Update use-aad-tutorial.md

- docs/sp-add-ins/synchronize-sharepoint-items-using-the-rest-service.md
> You missed root element for Query param

- docs/spfx/extensions/guidance/using-custom-dialogs-with-spfx.md
- docs/spfx/office-ui-fabric-integration.md
updated package references for consistency so:
- first reference is linked to the NPM package page on https://www.npmjs.org
- all references are bold & have the correct `@microsoft/` scope prefix where appropriate
> Update NPMJS package references

- docs/solution-guidance/modern-experience-customizations-provisioning-sites.md
Title and variable are copied from teams example and are incorrect for the communication site.
Content fix
Correction to title and variable in communication site example.
> Errors in communication site powershell example

- docs/spfx/office-ui-fabric-integration.md
Updated the scoped UI Fabric class from `ms-Fabric-core--v6` to `ms-Fabric--v6-0-0`.
Updated the UI Fabric scoped class name.
> Updated the scoped UI Fabric class

- docs/spfx/tenant-properties.md
Adds details on how the Office 365 CLI can be used to get, list, set and remove tenant properties to the SharePoint Online tenant properties document
> Adds details on how the Office 365 CLI  can be used to manage tenant properties

- docs/spfx/use-aad-tutorial.md
- docs/toc.yml
> Edit pass on Consuming APIs secured with Azure AD article.

- docs/general-development/query-refinement-in-sharepoint.md
There was a typo in the code.
FROM
var firstRefinementOption = refinementOptionArray[6];x
TO
var firstRefinementOption = refinementOptionArray[6];
> Typo in code.

- docs/toc.yml
Also changed sort order at the end of the TOC to be alphabetic and thus more readable
Updated the main TOC to include a reference to the PnP Office 365 CLI project alongside the other two PnP projects (Sites Core & POSH). 
Also tweaked sort order of these items to be alpha and thus more readable
> Update TOC to include reference to PnP Office 365 CLI

- docs/spfx/use-theme-colors-in-your-customizations.md
- removed two that aren't available at the present time
- updated  theme to correct name
All verified checking against SPO theme properties within the
> Update theme tokens available in SPFx solutions

- docs/solution-guidance/Branding.md
> Branding guidance

- docs/apis/alm-api-for-spfx-add-ins.md
Minor edits to recent updates to ensure consistency across the SharePoint documentation set and to abide by Microsoft Writing Style Guide standards. Updates included edits to grammar, punctuation, and capitalization.
> Minor edits to ALM topic

- docs/declarative-customization/site-design-pnp-provisioning.md
Also added link to download SharePoint Online Management Shell.
Improved readability
> Minor improvement for readability

- docs/general-development/creating-a-workflow-by-using-sharepoint-designer-and-the-sharepoint-wo.md
Added link for workflow manager configuration
> Updated link for workflow manager configuration

- docs/general-development/office-365-cdn.md
- Related issues: None
Minor grammatical fixes
> Minor grammatical fixes

- docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md
> Fixed broken link

- README.md
Added link to SPFx v1.4.1 release notes
> Update README.md added v1.4.1 release notes link

- docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md
Added documentation for the AddValidateUpdateItemUsingPath operation
> Added documentation for the AddValidateUpdateItemUsingPath operation

- docs/spfx/use-aad-tutorial.md
- docs/spfx/use-aadhttpclient.md
- docs/spfx/use-msgraph.md
Edited the following:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial
> Edits of some SPFx docs

- docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md
Added information about the RenderListDataAsStream endpoint
> Added information about the RenderListDataAsStream endpoint

- docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
added details around what to do if you're buidling front end components.
https://github.com/SharePoint/PnP-JS-Core/issues/641
- Related issues: https://github.com/SharePoint/PnP-JS-Core/issues/641
Provided additional guidance for throttling tagging for people building front end components as it is impossible to change the user agent string in most browsers.
> throttling: provided guidance for front end components

- docs/features/hub-site/create-hub-site-with-powershell.md
Corrected download links and updated powershell snippet
Clearified use of SPO PowerShell and PnP PowerShell. Updated download links (PnP was incorrectly linked to SPO PS Download). Updated PS snippet to do additional (required) Connect-PnPOnline for the New-PnPSite cmdlet to work.
> Clarified use of SPO Management Shell and PnP PowerShell.

- docs/features/hub-site/create-hub-site-with-powershell.md
- Related issues: fixes #1515 
Updated PS examples to always use named parameters in documentation. Fixed incorrect example to associate a site with a hubsite.
> fixed example, correct powershell statements

- docs/solution-guidance/Transformation.md
> Transformation guidance

- docs/solution-guidance/Custom-configurations.md
Added custom configuration guidance
> Added custom configuration guidance

- docs/solution-guidance/Security.md
Added scenario-based guidance around security
> Added security guidance

- docs/solution-guidance/Performance.md
> Added Performance guidance

- docs/solution-guidance/Enterprise-Content-Management.md
> Scenario guidance ECM

- docs/solution-guidance/Long-running-scheduled-operations.md
Long-running and scheduled operations solution guidance
> Long-running and scheduled operations solution guidance

- docs/solution-guidance/Site-provisioning.md
- docs/solution-guidance/implement-a-sharepoint-site-classification-solution.md
Article about Site Provisioning.
> Scenario guidance

- docs/solution-guidance/User-information.md
Scenario guidance around user information
> User information guidance

- docs/solution-guidance/Development-models.md
> Scenario guidance development models

- docs/solution-guidance/Line-of-Business-integration.md
Article about LOB integration.
> Scenario guidance LOB integration

- docs/solution-guidance/Multi-geo-capabilities.md
Article about Multi-Geo capabilities in Office 365.
> Article about Multi-Geo capabilities

- docs/solution-guidance/Responding-to-changes.md
Article about "Responding to changes"
> Scenario guidance responding to changes

- docs/solution-guidance/Business-processes.md
Article about Business Processes
> Scenario guidance business processes

- docs/solution-guidance/Application-lifecycle-management.md
> Article about ALM

- docs/solution-guidance/Solutions-deployment.md
Article about Solutions Deployemnt
> Article about Solutions Deployment

- docs/spfx/web-parts/guidance/connect-to-sharepoint-using-jsom.md
Updated the PnP JS Core hyperlink to the new repository.
> Updated the PnP JS Core link

- docs/features/hub-site/hub-site-overview.md
Added a note to state that the hub site navigation is based upon the top navigation of the hub site.
> Added note about programmatically changing hubsite navigation

- docs/features/hub-site/REST-cancreate-method.md
- Related issues: None
Added the missing headers for the Definitions table
> Fixed broken table

- docs/spfx/web-parts/guidance/build-client-side-web-parts-with-angular-1-x.md
- Related issues: fixes #1565
Fixed incorrect string name (`BasicGroupName` to `ViewGroupName`).
> Fixed incorrect string name

- docs/spfx/extensions/get-started/building-simple-field-customizer.md
- Related issues: fixes #1612 
Removed quotes from stylesheet
> Removed quotes from stylesheet

- docs/features/hub-site/REST-synchubsitetheme-method.md
- Related issues: fixes #1594
Fixed GET to POST in Sample Request
> Fixed GET to POST in Sample Request

- docs/declarative-customization/column-formatting.md
- Related issues: fixes #1593
Added details around referencing hyperlink fields in Column Formatting
> Added details around referencing hyperlink fields

- docs/declarative-customization/site-design-json-schema.md
suggestion of remove a confusing use of the term "Subactions"
> confusing use of term Subactions for addSPView

- docs/apis/alm-api-for-spfx-add-ins.md
- docs/apis/communication-site-creation-rest.md
- docs/declarative-customization/column-formatting.md
- docs/declarative-customization/site-theming/sharepoint-site-theming-csom.md
- docs/declarative-customization/site-theming/sharepoint-site-theming-json-schema.md
- docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md
- docs/declarative-customization/site-theming/sharepoint-site-theming-rest-api.md
- docs/features/groupify/groupify-csom.md
- docs/features/groupify/groupify-overview.md
- docs/sp-add-ins/complete-basic-operations-using-javascript-library-code-in-sharepoint.md
- docs/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code.md
- docs/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints.md
- docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md
- docs/sp-add-ins/set-custom-permissions-on-a-list-by-using-the-rest-interface.md
- docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md
- docs/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery.md
- docs/sp-add-ins/working-with-folders-and-files-with-rest.md
- docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md
- docs/spfx/shorter-share-link-format.md
- docs/toc.yml
> Updates to Features section

- docs/solution-guidance/multigeo-search.md
> Updated with new information

- docs/features/groupify/groupify-csom.md
- docs/features/groupify/groupify-overview.md
- docs/solution-guidance/modern-experience-customizations-provisioning-sites.md
- docs/solution-guidance/modern-experience-site-classification.md
- docs/toc.yml
- docs/transform/modernize-classic-sites.md
- docs/transform/modernize-connect-to-office365-group.md
- docs/transform/modernize-userinterface-lists-and-libraries.md
- docs/transform/modernize-userinterface.md
Ensured that all references across sp-dev-docs matched Vesa's updates to "groupify" and "Office 365 Group"
Used:
group-connect to replace "groupify"
group-connected to replace "groupified"
group-connection to replace "groupifying"
Office 365 group to replace "Office 365 Group"
Updated TOC
> Edit of Vesa's updates

- docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md
Update to make sure every feature needs to get a unique ID so that developer not only copies and paste the code blindly. Might an overkill to mention for senior SP developer but definitely worth to mention if you just started developing SharePoint and/or SPFx
> For every feature a new GUID should be defined

- docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md
> Removed Typo

- docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md
- Related issues: mentioned in #1654 
Fixed issue with incorrect &amp; tokens.
> Fixed issue with incorrect &amp; tokens

- docs/general-development/how-to-convert-an-html-file-into-a-master-page-in-sharepoint.md
- Related issues: fixes #1738 
Added missing space
> Added missing space

- docs/spfx/use-aadhttpclient-enterpriseapi.md
- docs/spfx/web-parts/guidance/connect-to-api-secured-with-aad.md
- docs/toc.yml
Added notes regarding CORS configuration for APIs hosted on Azure
> Added notes regarding CORS configuration for APIs hosted on Azure

- docs/solution-guidance/modern-experience-customizations-customize-sites.md
Tenant Themes where added after so to keep the guidance inline with current practices I propose a note in the theming section of this article.
Cross link note information regarding modern site theming
This is aimed at being published on office docs
> Added cross link to SharePoint Site Theming

- docs/general-development/sharepoint-workflow-samples.md
- Related issues: fixes #1787 
Fixed broken sample links
> Fixed broken sample links

- docs/general-development/what-s-new-in-workflows-for-sharepoint.md
This article describes changes that were made for SharePoint Server 2013.
This article  describing changes that were made for SharePoint Server 2013 was edited to make it more clear what product it applies to.
> Change from What's new in SharePoint to What's new in SharePoint 2013

- docs/general-development/managed-navigation-in-sharepoint.md
The code output was not indented and was hard to read. I used Visual Studio to make it readable.
> Prettify code.

- docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
- [z] Content fix
- updated link to "capacity planning & load testing SPO" to `support.office.com`
Closes #1811
> updated link to referenced doc closing #1811

- docs/general-development/site-collection-app-catalog.md
- Related issues: #1567 
Removed 'ALM API limitation', as they're now implemented and available for site collection app catalog.
Updated date
> Removed ALM API limitation

- docs/spfx/overview-graphhttpclient.md
> Make it clearer that the page is deprecated.

- docs/spfx/web-parts/basics/hide-web-part-from-toolbox.md
- docs/toc.yml
Added documentation on how to hide a web part from the toolbox when editing a modern page.
> Added docs on how to hide a web part from the modern toolbox

- docs/declarative-customization/site-design-json-schema.md
> Wrong description for ListViewCommandSet

- docs/declarative-customization/site-design-json-schema.md
> 
> fixed a supposed typo in "ClientSide" => was "ClientSite"
> Typo in clientside

- docs/general-development/modify-sharepoint-components-for-mds.md
- Related issues: fixes #1908 
Corrected namespace typo in attribute example
> Fixed namespace typo

- docs/community/repositories.md
- docs/scenario-guidance/Branding.md
- docs/scenario-guidance/Long-running-scheduled-operations.md
- docs/scenario-guidance/Security.md
- docs/scenario-guidance/Transformation.md
- docs/scenario-guidance/User-information.md
- docs/solution-guidance/Document-library-templates-sample-app-for-SharePoint.md
- docs/solution-guidance/remote-timer-jobs-sharepoint-add-in.md
- docs/solution-guidance/replace-sharepoint-web-parts-with-add-in-parts.md
- docs/solution-guidance/search-api-usage-sharepoint-add-in.md
- docs/solution-guidance/site-provisioning-sharepoint-add-in.md
- docs/solution-guidance/yammer-integration-sharepoint-add-in.md
- docs/sp-add-ins/publish-sharepoint-add-ins-by-using-visual-studio.md
- docs/sp-add-ins/sharepoint-add-ins-ux-design-guidelines.md
- Related issues: fixes #1973 #1974 #1975 #1976 #1977 #1978 #1979 #1980 #1981 #1982 #1983 #1984 #1985 #1986 #1987 #1988 
Multiple broken link fixes in docs
> Fixed multiple broken links within SP docs

- docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
- Related issues: fixes #1990 
tweak docs to address doc feedback from comment #1990
> tweak docs to address doc feedback from comment

- docs/spfx/set-up-your-development-environment.md
Updating NodeJS LTS version in "how to setup your spfx environment"
> Updated current NodeJS LTS version

- docs/features/hub-site/hub-site-overview.md
Removed "Important" note that Hub Sites are still in preview. Hub sites are 100% in prod as per the Microsoft Internal yammer post:
https://www.yammer.com/microsoft.com/#/threads/show?threadId=1045173825
> 
> 
> *Please update this PR information accordingly. We'll use this as part of our release …
> Remove Preview Note

- docs/declarative-customization/column-formatting.md
Added details about the `@window.innerHeight` and `@window.innerWidth` special strings
> Added @window special strings

- docs/solution-guidance/localization-sharepoint-add-in.md
- Related issues: fixes #2074
Fixed broken links as mentioned in issue #2074
> Fixed broken links

- docs/apis/migration-api-overview.md
[X ] Content fix
Added section for changes in the "Ship Disk" option and MD5.
Formatting, grammar, typo edits.
> Update the migration-api-overview.md

- docs/spfx/tools-and-libraries.md
Added a link to one popular front-end library.
> Added link to vue.js

- docs/spfx/extensions/get-started/build-a-hello-world-extension.md
- Related issues: mentioned in #2124 
Added note for debugging with serve configurations as suggested in #2124
> Added note for debugging with serve configurations

- docs/sp-add-ins/handle-security-tokens-in-provider-hosted-low-trust-sharepoint-add-ins.md
- Related issues: fixes #2058 
Fixed the JWT Specification link (previously pointing to a draft document that no longer exists, now points to the official specification).
> Fixed JWT Specification Link

- docs/solution-guidance/security-apponly-azuread.md
> Keycredentials are not printed out

- docs/general-development/using-the-sharepoint-search-query-apis.md
> Fix DLL and namespace in .NET CSOM example

- docs/solution-guidance/multigeo-introduction.md
Minor changes to take out the word Preview and SharePoint since we are GA for ODB and have not entered Preview yet for SPO
> 
> 
> 
> *Please target your PR to 'master' branch. …
> Taking off Preview from and SharePoint since we are GA for ODB

- docs/toc.yml
Icon creation only makes sense after you create a Command Set - let's move this tutorial down.
> Let's move the Icon creation to after the Command Set

- docs/declarative-customization/site-theming/sharepoint-site-theming-csom.md
- docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md
The documentation as it currently exists gives developers the impression that there is no programmatic way to apply a custom theme to a site collection when in fact it can very easily be done through a site script/site design.  I've added 2 points of clarification to direct them to the appropriate information.
> Helping developers find appropriate information about how to apply a custom theme to site collections programmatically.

- docs/declarative-customization/column-formatting.md
- Related issues: fixes #2402 
- Added Currency to unsupported column types
- Added note about icons not being included in sp-field-severity classes
- Added note about using other UI Fabric classes
- Added link to PnP Column Formatter
- Updated all schema references
> Added Additional Details

- docs/declarative-customization/site-design-trigger-flow-tutorial.md
Removed line about footer, since there is no footer present in this tutorial.
- Related issues: none
> Removed line about footer

- docs/spfx/enterprise-guidance.md
Extended enterprise guidance with information on support and SLA
> Extended enterprise guidance with information on support and SLA

- docs/spfx/connect-to-anonymous-apis.md
- docs/toc.yml
New guidance on connecting to anonymous APIs in SharePoint Framework
> Added guidance on connecting to anonymous APIs

- docs/spfx/extensions/get-started/hosting-extension-from-office365-cdn.md
> Fix bold display

- docs/spfx/sharepoint-framework-overview.md
Remove incorrect formatting of header table containing document metadata.
- Related issues:
Fixes rendering of header table as it is broken with an extra hidden character at the moment.
> Fix formatting of header table with metadata

- docs/sp-add-ins/update-add-in-web-components-in-sharepoint.md
Fix code formatting for HTML and XML content described.
No guidance needed.
> Fix code block formatting

- docs/general-development/step-3-accessing-the-web-service.md
There is a bug on the MD syntax, that made it headlines of C# and VB not display correctly (instaed of headline they show the words "cs" and "VB.net" with grave accents).
> fix MD bugs

- docs/declarative-customization/site-design-overview.md
today site designs are only supported with SharePoint online and not SharePoint 2019, added the information
today site designs are only supported with SharePoint online and not SharePoint 2019, added the information
> added information regarding site design support

- docs/spfx/web-parts/guidance/connect-to-api-secured-with-aad.md
> Add explicit message on using webApiPermissionRequests when accessing enterprise API with AadTokenProvider

- docs/spfx/use-aadhttpclient.md
Fixes  https://github.com/SharePoint/sp-dev-docs/issues/2511
- Related issues: fixes #2511 , partially #Y, mentioned in #Z
> Fix the invalid link
> Fix link 404

- docs/declarative-customization/site-theming/sharepoint-site-theming-rest-api.md
Updated the `RemoveTenantTheme` API endpoint to `DeleteTenantTheme`. The `RemoveTenantTheme` doesn't exist, so the `DeleteTenantTheme` is the correct one to call.
> Updated API endpoint

- docs/spfx/set-up-your-development-environment.md
Updated version of Node.JS LTS to 8.12.0
> Update latest LTS version of node to 8.12.0

- docs/general-development/build-sites-for-sharepoint.md
Add missing space between two words
Add missing space between two words.
> add missing space

- docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
Several fixes and updates ahead of MSIgnite 2018.
> 
> 
> 
> 
> _(DELETE THIS PARAGRAPH …
> Update of information on throttling

- docs/solution-guidance/multigeo-introduction.md
https://github.com/SharePoint/sp-dev-docs/issues/2531
- Related issues: fixes #2531
> Modify the document title
> GitHub Doc Issue

- docs/general-development/reference-threads-and-digest-threads-in-sharepoint-server-social-feeds.md
Change the link of `IsDigest` to `https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.social.socialthreadattributes.aspx`
- Related issues: fixes #2706 
Change the link of `IsDigest` to `https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.social.socialthreadattributes.aspx`
> Modify the link

- docs/general-development/how-to-learn-to-read-and-write-to-the-social-feed-by-using-the-net-client-object.md
Modify the Link URL as blow:
Change the link of SharePoint Client Components  to `http://www.microsoft.com/en-us/download/details.aspx?id=35585`;
Change the link of Value  to `https://msdn.microsoft.com/EN-US/library/ee543385.aspx`;
Change the link of CanReply to `https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.social.socialthreadattributes.aspx`;
- Related issues: fixes #2700 
Modify the Link URL as blow:
Change the link of SharePoint Client Components  to `http://www.microsoft.com/en-us/download/details.aspx?id=35585`;
Change the link of Value  to `https://msdn.microsoft.com/EN-US/library/ee543385.aspx`;
Change the link of CanReply to `https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.social.socialthreadattributes.aspx`;
> Modify the Link URL

- docs/toc.yml
> Added design topics to TOC.

- docs/general-development/how-to-create-a-page-layout-in-sharepoint.md
- Related issues: fixes #2599
Fixed escaping issue which was causing `<div>` to not show up in the text.
> Fixed code escape issue

- docs/spfx/tenant-properties.md
- Related issues: fixes #2678
Fixed broken links
> Updated links from SharePoint org to PnP

- docs/general-development/how-to-deploy-a-custom-theme-in-sharepoint.md
Nothing major..just adding a 'for' on the "NOTE" section near the top. VERY minor thing, but @VesaJuvonen asked the community to submit any doc updates we saw while reading....'SharingIsCaring' :)
> Simple grammar update for the "Note:" section

- docs/spfx/use-aadhttpclient.md
Updated information about the resource in requesting API permissions
> Updated information about the resource in requesting API permissions

- docs/general-development/claims-based-identity-in-sharepoint.md
> Extremely minor grammar issue

- docs/apis/webhooks/overview-sharepoint-webhooks.md
`validationtoken` should be with a lower case `t` and not `validationToken`
> Correct validationtoken value

- docs/apis/webhooks/lists/create-subscription.md
`clientState` should be `clientState` and not `client-clientState`
> Updated clientState

- docs/spfx/sharepoint-framework-overview.md
Updated the text so it states that SPFx is also available for SharePoint 2016 Feature Pack 2 and SharePoint 2019 on-premises
> SPFx available for 2016 FP2 and 2019

- docs/spfx/connect-to-anonymous-apis.md
Changed the API used in examples to one that works
- Related issues: fixes #2807 
Updated guidance on connecting to anonymous APIs in SPFx
> Updated guidance on connecting to anonymous APIs

- docs/solution-guidance/provisioning-console-application-sample.md
The link on SharePointPnPCore showed only an empty result page.
Link update to Nuget
> Update link on SharePointPNPCore Libraries

- docs/schema/apppartconfigdefinition-schema-reference.md
change the link of `Create add-in parts to install with your SharePoint Add-in` to `../sp-add-ins/create-add-in-parts-to-install-with-your-sharepoint-add-in.md`
- Related issues: fixes #2735 
change the link of `Create add-in parts to install with your SharePoint Add-in` to `../sp-add-ins/create-add-in-parts-to-install-with-your-sharepoint-add-in.md`
> Change the link

- docs/general-development/query-refinement-in-sharepoint.md
Modify the link of `KeywordQuery`
- Related issues: fixes #2730 
Modify the link of `KeywordQuery` to `https://msdn.microsoft.com/library/Microsoft.Office.Server.Search.Query.KeywordQuery.aspx`
> Modify the link of `KeywordQuery`

- docs/toc.yml
- Related issues: fixes #2917
Modification to the title of the document on dynamic data making it more discoverable in the docs TOC
> update TOC making dynamic data article more discoverable

- docs/general-development/claims-based-identity-term-definitions.md
- Related issues: fixes #2845 
1.  Fixing link in text "_Web Services Federation Language (WS-Federation) Version 1.2_" .
1.  Fixing link in text "_Web Services Federation Language (WS-Federation) Version 1.2_" .
> Fixing incorrect link WS-Federation

- docs/general-development/advanced-scenarios-and-additional-samples.md
- Related issues: fixes #2823
1. modify the invalid link of `Excel Services REST API Examples` to  `https://www.microsoft.com/en-us/microsoft-365/blog/2009/11/09/excel-services-in-sharepoint-2010-rest-api-examples/`
2. modify the invalid link of `Excel Services REST API Examples` to  `https://www.microsoft.com/en-us/microsoft-365/blog/2009/11/04/simple-access-to-spreadsheet-data-using-the-excel-services-2010-rest-api/`
3. modify the invalid link of `Excel Services REST API Syntax` to  `https://www.microsoft.com/en-us/microsoft-365/blog/2009/11/05/excel-services-in-sharepoint-2010-rest-api-syntax/`
> Modify the invalid link

- docs/general-development/bcs-rest-api-reference-for-sharepoint.md
- Add new ref link to example
- Related issues: fixes #2846 
1. Update to invalid link (SharePoint: Perform basic data access operations by using REST in apps)
2. Update title in the link to "SharePoint **2013**: Perform basic data access operations by using REST in apps"
3. Add new reference (Basic CRUD operations in SharePoint Add-ins using the REST/OData APIs)
1. **See Notes** links has been added with new reference to **Basic CRUD operations in SharePoint Add-ins using the REST/OData APIs**
> - Update link title in  **See also**

- docs/spfx/web-parts/basics/notes-on-solution-packaging.md
- Related issues: no
Versioning system explanation
> Versioning system explanation

- docs/spfx/tenant-scoped-deployment.md
> Added mention of Office 365 CLI as upgrade option from SPFx  solutions older than 1.4
> Adding Office 365 CLI reference for SPFx upgrade

- docs/solution-guidance/javascript-patterns-and-performance.md
> Fixed header link.

- docs/spfx/office-ui-fabric-integration.md
- Related issues: fixes #2936
updated doc to be more in line with proper docs as explained in other docs: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/use-fabric-react-components\#add-an-office-ui-fabric-component
> fix incorrect fabric react guidance

- docs/spfx/integrate-with-teams-introduction.md
> Changes based on issue #2949

- docs/declarative-customization/column-formatting.md
- Related issues: fixes #2968, #2961
- Adjusted the conditional formatting example to match the more complete sample (as referenced in #2968). Now the screenshot matches the sample code.
- Removed `debugMode` from sample code
- Fixed missing closing parenthesis from excel style expressions
- Added additional whitelisted style properties
> Formatting Updates

- docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
adding 503 error code
giving sample app types for following scanguidance
> 
> 
> 
> 
> …
> updating throttling guidance

- README.md
Added link to SPFx 1.7 release notes to the README.md page.
> Added SPFx 1.7 Release Notes

- docs/declarative-customization/site-design-overview.md
- Related issues: Fixes typo mentioned in Note section mentioned in this site-design-overview.md
> Description:
> Fixes typographical error in the Note section specifically: ...For **more** information...
> Typo in Note section - Fixed

- docs/general-development/set-up-and-configure-sharepoint-workflow-manager.md
Changed the phrasing in the title from SharePoint Workflow Manager to Workflow Manager with SharePoint to avoid confusion. There is no released product named SharePoint Workflow Manager.
> 
> 
> *Please update this PR information accordingly. We'll use this as part of our release notes in monthly …
> Title change per feedback

- docs/features/hub-site/hub-site-overview.md
Modified the statement to include support for Hubs Multi-Geo.
> 
> 
> 
> 
> _(DELETE THIS …
> Hubs Multi-Geo Support

- docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md
exerice ->exercise
Typo fix "exerice" -> "exercise"
> Typo in hosting-webpart-from-office-365-cdn.md

- docs/community/community.md
Update to the community call community demo submission instructions & guidance.
> Update community call submission guidance

- docs/spfx/web-parts/get-started/connect-to-sharepoint.md
Clarify the text around using this.context.pageContext
> 
> 
> 
> 
> _(DELETE THIS …
> Update connect-to-sharepoint.md (pageContext section)

- docs/community/community.md
> Fix grammatical error in community.md

- docs/training/training.md
- added links to new training modules
> Update SPFx training page

- docs/spfx/web-parts/basics/use-web-parts-full-width-column.md
- Related issues: fixes #3119
Content fixup to add additional information where web part manifest file is located... addresses comment in #3119
> Content fixup to clarify where web part manifest file is located

- docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md
- Related issues: fixes #3099
Fixup code formatting to address garbled rendering.
> Content fixup for garbled rendering (fixes 3099)

- docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md
> Correct the package content folder path.

- docs/declarative-customization/column-formatting.md
Added details about the new `@currentWeb` magic string.
> Added @currentWeb

- docs/general-development/build-mobile-apps-for-other-platforms-using-sharepoint.md
- Related issues: fixes #2702 
> Remove incorrect link in the _See also_ section. Other references already provide wide range of examples.
> Remove incorrect link in the _See also_ section.
> Removing incorrect link

- docs/spfx/debug-in-vscode.md
- Related issues: fixes #2248
> Fixing video link to Pnp - Debugging SharePoint Framework solutions in Visual Studio Code
> Fixing video link to Pnp - Debugging SharePoint Framework solutions in Visual Studio Code
> Fixing video link  Debugging SharePoint Framework solutions in Visual Studio Code

- docs/solution-guidance/modern-experience-customizations-customize-pages.md
Updated HTTP to HTTPS in image URL, that caused security warning in browser.
Updated HTTP to HTTPS in image URL for solving security warning in browsers about mixing http and https contents.
Updated HTTP to HTTPS in image URL, that caused security warning in browser.
> Updated HTTP to HTTPS in image URL

- docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md
- Related issues: fixes #3233 
> Remove obsolete links reference. _(Reason: Author confirms that links or content no longer available. New reference not available)_
> Remove obsolete links reference. _(Reason: Author confirms that links or content no longer available. New reference not available)_
> Scott Hillier - confirms links no longer exists. No new reference

- docs/scenario-guidance/Long-running-scheduled-operations.md
- Related issues: fixes #3291 
> Remove obsolete links reference. _(Reason: No longer available. New reference not available)_
> Remove obsolete links reference. _(Reason: No longer available. New reference not available)_
> Links is no longer available. No new reference available

- docs/spfx/web-parts/get-started/connect-to-sharepoint.md
Fix of #3296
- Related issues: #3296 
Fix of #3296
> Update based on issue #3296

- docs/general-development/common-error-messages-in-sharepoint-workflow-development.md
- docs/general-development/create-associations-in-sharepoint.md
- docs/general-development/excel-services-blogs-forums-and-resources.md
- docs/general-development/how-to-create-custom-sharepoint-server-workflow-forms-with-visual-studio-20.md
- docs/general-development/how-to-learn-to-read-and-write-to-the-social-feed-by-using-the-net-client-object.md
- docs/general-development/how-to-trust-a-location.md
- docs/general-development/javascript-user-defined-functions-overview.md
- docs/general-development/requesting-excel-workbook-data-from-sharepoint-server-using-odata.md
- docs/general-development/sharepoint-search-rest-api-overview.md
- docs/general-development/using-odata-with-excel-services-rest-in-sharepoint.md
- docs/general-development/what-s-new-for-developers-in-social-and-collaboration-features-in-sharepoint-201.md
- docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md
- docs/solution-guidance/feature-stapling-sharepoint-add-in.md
- docs/sp-add-ins/add-in-permissions-in-sharepoint.md
- Related issues:
- fixes #1034
- fixes #1474
- fixes #2075
- fixes #2209
- fixes #2210
- fixes #2539
- fixes #3268
- fixes #3294
- fixes #3294
> Multiple doc fixes

- docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md
Pulled the contents of this into Word and ran a spelling and grammar check.
> Spelling and grammar check

- docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md
Fixed typo `publis h` to `publish`
> Update implement-ci-cd-with-azure-devops.md typo

- docs/schema/declarativecontextdefinitiongroup-element-solutionmanifestdeclarativeextensions.md
> Fixing broken link from issue 3378

- docs/declarative-customization/column-formatting.md
Added new operators and expanded operator section with explanations and examples
- Related issues: None
- Added undocumented operators
- Added detailed descriptions and examples to operators
> Operator Additions

- docs/general-development/create-sharepoint-no-code-solutions.md
- docs/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code.md
- docs/sp-add-ins/get-started-creating-sharepoint-hosted-sharepoint-add-ins.md
- docs/sp-add-ins/sharepoint-add-ins.md
- docs/spfx/use-msgraph.md
Related issues:
- fixes #1536
- fixes #1552
- fixes #2068
- fixes #3315
- fixes #3400
Multiple fixes to documentation covering typos, code errors, exceptions, broken links & clarification to steps/descriptions that were ambiguous:
> Multiple updates to docs fixing typos, broken links & clarifications

- docs/design/layout-patterns.md
- Related issues:
- fixes #3455
- title typo
- few typos in doc
> Fix doc typos (issue 3455)

- docs/declarative-customization/column-formatting.md
- Related issues: None
- Fixed tab/spacing issues within code samples
- Added note about where expression syntax styles can be used
- Added excel-style versions of AST samples
- Fixed incorrect `style` sample
- Added note to operations not available in SP2019
> Formatting and sample adjustments

- docs/spfx/web-parts/basics/add-an-external-library.md
- Related issues: 
Updated the npm install examples to save-dev for types declarations installations
> updated install commands to save-dev on @types/* installations

- docs/solution-guidance/security-apponly-azureacs.md
Included usings that were outside the scope of the code snippet
Fixed incorrect code snippet where the `usings` were outside of the code snippet and added XML language identifier to another code snippet
> Fixed code example

- docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md
Related to https://github.com/SharePoint/sp-dev-build-extensions/pull/32
- Related issues: related https://github.com/SharePoint/sp-dev-build-extensions/pull/32
Removed dependency to lodash in the documentation provided. Updates made to reflect the updates in the sample.
> Updated documentation to remove a dependency to lodash

- docs/declarative-customization/view-formatting.md
For issue #3511
- Related issues: fixes #3511 
Fixing spelling mistake
> Fixing Spelling mistakes in documentation

- docs/spfx/web-parts/basics/configure-web-part-icon.md
Remove the "-" on text say first- in the documentation
> Grammar correction for configure-web-part-icon.md

- docs/declarative-customization/column-formatting.md
> Added docs with Thumbnails, LoopIndex and Multivalue field operations in Custome Formatter

- docs/spfx/use-aad-tutorial.md
Only show the search button if the clientMode property of the GraphConsumer component has been set.
- Related issues: fixes #3398 
Sorry for the previously wrong pull request and noise.
> Conditionally render search button

- docs/spfx/web-parts/basics/use-web-parts-full-width-column.md
Remove the "s" on the line say thousands.
> Correct grammar use-web-parts-full-width-column.md

- docs/solution-guidance/security-apponly-azuread.md
Added PowerShell snippet to be used in Azure Automation runbooks for the App-only model to communicate with SPO
> Added PowerShell snippet

- docs/spfx/library-component-overview.md
> spelling update

- docs/spfx/integrate-with-teams-introduction.md
> Fix of #3650 from sp-dev-docs

- docs/spfx/library-component-overview.md
A couple of very simple spelling updates. :)
Couple of simple spelling updates....nothing major. :)
> Spelling updates for library-component-overview.md

- docs/transform/modernize-userinterface-site-pages-webparts.md
> Fix of #3649

- docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md
- Related issues: fixes #3714 
Just updated the code sample to reference "helloworld" instead of "helloword".
Thanks to @RiccardoAmadi for bringing to attention. :)
Fixes issue #3714 .
> Spelling corrections for Hello World part 3

- docs/spfx/integrate-with-teams-introduction.md
- docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md
- docs/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart.md
- previously docs addressed the "sync to teams" functionality which is not operational
- updated docs to be more descriptive on creating the Teams app manifest file
- updated docs to be more descriptive on creating the Teams app package
- updated docs to focus on the side-loading approach
- updated docs to mention "Sync to Teams", but be explicit that this is (1) not operational & (2) not recommended at this time
> update spfx+teams docs

- docs/spfx/integrate-with-teams-introduction.md
Related issues: 
- closes #3650
- previous PR #3657 caught one link... there were two
- this fixes the other link
> Fix broken link 3650

- docs/general-development/sorting-search-results-in-sharepoint.md
Related issues: 
- closes #3513
fix broken link to ManagedDateTime enum
> fix broken link 3513

- docs/spfx/web-parts/get-started/use-fabric-react-components.md
On the page https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/use-fabric-react-components
Spelled "of" instead of "fo"
No major update. Only a small spelling correction.
> Small spelling correction

- docs/solution-guidance/modern-experience-customizations-customize-sites.md
- Related issues: fixes #1057
Added a note about not being able to programmatically update navigation elements.
> Updated to address issue #1057

- docs/docfx.json
> Updated global metadata to "ms.suite": "office",

- docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md
> Typo fix exerice -> exercise

- docs/design/design-a-web-part.md
Simple spelling correction to adjust "Accordian" mis-spelling to "Accordion" in one of the subtitles. :)
> Spelling correction from Accordian to Accordion

- docs/general-development/sharepoint-2019-development-platform.md
Broken link and markdown fix in see also section.
> Fixes broken link in see also

- docs/design/designing-a-web-part-icon.md
Misspelled word "veritical" corrected to "vertical"
> Updated spelling to "vertical"

- docs/design/grid-and-responsive-design.md
Updated misspelled word "communcation" to "communication"
> Spelling correction word "communication"

- docs/spfx/web-parts/get-started/use-fabric-react-components.md
The npm sample above mentions 5.132.0, the note section mentions we're installing 5.143.0. The latter is not a valid published version of this package whereas the first one is, so fixing it to become 5.132.0.
> Changed Office UI Fabric version to become consistent

- docs/design/empty-states.md
Simple spelling correction. Updated stucture to structure :-)
> Spelling correction

- docs/community/contribute.md
Switched out March 2018 example for the April 2019 monthly summary
> 
> 
> 
> 
> _(DELETE …
> Updated monthly summar example

- docs/solution-guidance/security-apponly-azuread.md
Writing ACS in the past tense as it was written to happen in the future, but already happened last year.
> Writing ACS in the past tense

- docs/spfx/use-developer-dashboard.md
Updated "intializing" to "initializing".
> Performance section update misspelling

- docs/spfx/office-ui-fabric-integration.md
Updating the icon usage in SPFx components
> Update icon usage in office-ui-fabric-react integration

- docs/general-development/keyword-query-language-kql-syntax-reference.md
- Related issues: fixes #3827
Added KQL samples for dates.
> Added KQL samples for dates

- docs/general-development/how-to-deploy-a-claims-provider-in-sharepoint.md
Added text to denote that the Farm Scope is needed in order to deploy a custom claims provider
> Added the Feature Scope required for deployment

- docs/spfx/web-parts/single-part-app-pages.md
- [ X] Content fix
Grammar fixes
> grammar updates

- docs/spfx/web-parts/guidance/build-custom-property-pane-controls.md
- docs/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties.md
I updated the correct modules with latest version of SPFx, I already have created a [pull request](https://github.com/SharePoint/sp-dev-fx-webparts/pull/849) with the example mentioned how to create a custom property pane to match with this changes.
> Update interfaces from correct module

- docs/declarative-customization/site-design-overview.md
- Related issues: 
updated site script example to include schema definition
> updated site script example to include schema definition

- docs/declarative-customization/site-design-json-schema.md
- Related issues: 
fixes [3886](https://github.com/SharePoint/sp-dev-docs/issues/3886)
1. Corrected "Remove a navigation link" verb.
2. Added section - Handle special characters.
Resolved issue raised here: [3886](https://github.com/SharePoint/sp-dev-docs/issues/3886)
> Fixed Typo and added new section

- docs/spfx/use-aad-tutorial.md
- Closes #3946
- Fixed instructions to reflect refactoring in SPFx v1.8.0 web part property pane to it's own NPM package.
- Fixed various markdown formatting issues (ordered bullets, code indentation, etc
> Update code reflecting refactoring + formatting fixes (#3946)

- docs/sp-add-ins/get-started-creating-sharepoint-hosted-sharepoint-add-ins.md
- closes #3936
- Fixed broken link reported in issue
- Cleaned up markup formatting
> Fix broken link & update markdown formatting (#3936)

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- Added example for checking an item in the list on both issue & PR template
- Refactored section for related issues in PR template with additional instructions
> Updating issue & pull request template

- docs/apis/alm-api-for-spfx-add-ins.md
- Closes #3926
- Updated details on Deploy endpoint to include required `body` content in HTTP request.
- Updated markdown formatting of request to match other MSFT docs for REST APIs
> Update ALM API deploy endpoint + formatting updates (#3926)

- docs/spfx/debug-in-vscode.md
Simple spelling correction from "debuging" to "debugging". :)
> Corrected mis-spelling of "debuging"

- docs/spfx/web-parts/get-started/use-fabric-react-components.md
- Closes #3811
- Fixed heading rendering issue
- Updated copy docs, being more specific "fabric" => "Office UI Fabric React"
- Fix markdown formatting errors
> Fix heading rendering, update markdown formatting (#3811)

- docs/general-development/sharepoint-search-rest-api-overview.md
- Related issues: fixes #3852
Add information on how to get output for the Search REST API in JSON format.
No additional notes/guidance.
> Add information on Search REST API output format

- docs/general-development/choose-the-right-api-set-in-sharepoint.md
- n/a
- Cleaned up lost of markdown issues in the docs
- Added link in "See also" to ALM API doc
> Markdown formatting cleanup in "choose right API" doc

- docs/general-development/sharepoint-search-rest-api-overview.md
- docs/schema/field-element-field-types-property-schema.md
- docs/schema/field-element-field-types.md
- docs/schema/field-element-field.md
- docs/schema/field-element-fields-elementschemasource-elementdatasourcetype-complextypeaction.md
- docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md
- closes #3745, closes #3780
- Fixed markdown formatting in feature schema reference for `Field` element & related elements
- Fixed markdown formatting & fixed typo in "get to know sp rest" doc
- Fixed markdown formatting in search REST API doc
> Markdown formatting fixes & few typos

- docs/spfx/web-parts/guidance/migrate-script-editor-web-part-customizations.md
> Add <any> for newer typescript version

- docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md
Fixing minor typo
N/A
Minor typo fix
> Minor typo fix

- docs/spfx/use-msgraph.md
- fixes 
- partially
- mentioned in 
This pull requests provides additional details on single sign-on support for ms graph client and on premices developments
> MsGraphClient: detailed limitations for SSO

- docs/declarative-customization/view-formatting.md
Fixed the text (by using the to determine) to add a clear sentence.
> Updated unclear sentence

- docs/spfx/enterprise-guidance.md
Updated latest release link to https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.8-release-notes
- fixes
- partially
- mentioned in
Documentation update to point to latest release of SPFx 1.8
> Update to latest release link

- docs/general-development/site-collection-app-catalog.md
N/A
Removing reference to a bugfix done in 2017
> Removing reference to a bugfix done in 2017

- docs/general-development/sharepoint-2019-development-platform.md
- Only supports basic styled syntax, Excel Styled Syntax is not supported.
> 
> 
> Please describe the changes in this PR. Sample description or details around bugs …
> Column Formatting for On Premise

- docs/declarative-customization/site-design-json-schema.md
Reflect that customers must use Product ID instead of ItemID when writing site designs that span across geos. The solution needs to be installed in each geo's app catalog
> Just a content update explained above
> 
> 
> Update SPFX Solution for multi-geo

- docs/spfx/shorter-share-link-format.md
- fixes #3851 
The shortened link format is corrected to https://contoso-my.sharepoint.com/:w:/p/john_contoso_com/ERGZUIZ8E0pAuC1oJtwz4dQB23IabPgbMtiVe0OLPtMybw
The shortened link format is corrected for OneDrive and SharePoint.
> Updated the shortened link format

- docs/transform/modernize-userinterface-site-pages-ui-guide.md
Correct spelling from "loosing" to "losing".
> Updated grammar spelling

- docs/spfx/integrate-with-teams-introduction.md
- fixes #4041
fix broken image link
> update broken link in "building MSFT teams tabs" doc

- docs/spfx/set-up-your-developer-tenant.md
- fixes #4007
Added details to the doc addressing differences between classic & modern sp admin centers
> Update setup dev tenant steps

- docs/sp-add-ins/sharepoint-add-ins.md
- fixes #4004
Fix grammatical typo in docs
> Grammatical typo fix

- docs/spfx/web-parts/get-started/use-fabric-react-components.md
- fixes #1590
Two Office UI Fabric docs were not in sync with the same guidance. This fixes that error.
> Update OUIFR guidance to be in sync across docs

- docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md
N/A
Fixed a typo: element.xml -> element**s**.xml
> Typo: element.xml -> elements.xml

- docs/declarative-customization/site-design-json-schema.md
> New capabilities around branding and nav.
> Reflect new branding and nav capabilities

- docs/declarative-customization/site-design-overview.md
> Updating to reflect branding and nav updates. As well as promote the abilluty to extract a site script from a list.
> Reflect branding/nav and promote extract List

- docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md
- fixes #3892
Updates POSH module using the new name that of the renamed module
> Fix renamed POSH module

- docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md
- docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
- docs/spfx/web-parts/get-started/connect-to-sharepoint.md
- docs/spfx/web-parts/get-started/deploy-web-part-to-cdn.md
- docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md
- docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md
- docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md
- docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md
Markdown fixes to spfx web part tutorial
> fixed markdown issues with web part tutorial

- docs/transform/modernize-userinterface-site-pages-videos.md
Updating word ".Net" to ".NET"
> Updating word

- docs/solution-guidance/portal-performance.md
> Fixed the spelling from "requried" to "required"
> Fixed the punctuation from "pages performance" to "page's performance"
> Fixed the space from "experience.The" to "experience. The"
> Fixed the punctuation from "new Classic portal pages then this section" to "new Classic portal pages, then this section"
> Fixed the word from "high level" to "high-level"
> Updated grammar and spelling.

- docs/transform/modernize-userinterface-site-pages-dotnet.md
Updating word ".Net" to ".NET".
> Updating word .Net

- docs/community/community.md
Updating GMT times for community meetings as they are out by one hour
> Update GMT times as they are one hour out

- docs/declarative-customization/site-design-json-schema.md
Provide clarity on the idempotency of site scripts at the very top
- fixes #4081 
> Hopefully clarifies the current behavior for reapplying site designs
> Address idempotency issues

- docs/transform/modernize-userinterface-site-pages-dotnet.md
> Updated word

- docs/spfx/web-parts/isolated-web-parts.md
A comma has added in the sentence.
> Added comma

- docs/solution-guidance/portal-performance.md
Added "Summary Links Webpart" to the list of "Avoid XSLT based webparts"
- fixes https://github.com/SharePoint/sp-dev-docs/issues/4161
On the page https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-performance
Added "Summary Links Webpart" to the list of "Avoid XSLT based webparts" 
Added "Summary Links Webpart" to the list of "Avoid XSLT based webparts"
> Updated section "Avoid XSLT based webparts"

- docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
- fixes #4106
Rephrased a statement to be more clear that was phrase a little confusingly.
> Rephrased statement to be more clear

- docs/spfx/web-parts/get-started/use-fabric-react-components.md
Adding an entry point to the Office UI Fabric React website and another one to the API reference documentation on docs.microsoft.com portal.
> Add Fabric documentation entry points.

- docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md
Fixes #4190
- fixes #4190 
added guidance regarding which preset version to use for unit tests.
> SPFX devops: provided guidance for preset version to match react version

- docs/spfx/using-teams-solutions-in-sharepoint.md
Removed important note about the functionality being in preview
I removed the Important note about the functionality being under preview because it is now released.
> Removed preview note

- docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md
- fixes #4181
Update supported guidance for save site as template
> Update supported guidance for save site as template

- docs/general-development/sharepoint-search-rest-api-overview.md
- fixes https://github.com/sharepoint/sp-dev-docs/issues/4177
Corrected the spelling mistake on search rest api overview. Capitalization corrected to HitHighlightedProperties.
On the page, https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview
Corrected the spelling mistake on search rest api overview. Capitalization corrected to HitHighlightedProperties.
> Corrected spelling mistake

- docs/schema/listinstance-element-list-instance.md
- fixes #4231
`<ListInstance>` Feature XML schema doc markdown formatting fixes addressed.
> Fix markdown formatting for listinstance

- docs/transform/modernize-userinterface-site-pages-videos.md
Updated the word "you" to "your"
> Updated grammar

- docs/declarative-customization/site-design-json-schema.md
- fixes #2336
Update missing verb for adding field
> Update missing verb for adding field

- docs/features/site-footer.md
> Fixing the roll out time frame

- docs/spfx/toolchain/update-latest-packages.md
N/A
Updating the link to the release notes to point to the release notes of the post GA versions instead of the pre-GA versions which will be a lot more useful
> Updated release notes link

- docs/general-development/keyword-query-language-kql-syntax-reference.md
Added new samples and description for new functionality added to KQL in SP2019/SPO
> Grouping property restrictions in a KQL query

- docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/3012
- partially https://github.com/SharePoint/sp-dev-docs/pull/4138, https://github.com/SharePoint/sp-dev-docs/pull/4183
Corrected Type for adding data in a code.
Implemented changes suggested in #4138
On the page https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service
Corrected Type for adding data in a code that adds an item to a list sample data.
> Corrected Type for adding data

- docs/general-development/master-pages-the-master-page-gallery-and-page-layouts-in-sharepoint.md
na
Add a space between SharePoint and to
> Added a space between SharePoint and to

- docs/features/site-footer.md
> Fixing some content for accuracy

- docs/spfx/toolchain/update-latest-packages.md
Updated the link to the proper SPFx release notes that matter instead of the ones up to GA only
> Updating link to release notes

- docs/declarative-customization/site-design-pnp-provisioning.md
> minor typo

- docs/transform/modernize-userinterface.md
Changed word "libraries" "library"
> Changed word "libraries" "library"

- docs/transform/modernize-userinterface.md
Removed "," & replaced "end user" with "end-user"
> Grammar Checked

- docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/4301
On the page https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on
Updated the markdown to reflect ACS retirement note to doc header with details.
Updated ACS retirement note to doc header with details.
> Updated ACS retirement header with details

- docs/declarative-customization/site-design-json-schema.md
close #2205 
close #2993 
close #3543
close #2205 
close #2993 
close #3543
Addresses customer reported issues
> Address documentation issues for site designs

- docs/general-development/how-to-create-a-page-layout-in-sharepoint.md
Not clear if the text was trying to show a div tag or not.  If so, we may need to change the markdown to use backticks.
na
Code was causing an unnecessary line break.  Not clear if the text was trying to show a div tag or not.  If so, we may need to change the markdown to use backticks.
> Code was causing an unnecessary line break

- docs/features/site-footer.md
> Adding some clarifications and updating images

- docs/spfx/web-parts/guidance/migrate-script-editor-web-part-customizations.md
Corrected spelling Framew../ork to Framework
Corrected spelling Framew../ork to Framework
> Correct grammar spelling

- docs/declarative-customization/site-theming/sharepoint-site-theming-json-schema.md
- fixes #4406
Updated the link to the Theme Generator tool, which was being redirected to the Fabric UI page.
Thanks for info @sparkitect! :)
> Updated link to Theme Generator Tool

- docs/declarative-customization/site-design-json-schema.md
Relates to https://github.com/SharePoint/sp-dev-docs/issues/3037
Added documentation on activateSPFeature as there are quite some misunderstandings around it not working for site scoped features due to lack of documentation. Trying to take that away with this update.
> Added documentation on activateSPFeature

- docs/solution-guidance/Migrate-InfoPath-forms-to-SharePoint.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/3361
On the page https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/migrate-infopath-forms-to-sharepoint
In the "Alternatives to InfoPath in SharePoint 2013" table, Removed extra space after the s in users for first scenario.
In the "Alternatives to InfoPath in SharePoint 2013" table, Removed extra space after the s in users for first scenario.
> Fixed extra spacing

- docs/declarative-customization/column-formatting.md
SharePoint has added support for more functions in JSON, namely - subString, getDate, getMonth, getYear, pow, floor & ceiling. This PR contains updates to column formatting documentation, describing the usage of these functions.
> Added documentation for more supported functions such as pow, subString

- docs/spfx/web-parts/guidance/supporting-section-backgrounds.md
- fixes #4423 
- Added import statements and private variable declarations to inline samples to clear up some confusion.
- Changed style property from `color` to `backgroundColor` to match the article's theme of section backgrounds
- Added link to full samples in github
> Added details to sample and switched to bodyBackground

- docs/general-development/accessibility-in-sharepoint.md
changed: asassistive  / to: as assistive
> Spelling correction - added space

- docs/sp-add-ins/add-in-permissions-in-sharepoint.md
Copied from get-started-developing-with-social-features-in-sharepoint.md for better CTRL+F ability. Was stuck for ages trying to find "user profile".
> add in permissions: add more detail to social permissons

- docs/design/design-guidance-overview.md
> Removed comma

- docs/schema/spviewscope-simple-type-deploymentmanifest.md
> Fixed typo (alll)

- docs/declarative-customization/site-design-json-schema.md
"Actions can be run" instead of "Actions can be runned"
Small grammar correction, replaced the word "runned" with the word "run".
> Small grammar correction

- docs/apis/site-creation-rest.md
Request requires a 'request' object for the JSON payload. For issue #4567
- fixes #4567 
Updated documentation to include the proper JSON payload for creating sites.
> Updating Body of POST Request

- docs/spfx/web-parts/guidance/share-data-between-web-parts.md
Ref discussion last week @VesaJuvonen @johnguy0. Not sure what a better title would be.
Added note to use dynamic data for SPFx v1.7.0 or later.
> Added note to use dynamic data for part communication

- docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md
Possible workaround for an error that shows while updating the package.
- mentioned in #4322
Suggesting additional content to handle updating versions
> Adding information about updating package

- docs/declarative-customization/column-formatting.md
- fixes #4269 
- Updated list of supported column types
- Added section describing Location column sub properties
> Updated Supported Columns & Location Values

- docs/general-development/how-to-create-an-odata-data-service-for-use-as-a-bcs-external-system.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/4566
1. "AdventureWorks 20012 LT script" renamed to  "AdventureWorks 2012 LT script".
2. Hyperlink for Script and Data is pointed to https://github.com/Microsoft/sql-server-samples/releases/tag/adventureworks
3. Formatted code samples
4. Formatted headers for Note sections
1. "AdventureWorks 20012 LT script" renamed to  "AdventureWorks 2012 LT script".
2. Hyperlink for Script and Data is pointed to https://github.com/Microsoft/sql-server-samples/releases/tag/adventureworks
3. Formatted code samples
4. Formatted headers for Note sections
> Link and Code Formatting updates

- docs/transform/modernize-classic-sites.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/4652
In the section explaining about modernizing the publishing portals, provided link to Modernize classic publishing portals for continued reading.
Provided link to Modernize classic publishing portals for continued reading.
> Link to Modernize classic publishing portals

- docs/transform/modernize-publishing-portal.md
The link is renamed to "Guide to the Modern experience in SharePoint"
The link is renamed to "Guide to the Modern experience in SharePoint"
> Renamed the link

- docs/general-development/create-a-workflow-with-elevated-permissions-by-using-the-sharepoint-workflo.md
Correction to permissions guidance. Requested by support
Added note in workflow guidance for SharePoint Online. Access to the Site collection app permissions requires Site collection administrator permissions
> Change Site Owner to Site Collection Administrator

- docs/sp-add-ins/add-in-permissions-in-sharepoint.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/4611
Under the section "Managing and troubleshooting add-in permissions", the button text "???" is corrected to "..."
Under the section "Managing and troubleshooting add-in permissions", the button text "???" is corrected to "..."
> Corrected button text to "..."

- docs/spfx/library-component-tutorial.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/4626
Added section on how to unlink a library from SPFx solution and a symlink from local "node_modules" folder.
For SharePoint library component, added section - How to unlink SPFx library
> Added section How to unlink SPFx library

- docs/declarative-customization/site-design-json-schema.md
New Schema includes formatterJSON property for views.  Adding new property to documentation.
Updating addSPView to include formatterJSON value
> Adding new property formatterJSON for new schema

- docs/spfx/extensions/guidance/using-custom-dialogs-with-spfx.md
N/A
Updated code samples and text so it works with SPFx 1.91 and the latest version of OfficeUI Fabric for React. The current code does not work or compile with SPFx 1.91.
> Updating OfficeUIFabric React Extenstion article to work with SPFx 1.91

- docs/spfx/overview-graphhttpclient.md
bold with escape characters
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/overview-graphhttpclient
> 
> 
> Please describe the changes in this PR. Sample …
> Typo "**@microsoft/sp-http**"→"**\@microsoft/sp-http**"

- docs/sp-add-ins/add-sharepoint-write-operations-to-the-provider-hosted-add-in.md
- fixes #4771
Typo fix & markdown formatting cleanup
> Fixup file typo & markdown formatting

- docs/sp-add-ins/include-a-custom-button-in-the-provider-hosted-add-in.md
> markdown formatting fixes

- docs/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code.md
- fixed #4712
Clarify code comment & update markdown formatting
> Clarify code comment & update markdown formatting

- docs/sp-add-ins/add-a-workflow-to-a-sharepoint-hosted-sharepoint-add-in.md
- fixes #4665
- references #4654
Update incorrect step, cleanup markdown formatting
> Update incorrect step, cleanup markdown formatting

- docs/spfx/use-aadhttpclient-enterpriseapi.md
- fixes #4713
Add missing step to docs
> Update missing step in docs

- docs/spfx/web-parts/guidance/localize-web-parts.md
- closes #4732 
Includes PR #4732 + markdown fixes
> Docfix pr4732

- docs/general-development/site-collection-app-catalog.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/4542
Added information about hidden list that stores tenant app catalog information.
Added information about hidden list that stores tenant app catalog information.
> Updated Governance section under Considerations

- docs/sp-add-ins/sharepoint-rest-graph.md
- docs/toc.yml
Added docs to mention the REST v2 API's documented via the Graph API's.
cc @VesaJuvonen
> Added REST v2 docs

- docs/general-development/social-feed-rest-api-reference-for-sharepoint.md
> Polishing PR 4748

- docs/apis/export-amr-api.md
Fixed typo in SharePoint: Sharepoint to SharePoint.
> Fixed typo: Sharepoint to SharePoint

- docs/sp-add-ins/handle-list-item-events-in-the-provider-hosted-add-in.md
For Issue #4805
- fixes #4805
Replaced &amp; with & where necessary
> Updating encoded ampersands

- docs/solution-guidance/custom-field-type-sharepoint-add-in.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/4472
> png is not displayed

- docs/sp-add-ins/register-sharepoint-add-ins.md
- fixes #3055
- fixes typo
- cleanup markdown formatting
> Fix typo, cleanup markdown formatting

- docs/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery.md
- fixed #3159
Typo fix & markdown cleanup
> Fix typo, markdown cleanup

- docs/spfx/set-up-your-development-environment.md
Update guidance on SP2016 + SPFx
> update spfx dev guidance for sp2016

- docs/spfx/web-parts/get-started/connect-to-sharepoint.md
- fixes #4908
Fixes typo in SPFx getting started doc
> DocFix for typo in SPFx getting started doc

- docs/transform/modernize-userinterface-lists-and-libraries-scanner.md
Change "an" to "a"
> Corrected Grammar in the article
> Corrected Grammar

- docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md
> remove stray backslash

- docs/solution-guidance/modern-experience-customizations.md
- docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md
- fixes #4920 
Fixes the misspelling of Sharpoint into SharePoint (2 different docs)
> Changed Sharpoint to SharePoint

- docs/declarative-customization/site-design-trigger-flow-tutorial.md
With the rename of **Microsoft Flow** to **Power Automate**, there were a number of issues with this article. There have also been many UI changes in `flow.microsoft.com` since the article was last updated in October, 2018. There have also been licensing changes for triggers like **Request**.
I've made changes to reflect all of this, to the best of my ability.
These corrections will make the article useful again.
> Updated to reflect Power Automate changes

- docs/spfx/hyperlinking.md
- docs/toc.yml
- fixes #1582
Added documentation about the usage of `data-interception="off"` to bypass page router on hyperlinks.
> #1582 added documentation on data-interception attribute

- docs/spfx/enterprise-guidance.md
Updated the latest release of the SharePoint Framework as 1.9.1
Updated the latest release of the SharePoint Framework as 1.9.1
> Updated Current status of SharePoint Framework

- docs/spfx/set-up-your-developer-tenant.md
Steps to create app catalog & developer site no longer relevant and needed to be refreshed.
> Update steps to match modern SP admin center

- docs/community/community.md
None
A small bit of proof-reading: 
A couple of mentions of "the Microsoft" changed to "Microsoft" and a period deleted for consistency.
None
> A couple of edits

- docs/features/hub-site/REST-sphubsite-type.md
The property for SPHubSite should be LogoUrl with 'L' in capital
The property for SPHubSite should be LogoUrl with 'L' in capital
> The property should be LogoUrl

- docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md
- docs/spfx/toolchain/implement-ci-cd-with-azure-pipelines.md
none
- adds new documentation to leverage Azure Pipelines with SPFx for CI, CT, CD
> - adds azure pipelines spfx cicd documentation

- docs/toc.yml
- partially #4976
- adds link to new Azure Pipelines documentation in the navigation
> updates navigation to include Azure Pipelines docs link

- docs/solution-guidance/Introducing-the-PnP-Provisioning-Engine.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/4999
Corrected link to PnP Provisioning Engine and the Core Library
Corrected link to PnP Provisioning Engine and the Core Library
> Corrected link

- docs/declarative-customization/site-design-rest-api.md
Documentation about the new REST API GetSiteScriptFromWeb.
> Added documentation about the GetSiteScriptFromWeb REST API;

- docs/sp-add-ins/host-webs-add-in-webs-and-sharepoint-components-in-sharepoint.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/5018
Under types of SharePoint components that can be in a SharePoint Add-in, updated List and library instances for Classic experience only.
Updated List and library instances for Classic experience only.
> Classic experience only

- docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md
The docs refer to the Authentication Code flow, while it should be the Authorization Code flow, as there is no such thing as an Authentication Code flow in the OAuth specification.
> Rename Authentication Code flow to Authorization Code flow

- docs/general-development/site-collection-app-catalog.md
N/A
Cleaning up the sample commands so they align and are as easy as possible to use
> Sanitizing the Site Collection App Catalog sample commands

- docs/toc.yml
Fixes a wrong topic title in the outline of the docs. Accidentally there was the same title for two different topics.
> Fixed wrong topic title in the outline

- docs/declarative-customization/site-design-json-schema.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/5092
In the Site design JSON schema, removed semicolon at the end of JSON
In the Site design JSON schema, removed semicolon at the end of JSON
> Removed semicolon at the end of JSON

- docs/spfx/dynamic-data.md
- fixes #5107
- add `imports` to code snippet
- improved readability
> Add missing code in code snippet

- docs/spfx/use-aadhttpclient-enterpriseapi-multitenant.md
- docs/spfx/web-parts/guidance/connect-to-api-secured-with-aad.md
- fixes #5033, fixes #5069
- update docs to use the Application ID URI when obtaining the AAD client/token, not the GUID of the Azure AD app
- fix markdown rendering issues
- improve readability
> Fix doc errors

- docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md
- fixes #5064
- fix broken link reported in #5064
- address readability issues
- improve doc acrolinx score
- fix markdown issues
> fix doc broken link and improve readability

- docs/spfx/web-parts/guidance/localize-web-parts.md
- fixes #5951
- fix error reported in #5951
- fix markdown issues
- improve readability & acrolinx score
> fix doc error

- docs/transform/modernize-scanner.md
- fixes #4996 
- fix spelling errors and improve acrolinx score (readability)
> imrove doc readability, fix spelling errors

- docs/spfx/web-parts/get-started/using-microsoft-graph-apis.md
- fix markdown formatting issues
- improve readability with acrolinx score
> Fix markdown & improve doc readability

- docs/spfx/toolchain/implement-ci-cd-with-azure-pipelines.md
Provided link to Enable preview feature for Azure DevOps Services
Provided link to Enable preview feature for Azure DevOps Services
> Link added to Enable preview feature

- docs/sp-add-ins/determine-sharepoint-rest-service-endpoint-uris.md
- docs/sp-add-ins/navigate-the-sharepoint-data-structure-represented-in-the-rest-service.md
- docs/sp-add-ins/synchronize-sharepoint-items-using-the-rest-service.md
- docs/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery.md
- docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md
- docs/sp-add-ins/working-with-folders-and-files-with-rest.md
- docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md
- fixes #5128
- reference link pointed to root MSDN docs, now outdated, so removed
- update markdown formatting for HTTP requests to match MS docs guidelines
- fix typos
- update content readability score
> SP REST docs cleanup & broken link fixes

- docs/sp-add-ins/determine-sharepoint-rest-service-endpoint-uris.md
- docs/sp-add-ins/navigate-the-sharepoint-data-structure-represented-in-the-rest-service.md
- docs/sp-add-ins/synchronize-sharepoint-items-using-the-rest-service.md
- docs/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery.md
- docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md
- docs/sp-add-ins/working-with-folders-and-files-with-rest.md
- docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md
> Title fix on docs in last PR

- docs/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code.md
- docs/sp-add-ins/determine-sharepoint-rest-service-endpoint-uris.md
- docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md
- docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md
- docs/sp-add-ins/retrieve-tenant-app-catalog-url-rest.md
- docs/sp-add-ins/set-custom-permissions-on-a-list-by-using-the-rest-interface.md
- docs/sp-add-ins/synchronize-sharepoint-items-using-the-rest-service.md
- docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md
- docs/toc.yml
- update markdown formatting
- apply changes to improve readability score
- update links pointing to MSDN/TECHNET to docs.microsoft.com
> SharePoint REST docs updates

- docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
- docs/solution-guidance/Handle-SharePoint-Online-throttling-by-using-exponential-back-off.md
- fixes #4274
- minor modifications to address most current guidance to use `retry-after` header
- fix markdown formatting
- improve readability score
> Update throttling guidance

- docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md
- fixes #5149
Fix table rendering from markdown => HTML
> Fix table rendering

- docs/spfx/web-parts/single-part-app-pages.md
Simplified PowerShell example to use Set-PnPClientSitePage cmdlet
> Simplified PowerShell example

- docs/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart.md
Added word Microsoft
Added word Microsoft
> Added word Microsoft

- docs/apis/migration-api-overview.md
- closes #5156
- fixed numerous markdown issues with the page breaking rendering
> Fix page rendering

- docs/spfx/library-component-tutorial.md
Adding comma in the sentence
Adding comma in the sentences.
> Adding comma

- docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md
Fixes the parameter values of the o365 command when uploading/deploying to a site collection app catalog. The correct scope shall be 'sitecollection'.
> Fix in implement-ci-cd-with-azure-devops.md

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
- updated generic issue list template
- new issue list templates for bugs/errors, feature requests, general issues
- links to other resources
> update & add issue templates

- docs/declarative-customization/column-formatting.md
- docs/spfx/set-up-your-development-environment.md
- [ X] Content fix
Column-formatting - 
The Flow action content Code is aligned the above screenshot that shows a list with a Flow button added to the Action column. the screenshot Flow context shown as 'Send to Manager' which is incorrect in Code **txtContent :"It's Flow Time".**
Refer Screenshot in original document - https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#create-a-button-to-launch-a-flow
> Align Content- code is aligned with Snapshot change 

- docs/declarative-customization/site-design-pnppowershell.md
N/A
There was a help page already on using SPO Site Scripts and Site Designs using SPO Management Shell and Office 365 CLI, but not yet using PnP PowerShell. Adding that with this page.
> Creating documentation on using SPO Site Scripts & Designs with PnP PnP PowerShell

- docs/declarative-customization/site-design-powershell.md
PR #5167 for adding the page to which it will point
Adding in a reference to the documentation on the same topic using PnP PowerShell. Actual file is being added through PR #5167
> Adding reference to PnP PowerShell on SPO Management Shell Site Script/Design page

- docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md
Updating the package-solution.json file with the new property 'isDomainIsolated' that was added after this article got initially published
Updating the package-solution.json file with the new property 'isDomainIsolated' that was added after this article got initially published
> Updating the package-solution.json file with the new property
