- docs/solution-guidance/Branding-and-site-provisioning-solutions-for-SharePoint.md
- docs/solution-guidance/provisioning-console-application-sample.md
- docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md
- docs/sp-add-ins/context-token-oauth-flow-for-sharepoint-add-ins.md
- docs/sp-add-ins/create-and-use-access-tokens-in-provider-hosted-high-trust-sharepoint-add-ins.md
- docs/sp-add-ins/create-provider-hosted-sharepoint-add-ins-to-access-sap-data-by-using-the-sap-ga.md
- docs/sp-add-ins/handle-security-tokens-in-provider-hosted-low-trust-sharepoint-add-ins.md
- docs/spfx/extensions/guidance/migrate-jslink-to-spfx-extensions.md
- fixes #2070, fixes #2100, fixes #2174, fixes #2213
- update doc references to NuGet packages
- remove public site option reference
- clean up markdown formatting
- improve doc readability score
> Fixing multiple docs, markdown issues & improve doc readability scores

- docs/spfx/extensions/get-started/building-simple-field-customizer.md
Please Change HelloWorld.module.scss to HelloWorldFieldCustomizer.module.scss - this is probably a copy/paste artefact.
Please Change HelloWorld.module.scss to HelloWorldFieldCustomizer.module.scss - this is probably a copy/paste artefact.
> Change HelloWorld.module.scss to HelloWorldFieldCustomizer.module.scss

- docs/spfx/web-parts/basics/configure-web-part-icon.md
- docs/spfx/web-parts/basics/hide-web-part-from-toolbox.md
- docs/spfx/web-parts/basics/use-web-parts-full-width-column.md
- docs/spfx/web-parts/guidance/validate-web-part-property-values.md
> Updated the $schema in the package-solution that should be matched with the latest Yeoman generator.
> Updated the $schema in the package-solution

- docs/spfx/web-parts/guidance/intercepting-query-changes-in-webparts.md
- docs/toc.yml
- none
There is a use-case where web parts need to listen to query string
changes but the SharePoint Framework provides no guarantees that a
web part will re-render in the event of a query string change whilst on
the same page. This document serves as a guide to writing a Web Part
that can respond to query string changes.
Added guidance on subscribing to query string changes in web parts.
> Add guidance on subscribing to query string updates

- docs/spfx/extensions/get-started/build-a-hello-world-extension.md
The description should say
Select N to allow not allow solution to be deployed to all sites immediately.
The description should say
Select N to allow not allow solution to be deployed to all sites immediately.
> Updated description to deploy solution

- docs/spfx/library-component-overview.md
- docs/spfx/library-component-tutorial.md
- markdown corrections for code formatting
> Cleanup markdown formatting for library component articles

- docs/spfx/library-component-tutorial.md
Messed up the article date on last push... fixed.
> Date fixup

- docs/general-development/how-to-create-a-page-layout-in-sharepoint.md
> Adding a period to add the sentence.

- docs/solution-guidance/Handle-SharePoint-Online-throttling-by-using-exponential-back-off.md
> Fix incorrect internal broken links

- docs/community/contribute.md
- docs/community/social-media.md
- docs/general-development/sharepoint-2019-development-platform.md
- docs/spfx/sharepoint-2016-support.md
- docs/spfx/sharepoint-2019-support.md
- docs/support-feedback.md
- docs/toc.yml
- Renamed "Solution guidance" => "Scenario Guidance"
- Renamed "SharePoint development overview" => "Archive"
- contains loads of old content & deemed "outdated" by MSFT
- will update on an as-needed basis
- Refactored / reorganized:
- SPFx
- Addins
- Community
- Added "Overview" nodes to items that expand
- Removes the dupe of a section & first node with same name
- Renamed "Features" to "Capabilities & features"
- Removes confusion if it's a Feature (ie: feature.xml)
- Moved declarative customization options => this new section
> Documentation TOC refactoring & updates

- docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md
- docs/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions.md
- docs/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions.md
- docs/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions.md
- docs/spfx/use-aad-tutorial.md
- docs/spfx/use-aadhttpclient-enterpriseapi-multitenant.md
- docs/spfx/use-aadhttpclient-enterpriseapi.md
- docs/spfx/use-aadhttpclient.md
- docs/spfx/web-parts/get-started/deploy-web-part-to-cdn.md
- docs/spfx/web-parts/guidance/connect-to-api-secured-with-aad.md
> Updated the schema file that referenced in the latest Yeoman generator are the most current and correct references.
> Updated the Schema file

- docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md
Added few commas for better readability
> 
> 
> 
> _(DELETE …
> Added few commas for better readability

- README.md
- docs/community/community.md
> Update the new twitter & Facebook accounts from officeDevPnP  & Microsoft 365 Dev.
> Update the new twitter & Facebook accounts from officeDevPnP  & Microsoft 365 Dev.

- docs/spfx/office-addins-create.md
Included --save option to enable NPM to include the packages to dependencies section of the package.json file.
Included --save option to enable NPM to include the packages to dependencies section of the package.json file.
> save option while installing Office JavaScript SDK

- docs/spfx/web-parts/get-started/office-addins-tutorial.md
- docs/spfx/web-parts/guidance/use-existing-javascript-libraries.md
these are type declarations, these should go in devDependencies
> Update the type declarations 

- docs/declarative-customization/site-design-pnp-provisioning.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/5422
Added note on Location of Storage Account & Function App
Added note on Location of Storage Account & Function App
> Note on Location of Storage Account & Function App

- docs/general-development/sharepoint-search-rest-api-overview.md
Please review - updates to include CDN support originally documented in the CDN documentation 2 years ago but were regressed with the sync to async search change.
> 
>  …
> Updates to reflect CDN changes for the Search API

- docs/declarative-customization/column-formatting.md
Document how to concatenate strings and how to find the length of a string ( workaround )
Document and example of how to concatenate strings and how to find the length of a string ( workaround )
> Document some string related operators

- docs/features/hub-site/create-hub-site-with-powershell.md
N/A
Commands shown where a mixture of SPO Management Shell and PnP PowerShell. A mix that doesn't even work anymore today. Cleaned up the article to show only PnP PowerShell to avoid confusion and complexity as it doesn't add anything to use both.
> Fixed hub site creation page

- docs/transform/modernize-userinterface-site-pages-powershell.md
No related issue
Simple grammatical correction : Remove "s" of page
> Correct grammatical mistake

- docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md
- docs/spfx/web-parts/guidance/reference-third-party-css-styles.md
> these are type declarations, these should go in devDependencies.
> Update the type declarations

- docs/spfx/web-parts/overview-client-side-web-parts.md
Updated letter 's' to 'S' in Getting Started as it is a proper noun
Updated letter 's' to 'S' in **Getting Started** as it is a proper noun
> Updated Getting started to Getting Started

- docs/spfx/library-component-overview.md
- [] Example checked item (*delete this line*)
Tested and verified, a `library component` solution package can be used if it is only installed in the site app catalog.
> Library solution app catalog update

- docs/general-development/sharepoint-search-rest-api-overview.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/5429
Added parameter EnableDynamicGroups
Added parameter EnableDynamicGroups to SharePoint Search REST API
> Added parameter EnableDynamicGroups to SharePoint Search REST API

- docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md
N/A
Did some small textual changes to correct a statement on having to be a global admin to enable a site scoped feature and removed the quotes from the PnP PowerShell commands as these can be found confusing and copied along.
> Small textual changes to SP Site Theming article

- docs/solution-guidance/security-apponly-azuread.md
- fixes #5455
> Correct typo - "Gran**d** consent". Click on the "Gran**d** admin cons**t**ent for "
should be "Grant consent". Click on the "Grant admin consent for ".
> Typo - Update security-apponly-azuread.md

- docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md
- docs/spfx/extensions/get-started/building-simple-field-customizer.md
- docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
> Correct the description - Select N to **not** allow the solution to be deployed to all sites immediately.
> Correct the description

- docs/declarative-customization/site-design-overview.md
- docs/declarative-customization/site-design-pnp-provisioning.md
Replace Microsoft Flow by Power Automate
> Replace Microsoft Flow by Power Automate

- docs/business-apps/power-automate/get-started/sharepoint-actions-triggers.md
- docs/business-apps/power-automate/guidance/working-with-get-items-and-get-files.md
- docs/business-apps/power-automate/guidance/working-with-send-sp-http-request.md
Fixing multiple errors in the build reports. The content didn't conform to MSDocs guidelines
> Fixing build report errors

- docs/sp-add-ins/high-trust-configuration-scripts-for-sharepoint.md
- fixes #5480
- update markdown formatting
- fix script error reported in issue by the community
> Fixup script error

- docs/spfx/use-aadhttpclient.md
> Update markdown to fix formatting issues

- docs/business-apps/power-automate/get-started/connect-to-other-services-in-your-flow.md
Performed edit scrub to meet MSTP guidelines. Swapped out Microsoft Flow with Power Automate where appropriate. 'Next Steps' section needs to be populated with content.
> 
> 
> _(DELETE THIS PARAGRAPH AFTER …
> Edit scrub on 'Connect your flow to other services' article

- docs/business-apps/power-automate/get-started/create-your first-flow.md
Performed edit scrub per MSTP guidelines and upgraded content to match new UI. Technical review required.
> 
> 
> Please describe the changes in this PR. Sample …
> Edit scrub and updated steps with new UI.

- docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
N/A
If we're going to give an example, I think we should give a complete and good one. In my opinion such a sample should show to request nometadata instead of verbose from our endpoints. It does make quite a huge difference in data size. I haven't ran across any case yet where the metadata was actually being used.
> Changing Accept header to request nometadata

- docs/business-apps/introduction-to-sharepoint-business-process-integration.md
Edited content to meet MSTP standards and swap out Microsoft Flow with Power Automate and Powerapps with Power Apps.
> 
> 
> Please describe the changes in this PR. …
> SharePoint custom forms and automated business workflow

- docs/business-apps/power-automate/get-started/sharepoint-actions-triggers.md
Performed edit scrub updates per MSTP guidelines. Requires technical review.
> 
> 
> Please describe the changes in this PR. Sample description or details around bugs …
> Edit pass on SharePoint Connector for Power Automate.

- docs/business-apps/power-automate/guidance/working-with-get-items-and-get-files.md
- docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md
- docs/toc.yml
TOC updates and small fixes for Business Apps and Process Automation. 
@VesaJuvonen please review the TOC updates.
> TOC updates and small fixes

- docs/spfx/enterprise-guidance.md
Under para "Current status of SharePoint Framework", updated current SPFx version as v1.10
Under para "Current status of SharePoint Framework", updated current SPFx version as v1.10
> Updated SPFx version to v1.10

- docs/solution-guidance/Bulk-user-profile-update-api-for-sharepoint-online.md
I simply improved the quality of the content about using an app-only context to execute the API.
> Improved content about app-only context

- docs/business-apps/introduction-to-sharepoint-business-process-integration.md
Streamlined duplicate info and fixed typo with Power Automate.
> 
> 
> Please describe the changes in this PR. Sample description or details around bugs which are being …
> Update intro to Business apps and business process automation article.

- docs/community/repositories.md
Removed below line from line number 50 as it is not working
"Source for templates available from the PnP Template Gallery at http://templates-gallery.sharepointpnp.com |"
and added a line
Maybe we should add this url https://provisioning.sharepointpnp.com/
https://provisioning.sharepointpnp.com/
> Removed a non working link

- docs/apis/sharepoint-rest-graph.md
Removed an unneeded 'a'.
Changed nativly to natively.
Removed an unneeded 'a'.
> Changed nativly to natively.

- docs/solution-guidance/security-apponly-azureacs.md
N/A
Added PnP PowerShell sample, fixed broken link, updated ACS retirement text to be written in the past instead of the future
> Added PnP PowerShell sample, fixed broken link

- docs/features/site-footer.md
N/A
Updated sample of working with PnP PowerShell to enable or disable the page footer to be shown to a way shorter syntax through it's native command for this. Depends on https://github.com/pnp/PnP-PowerShell/pull/2634 to be merged and released first in the May 2020 release of PnP PowerShell.
> Updating PnP PowerShell set footer sample

- docs/solution-guidance/Bulk-user-profile-update-api-for-sharepoint-online.md
N/A
Added PnP-PowerShell sample to using the bulk user profile api
> Added PnP-PowerShell sample to using the bulk user profile api

- docs/apis/export-amr-api.md
- docs/apis/sharepoint-rest-graph.md
- docs/business-apps/introduction-to-sharepoint-business-process-integration.md
- docs/business-apps/power-automate/get-started/connect-to-other-services-in-your-flow.md
- docs/community/repositories.md
- docs/declarative-customization/get-started-create-site-design.md
- docs/declarative-customization/site-design-json-schema.md
- docs/features/site-footer.md
- docs/solution-guidance/Bulk-user-profile-update-api-for-sharepoint-online.md
- docs/solution-guidance/configuring-the-pnp-provisioning-engine.md
- docs/solution-guidance/modern-experience-customizations-customize-sites.md
- docs/solution-guidance/security-apponly-azureacs.md
- docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md
- docs/spfx/enterprise-guidance.md
- docs/spfx/extensions/basics/preallocated-space-placeholders.md
What's in this Pull Request?
Merging latest changes.
> Merging latest changes

- docs/declarative-customization/column-formatting.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/5597
The link to Office UI Fabric are updated.
The link to Office UI Fabric are updated.
> Fixed broken links of Office UI Fabric

- docs/spfx/use-theme-colors-in-your-customizations.md
The broken link to "Support section backgrounds" is fixed with correct working reference.
The broken link to "Support section backgrounds" is fixed with correct working reference.
> Fixed broken link: Supporting Section Backgrounds

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
n/a 
- added additional prompts for target SharePoint environment in the context question
- standardized the environment heading
> Update issue templates

- docs/scenario-guidance/Branding.md
- docs/scenario-guidance/Development-models.md
- docs/scenario-guidance/Long-running-scheduled-operations.md
- docs/scenario-guidance/Performance.md
- docs/scenario-guidance/User-information.md
> Most of links which is hosted under the dev.office.com are broken, now fixing the broken links with proper urls
> Fixing the broken links related to dev.office.com

- docs/apis/migration-api-azure-container-and-queue.md
Category:  Content Fix
Description:  Added note regarding required endpoints if your tenant is hosted in GCC
> update migration api azure container and queue

- docs/apis/export-amr-api.md
Content fix:  [X]
Correcting info on IncludeSecurity descriptions, plus emphasizing issues regarding performance and using this setting.
> updated export-amr-api.md

- docs/scenario-guidance/Security.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/5633
- Fixed the link to Azure Active Directory implicit flow authentication samples.
- Removed duplicate sample - Dynamically request permissions for an add-in.
- Fixed the link to Azure Active Directory implicit flow authentication samples.
- Removed duplicate sample - Dynamically request permissions for an add-in.
> Updated security samples link association

- docs/apis/migration-api-encryption.md
Content update:
Updates to encryption and security.
> update migration api encryption

- docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md
- docs/general-development/how-to-create-scorecard-transforms-for-performancepoint-services-in-sharepoint-2.md
- docs/index.md
- docs/scenario-guidance/Branding.md
- docs/schema/startpage-element-propertiesdefinition-complextypesharepoint-add-in-manifest.md
- docs/sp-add-ins/add-in-permissions-in-sharepoint.md
- docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md
- docs/sp-add-ins/context-token-oauth-flow-for-sharepoint-add-ins.md
- docs/sp-add-ins/create-a-sharepoint-add-in-that-contains-a-document-template-and-a-task-pane-add.md
- docs/sp-add-ins/create-provider-hosted-sharepoint-add-ins-to-access-sap-data-by-using-the-sap-ga.md
- docs/sp-add-ins/handle-security-tokens-in-provider-hosted-low-trust-sharepoint-add-ins.md
- docs/sp-add-ins/register-sharepoint-add-ins.md
- docs/sp-add-ins/three-authorization-systems-for-sharepoint-add-ins.md
- docs/spfx/web-parts/guidance/migrate-script-editor-web-part-customizations.md
> Fixing the broken links which are related to dev.office.com.
> Fixing the broken links which are related to dev.office.com

- docs/apis/migration-api-overview.md
Some changes in words while trying to keep changes to the content minimal. Could not understand what is wrong with tables in two places when displayed - "What is stored in those Azure Blob Containers?" & "SPMigrationJobState". Markup seems correct to me.
> There were some grammatical and logical inconsistencies in a few sentences. I have tried to rectify them trying to keep minimal changes. e.g. it said " starts at from no later than", here I have proposed to use "starts no later then..". Added commas after "Additionally" & "Currently" at the start of sentence, added a few "the", and some similar changes.
> Some lexical changes in text

- docs/spfx/web-parts/guidance/validate-web-part-property-values.md
- references #5695
I screwed up the review & merge of PR #5695... this fixes that change. Also fixed lots of markdown formatting issues.
> PR 5695 fixup - update & correct markdown

- docs/sp-add-ins/create-a-sharepoint-add-in-that-contains-a-document-template-and-a-task-pane-add.md
- docs/spfx/web-parts/guidance/migrate-script-editor-web-part-customizations.md
Fix docs build warnings due to locale in URLs
> Fixup url locales

- docs/spfx/debug-modern-pages.md
- references #5385
- updated markdown formatting
- Fixed "spfx" => "SPFx"
- Added additional details on how to disable automatic loading of debug scripts (ref #5385)
> Update SPFx debugging page

- docs/spfx/web-parts/guidance/validate-web-part-property-values.md
Updated promises to async/await pattern for readability.
> Updated promises to async/await

- docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md
- Fix markdown error in the build report
> Fix build error report + clarification

- docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md
> Build report fix md edits

- docs/solution-guidance/modern-experience-site-classification.md
- fixes #https://github.com/SharePoint/sp-dev-docs/issues/5713 & https://github.com/SharePoint/sp-dev-docs/issues/5712
> Add link to "See also" section as a Implement a SharePoint site classification solution https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/implement-a-sharepoint-site-classification-solution
> add the see also link - Update modern-experience-site-classification.md

- docs/spfx/compatibility.md
An initial version of the SPFx compatibility matrix.
> New content: Compatibility Matrix

- docs/solution-guidance/manage-user-sharing-expiration.md
- docs/spfx/use-aadhttpclient-enterpriseapi-multitenant.md
- docs/spfx/use-aadhttpclient-enterpriseapi.md
- docs/toc.yml
Fixes multiple issues reported in recent MSDOCS build report
- missing image
- article missing **.md** extension causing a broken link
- TOC missing **.md** extension causing a broken link
> Build report fixup

- docs/solution-guidance/modern-experience-customizations-customize-pages.md
The original result after disabling the site page feature is confusing. I add a note to clarify it.
> Clarify the effects after disable the site page feature.

- docs/features/hub-site/hub-site-rest-api.md
Changed "site designs and site scripts" to "hub sites"
> Changed wrong text for REST usage description

- docs/solution-guidance/manage-user-sharing-expiration.md
> fix the broken link - Update manage-user-sharing-expiration.md

- docs/solution-guidance/custom-actions-sharepoint-add-in.md
- docs/solution-guidance/delegate-controls-sharepoint-add-in.md
- docs/solution-guidance/document-id-provider-sharepoint-add-in.md
- docs/solution-guidance/feature-stapling-sharepoint-add-in.md
- docs/solution-guidance/localization-sharepoint-add-in.md
- docs/solution-guidance/onedrive-for-business-customization-sharepoint-add-in.md
- docs/solution-guidance/performance-considerations-sharepoint-add-in.md
- docs/solution-guidance/search-api-usage-sharepoint-add-in.md
- docs/solution-guidance/search-configuration-sharepoint-add-in.md
- docs/solution-guidance/template-for-sharepoint-add-in.md
- docs/solution-guidance/user profile manipulation-sharepoint-add-in.md
- docs/solution-guidance/user-controls-and-web-controls-sharepoint-add-in.md
- docs/solution-guidance/variations-sharepoint-add-in.md
- docs/solution-guidance/web-part-sharepoint-add-in.md
- docs/solution-guidance/workflows-actions-events-and-forms-sharepoint-add-in.md
- docs/solution-guidance/yammer-integration-sharepoint-add-in.md
> Updated the new Microsoft 365  PnP link to https://aka.ms/sppnp.
> Updated the new Microsoft 365 PnP link to https://aka.ms/sppnp

- docs/general-development/color-palettes-and-fonts-in-sharepoint.md
- docs/general-development/how-to-create-a-master-page-preview-file-in-sharepoint.md
- docs/general-development/how-to-make-custom-css-files-themable-in-sharepoint.md
- docs/general-development/themes-overview-for-sharepoint.md
- docs/general-development/upgrade-custom-themes-and-css-to-sharepoint.md
- docs/solution-guidance/modern-experience-customizations-customize-pages.md
> Fix the broken links 
> **Note - unfortunately, localization is not working property for these links and these links are working only with en-US so these links include the 'en-us'.**.
@VesaJuvonen  - Resubmitted the PR - https://github.com/SharePoint/sp-dev-docs/pull/5749#event-3350994436
> Fix the broken links

- docs/toc.yml
- fixes #5792
moved throttling doc in TOC out of **Archive** => adjacent to other throttling doc
> Move throttling doc in toc

- docs/declarative-customization/list-form-conditional-show-hide.md
- docs/toc.yml
Updated TOC file and the documentation for show or hide columns in a list form.
> Updated docs for show or hide columns in a form

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- included message issues & PRs will be tagged & autoclosed as incomplete if they ignore the provided sections
> Update issue & PR templates

- docs/spfx/tenant-properties.md
- includes/snippets/open-source/pnp-o365cli.md
- includes/snippets/open-source/pnp-powershell.md
- converted doc to use tabbed examples instead of long-form display for different options
> refresh tenant properties readability

- docs/general-development/site-collection-app-catalog.md
- fixes #5836 _(PR merged before noticing build error)_
Removes locale from URL reported as error in build report.
> remove locale to fix build error

- docs/apis/alm-api-for-spfx-add-ins.md
n/a
- restructure doc for improved readability
- updated commands
> refresh ALM API doc

- docs/declarative-customization/site-design-rest-api.md
- fixes #5852 
Updating the parameters for CreateSiteDesign REST endpoint to match the correct parameter names.
> Updating CreateSiteDesign Parameters

- docs/solution-guidance/how-to-provide-add-in-app-only-tenant-administrative-permissions-in-sharepoint-online.md
Reverts SharePoint/sp-dev-docs#5832
Currently waiting for validation we can upload tenant app-pnly permission .app for SC app catalog before merging this.
> Revert "Adding extra level of detail to avoid ambiguity"

- docs/features/embed-pages-to-teams.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/5870
At the top of the page under the title, Mentioned cloud platform applicability as Office 365
> Mentioned cloud platform applicability

- docs/solution-guidance/modern-experience-customizations-provisioning-sites.md
A typo in the document, changed word `reqeust` to `request`.
> Fixing typo - update document fixing a typo and updated date

- docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md
- fixes #5886
Fix some samples in oauth auth code flow for addins
> #5886 fix some auth code flow samples

- docs/declarative-customization/customize-default-site-design.md
- docs/declarative-customization/site-design-overview.md
- docs/declarative-customization/site-design-rest-api.md
Tested and renamed API samples to proper SharePoint casing.
Fixing SharePoint casing in 3 example files.  I've tested that the API is case-insensitive.
> Renamed API samples to proper SharePoint casing.

- docs/spfx/toolchain/sharepoint-framework-toolchain.md
- fixes n/a
- partially n/a
- mentioned in n/a
Adds information about the new developer section that will be added to package-solution.json in SPFx v1.11
> Adds information about the developer section

- docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md
Add note about manual invocation only from default environment to address a common topic in support cases.
> Add note about manual invocation only from default environment

- docs/features/hub-site/create-hub-site-with-powershell.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/5931
Updated the cmdlet to Register-SPOHubSite instead of Register-PnPHubSite
> Updated cmdlet to Register-SPOHubSite

- docs/business-apps/get-started/set-up-sharepoint-site-lists-libraries.md
- docs/solution-guidance/modern-experience-customizations-provisioning-sites.md
> Correct the Typo

- docs/declarative-customization/list-form-conditional-show-hide.md
Corrected spelling preceeded to preceded
> Corrected spelling

- docs/sp-add-ins/using-csom-for-dotnet-standard.md
- fixes #5953 
Adds a note adding reference to an issue that could cause problems for people running the code sample in Azure Functions.
> Add troubleshooting tip for use with Azure Functions v3

- docs/spfx/set-up-your-development-environment.md
n/a
Make this page more generic with more guidance and remove specific Node version references.
> Remove version links on "Set up your SharePoint Framework development environment"

- docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md
Fixed some minor typos found while reading
> Fixed some minor typos

- docs/business-apps/power-automate/guidance/customize-page-approvals.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/6027
Fixed embed video for Customizing modern page approval workflow using Microsoft Flow
> Fixed embed video

- docs/spfx/release-1.7.1.md
- docs/spfx/release-1.8.1.md
- docs/toc.yml
n/a
- fixes two markdown rendering issues with NPM package references
- adds SPFx v1.8.1 release to TOC
> Fixup markdown rendering issues & update TOC

- docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md
While these gaps do exist, for each one, I've documented useful workarounds.
> Added list of specific functional gaps

- docs/spfx/sharepoint-framework-overview.md
Added missing asterisk
No related issues.
Just a simple fix.
> Update sharepoint-framework-overview.md - Added missing asterisk

- docs/spfx/release-1.11.0.md
- docs/toc.yml
- Updated release notes to match other release notes.
- Added release notes to TOC
> Update SPFx release notes v1.11

- docs/spfx/release-1.11.0.md
Updated v1.11 to v.1.10 in uninstalling statement.
- fixes #6060 
Fixed the typo issue from v1.11 to v1.10 for uninstalling statement.
> Updated the typo error

- docs/transform/modernize-scanner.md
Fixes #6036
- fixes #6036 
Updated typo
> Update Typo in modernization scanner docs

- docs/transform/modernize-scanner.md
Relates to PR https://github.com/pnp/sp-dev-modernization/pull/500 to update it in the code as well
Adding notice that -r / --urls is being ignored if -t / --tenant has been provided
> Updating command line parameter -r

- docs/spfx/dynamic-data.md
N/A
Fixing several textual errors in dynamic-data.md
> Fixing several textual errors in dynamic-data.md

- docs/spfx/publish-to-marketplace-checklist.md
Updated simple grammar mistake from "you" to "your".
> Correct simple grammar mistake

- docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/6054
Updated web part name to "jQuery" instead of " jQuery Web Part".
> Updated web part name

- docs/spfx/set-up-your-development-environment.md
- fixes https://github.com/SharePoint/sp-dev-docs/issues/6100
The word 'if' is changed to 'is' on the SPFX docs page for setting up your environment.
> Grammer correction - SPFX setting up environment.

- docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
> Fix doc typo

- docs/spfx/dynamic-data.md
Fixed JSON snippets in examples section
>  Update JSON snippets in examples

- docs/solution-guidance/modern-experience-customizations-provisioning-sites.md
N/A
Simplified the current _Provision a "modern" team site by using PnP PowerShell_ sample as it was overly complex for what it was trying to do
> Simplifying PnP PowerShell sample

- docs/spfx/web-parts/get-started/office-addins-tutorial.md
- docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md
- docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md
> Correct the Typo - JavaScript
> Correct the Typo - JavaScript

- docs/business-apps/power-automate/get-started/connect-to-other-services-in-your-flow.md
- docs/business-apps/power-automate/get-started/create-your-first-flow.md
- docs/business-apps/power-automate/guidance/customize-page-approvals.md
- docs/business-apps/power-automate/guidance/manage-list-flows.md
- docs/business-apps/power-automate/guidance/manage-list-item-file-permissions.md
- docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md
- docs/business-apps/power-automate/guidance/require-doc-approval.md
- docs/business-apps/power-automate/guidance/working-with-get-items-and-get-files.md
- docs/business-apps/power-automate/guidance/working-with-send-sp-http-request.md
- docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md
- docs/declarative-customization/list-form-conditional-show-hide.md
- docs/index.yml
- docs/solution-guidance/Migrate-InfoPath-forms-to-SharePoint.md
- docs/solution-guidance/configuring-the-pnp-provisioning-engine.md
- docs/solution-guidance/modern-experience-customizations-provisioning-sites.md
- docs/solution-guidance/pnp-provisioning-tenant-templates.md
- docs/spfx/publish-to-marketplace-checklist.md
- docs/spfx/release-1.11.0.md
- docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
- docs/spfx/web-parts/get-started/using-microsoft-graph-apis.md
- docs/spfx/web-parts/guidance/localize-web-parts.md
- docs/toc.yml
Merging latest master branch changes to live branch
> Merging latest master branch changes to live branch

- docs/spfx/extensions/get-started/building-simple-field-customizer.md
Added the questions when prompted the solution, then in this demo it creates a Field Customizer the questions say, What is you Application Cutomizer? the question is wrong because is a Field Customizer
> Update Build first Field Customizer extension.md

- docs/general-development/sharepoint-search-rest-api-overview.md
POST API is case-sensitive. Querytemplate does not work, but QueryTemplate (Capital T) does.
> Fixed casing of QueryTemplate

- docs/declarative-customization/list-form-conditional-show-hide.md
- fixes #6219
Fixed typo in Supported column types
> Fixed typo in Supported column types

- docs/declarative-customization/site-design-o365cli.md
- fixes #6223
Updated links to cli-microsoft365 based on renaming in github.io to "https://pnp.github.io/cli-microsoft365"
> Updated links to cli-microsoft365

- docs/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions.md
- fixes #6227
Added missing Yeoman command in step 3
> Added missing Yeoman command

- docs/apis/migration-api-shared.md
- partially #5891
Fixed invalid XML UserGroup.xml
> Fixed invalid UserGroup.xml

- docs/spfx/web-parts/overview-client-side-web-parts.md
> Remove redundant ')' in the last sentence

- docs/solution-guidance/modern-experience-customizations-customize-sites.md
This document stated that publishing for modern team sites was not supported, however, in this document we say it is supported: https://docs.microsoft.com/en-us/sharepoint/publishing-sites-classic-to-modern-experience
> - Target the `master` branch of this repo. Released documents are in `live` branch.
>
> Support for Publishing on Modern Team Sites

- docs/solution-guidance/provisioning-console-application-sample.md
Added paragraph and code block for ApplyProvisioningTemplate() function implementation
- fixes #6353 
Added paragraph and code block for ApplyProvisioningTemplate() function implementation
Removed unnecessary ConsoleColor defaultForeground, param from calling function
I'm pretty sure this function only applies to an existing site collection so edited article intro text to that effect.
> Added paragraph and code block for ApplyProvisioningTemplate() function implementation

- docs/solution-guidance/search-customizations-for-sharepoint.md
Added disclaimer for classic sites. Also linked to modern search web parts. Updated See Also with modern search web parts.
- fixes #6275 
Updated article to include a link to PnP modern search web parts.
> Added disclaimer for classic sites

- docs/declarative-customization/site-theming/sharepoint-site-theming-json-schema.md
None
- Added the out of the box Teal theme
- Add the accent color to each theme
> Added Teal Theme and Accent Colors

- docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md
None
Added Teal to the list of default themes
> Added Teal to the list of default themes

- docs/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api.md
I have used the code in the section for "Add a sub-folder to a folder (.net)" but got "Server relative urls must start with SPWeb.ServerRelativeUrl" Exception.
I changed the URL and removed the / at the beginning, and the code worked well.
> Removed "/" from line .. ServerRelativeUrl

- docs/spfx/build-for-teams-me-experience.md
Updates links to other resources to properly track traffic
> Updates links to other resources

- docs/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator.md
- docs/spfx/toolchain/sharepoint-framework-toolchain.md
- docs/spfx/tools-and-libraries.md
Refreshed content for the ** SPFx / tools & libraries** section of the docs, including:
- markdown formatting fixes
- fix typos
- correct outdated links
> SPFx refresh of the "tools & libraries" docs section

- docs/solution-guidance/modern-experience-customizations-provisioning-sites.md
- fixes #6386
Updated the URL of MS Graph - Create Group
> Updated URL of MS Graph - Create Group

- docs/spfx/connect-to-sharepoint.md
Fix small typo in spfx/connect-to-sharepoint.md
> Update typo on connect-to-sharepoint.md

- docs/general-development/pagination-for-large-result-sets.md
- docs/general-development/sharepoint-search-rest-api-overview.md
- docs/toc.yml
This PR is from SharePoint FAST search service team, and does not address existing issues
added new article explaining the new approach.
updated the existing doc about startrow limit.
> Pagination approach for large result sets

- docs/sp-add-ins/using-csom-for-dotnet-standard.md
- closes #6404
- removes redundant code
- fixes multiple readability issues to improve acrolynx score
> Update doc accuracy & readability

- docs/declarative-customization/column-formatting.md
- fixes #6405
defaultClick opens file instead of details pane.
> Updated defaultClick behavior

- docs/spfx/toolchain/implement-ci-cd-with-azure-pipelines.md
Azure Multi-Stage pipelines are now generally available
Content changes related to Azure DevOps feature - Multi-Stage pipelines, now generally available.
> Removed the Azure DevOps Multi-Stage "preview" references from the article

- docs/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator.md
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator
> **DELETE THIS LINE BEFORE SUBMITTING** | …
> Typo "**@microsoft/sharepoint**"→"**\@microsoft/sharepoint**"

- docs/general-development/social-feed-rest-api-reference-for-sharepoint.md
https://docs.microsoft.com/en-us/sharepoint/dev/general-development/social-feed-rest-api-reference-for-sharepoint
> **DELETE THIS LINE BEFORE SUBMITTING** | *Please …
> Typo "**@v**"→"**\@v**"

- docs/spfx/release-1.5.md
Bold with escape characters
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.5
> **DELETE THIS LINE BEFORE SUBMITTING** | *Please describe the changes in …
> Typo "**@microsoft/～-sharepoint**"→"**\@microsoft/～-sharepoint**"

- docs/solution-guidance/multigeo-onedrive.md
- closes #6456
Fixes broken link in doc
> fixup broken link

- docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md
- closes #6475
- remove broken links
- update redirect links
> fixup broken links

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
Issue templates were pointing to a playground repo, not the correct repo (this one).
> fix incorrect link in issue templates

- docs/general-development/advanced-scenarios-and-additional-samples.md
- fixes #6491
- one link requires locale as not translated
> fixup markdown & broken link

- docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md
> Remove duplicated word

- docs/declarative-customization/list-form-configuration.md
> Fix 404 links

- docs/solution-guidance/Handle-SharePoint-Online-throttling-by-using-exponential-back-off.md
- fixes #6515
updated broken link
> Update link to prev moved sample

- docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md
Added information on actions and triggers that are supported by the SharePoint Connector for SharePoint On-Prem 2013, 2016, and 2019.
> Add info on supported triggers and actions for SP On-prem

- docs/apis/onenote-migration-service.md
- docs/apis/sharepoint-rest-graph.md
- docs/apis/spod-copy-move-api.md
- docs/scenario-guidance/Enterprise-Content-Management.md
- docs/schema/file-element.md
- docs/schema/list-schema.md
- docs/schema/view-schema.md
- docs/solution-guidance/configuring-the-pnp-provisioning-engine.md
- n/a
- address warnings on the MSDocs build report
> Fixup front matter build errors & markdown formatting

- docs/general-development/debugging-sharepoint-server-workflows.md
- docs/general-development/extend-the-fixed-format-export-feature-in-word-automation-services.md
- docs/general-development/office-and-sharepoint-application-services.md
- docs/general-development/optimize-page-performance-in-sharepoint.md
- docs/general-development/prepare-to-set-up-and-configure-a-sharepoint-workflow-development-environment.md
- docs/general-development/understanding-task-actions-in-sharepoint-designer.md
- docs/general-development/visio-services-in-sharepoint.md
- docs/general-development/workflow-activity-classes-in-sharepoint.md
- docs/schema/elements-element-custom-action.md
- docs/schema/field-types-schema.md
- docs/schema/fieldref-element-contenttype.md
- docs/schema/fieldrefs-element-contenttype.md
- docs/solution-guidance/security-webapppolicies.md
- docs/sp-add-ins/sharepoint-add-ins.md
- fixes n/a
- fixing multiple MSDocs build report errors
> MS docs build error fixes

- docs/general-development/javascript-user-defined-functions-overview.md
To help direct readers to the modern JavaScript solution for Excel custom functions, we should add a note to the top of this article that link to the appropriate place.
A note at the top of the UDF overview article with a link to the JS Custom Functions overview.
> Cross-link to web-based custom functions article

- docs/toc.yml
- closes #6555
- added link to list form config page under
the Forms Configuration TOC node
> Update TOC - add link to forms config

- docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
- closes #6557
- add link to steps on creating an Azure AD application
> Add additional link to doc

- docs/sp-add-ins/using-csom-for-dotnet-standard.md
- closes #6538
- as reported by user, code was resetting previously defined
object, blocking code from working
> Fix overwritten var in snippet

- docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
Fixed link to "GitHub: SharePoint Online Throttling code sample" in "See also" section.
> Fixed link to Throttling code sample on GitHub

- docs/solution-guidance/Handle-SharePoint-Online-throttling-by-using-exponential-back-off.md
Fixed broken link to other article in "See also" section.
> Fixed broken links in article

- docs/declarative-customization/list-form-configuration.md
Fixed typos and improved code formatting in article
> Fixed typos and improved code formatting

- docs/schema/field-element-list.md
Fixed table formatting under "Predefined fields" section.
> fixed table content

- docs/spfx/web-parts/basics/add-an-external-library.md
- fixed #6623
Appears the referenced link has been removed, so we're removing it from the docs.
> update doc to remove broken link

- docs/general-development/sharepoint-vss-writer.md
- docs/general-development/sharepoint-workflow-development-best-practices.md
- docs/transform/modernize-guidance.md
- docs/transform/modernize-partner-guidance.md
- n/a
Correct docs with dupe titles
> Update duped article titles issues

- docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md
- addresses issues with PR #6656
- fix links
- fix markdown
- fix msdocs issues
> Event receiver doc fixup

- docs/declarative-customization/list-form-configuration.md
> Change to steps in document library

- docs/general-development/develop-sharepoint-workflows-using-visual-studio.md
- docs/general-development/get-started-with-workflows-in-sharepoint.md
- docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md
- n/a
- update links to point to redirect targets
- update links to use HTTPS
- markdown fixups
> MSDocs build error fixes

- docs/sp-add-ins/working-with-folders-and-files-with-rest.md
- fixes #6673
There is no mention how to deal with special characters of # and %
> Provides a link how to support % and # characters in files and folders.

- docs/spfx/enable-Microsoft-365-content-delivery-network.md
- fixes #6689
Updated code snippet to Verify the origin with CLI for M365
> Updated code snippet

- docs/declarative-customization/site-design-pnp-provisioning.md
PnP.PowerShell has been released. So the text at the start of the doc is now fixed to reflect that.
> Modified the note at the start of the docs

- docs/spfx/office-ui-fabric-integration.md
- docs/spfx/release-1.8.2.md
n/a
- added details from [this wiki entry](https://github.com/SharePoint/sp-dev-docs/wiki/Safely-using-legacy-Fabric-Styles) to the docs
- added callout to SPFx v1.8.2 release notes
> Migrate CSS change from wiki to docs

- docs/spfx/extensions/basics/tenant-wide-deployment-extensions.md
- closes #6707
Clarifying docs based on user inquiry... add detail on when the **clientsideinstance.xml** file is present.
> clarified doc based on user question

- docs/declarative-customization/site-design-pnp-provisioning.md
- mentioned in #6716
in responding to an issue, noticed a typo in the doc that's fixed by this PR
> update pnp-provisioning version

- docs/solution-guidance/modern-experience-customizations-customize-sites.md
Updated working link for New capabilities in SharePoint Online team sites including integration with Microsoft 365 groups
> Updated link

- docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md
- fixes #6748
Updated description to match up to the URL endpoint of list instead of document.
> Updated description to match URL endpoint

- docs/solution-guidance/pnp-provisioning-engine-and-the-core-library.md
- fixes #6751
Updated module from SharePointPnPPowerShellOnline to PnP.PowerShell
> Updated module from SharePointPnPPowerShellOnline to PnP.PowerShell

- docs/solution-guidance/Introducing-the-PnP-Provisioning-Engine.md
I had some problems following this guide, and after asking a question here (
https://github.com/pnp/powershell/discussions/314) I understand that the commands described in the article has changed names. 
Thought the documentation should be uptated to reflect this so no one else gets stuck on this.
> Updated cmdlets with the new names 

- docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md
- fixes #6770, fixes #6671
Fixed minor typos
> Minor typo fixes

- docs/spfx/set-up-your-developer-tenant.md
Added clarification for GCC High tenants since the URLs are different.
Expansion of content to add clarification for GCC High tenants since the URLs are different.
> Added GCC High clarification.

- docs/spfx/compatibility.md
None
Added SPFx 1.12 to the list
> Added SPFx 1.12

- docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
Update "Overwhelming" section with sync client cause
> Update "Overwhelming" section with sync client ca

- docs/general-development/managed-metadata-and-navigation-in-sharepoint.md
- fixes #6827
Corrected code snippet
> Corrected code snippet

- docs/sp-add-ins/context-token-oauth-flow-for-sharepoint-add-ins.md
> clarify confusing grammer

- docs/declarative-customization/site-design-pnp-provisioning.md
Azure function script fails to connect. The Connect-PnPOnline cmdlet is missing the -Tenant parameter. Example has been updated to include a placeholder for the -Tenant parameter
> Azure function script example fix

- docs/spfx/roadmap.md
- n/a
Refresh SPFx roadmap to match post SPFx v1.12 release
> update spfx roadmap (post spfx v1.12

- docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md
- fixes #6866
- prev link pointed to retired page
- updated link to point to repalcement page
> Change link to MSTeams deployment options

- docs/spfx/release-1.12.0.md
- docs/spfx/set-up-your-development-environment.md
- docs/toc.yml
- fixes #6868
- revert changes to "set up dev env for spfx" to focus on SPFx v1.11
> Revert guidance to focus on SPFx v1.11

- docs/spfx/developer-preview-beta-features.md
- docs/spfx/release-1.12.1.md
- docs/toc.yml
- includes/snippets/spfx-release-candidate.md
n/a
New & updated docs to address support for SPFx preview releases.
> Spfx v1.12.1 release

- .github/ISSUE_TEMPLATE/bug-report.yml
- n/a 
Quick patch to malformed issue template form
> (repo) fix - error in issue template

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/question.yml
> fix - malformed issue template 

- docs/solution-guidance/query-sharepoint-change-log-with-changequery-and-changeToken.md
- fixes #6920
Updated Links for below:
Core.ListItemChangeMonitor
Office 365 Developer patterns and practices
> Updated Links

- docs/declarative-customization/list-form-conditional-show-hide.md
Updated "Unsupported column types" based on recent pull request https://github.com/SharePoint/sp-dev-docs/pull/6921
> Updated "Unsupported column types"

- docs/declarative-customization/view-formatting.md
- fixes #6978 
Remove unnecessary padding.
> Updated view-formatting.md

- docs/spfx/compatibility.md
Changed from small case of Sharepoint to SharePoint.
Changes small case of "p" in SharePoint
> Changes to case of SharePoint word

- docs/spfx/web-parts/guidance/build-client-side-web-parts-with-angular-1-x.md
Replaced Anuglar with Angular.
> Fixed minor typo

- docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md
New note to clarify that the Create File action for SharePoint Server does not support chunked file upload.
> Add note about no support for chunked upload in SharePoint Server

- docs/index.yml
Replace 'developmer' with 'developer' in title
> Fix small typo

- docs/declarative-customization/view-formatting.md
Fixes #7044
- fixes #7044 
Updated reference link to formatter tool.
> Updating link to property column formatting tool.

- docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md
Keeping up to date with https://docs.microsoft.com/en-us/connectors/sharepointonline/#triggers
adding 3 lines to one markdown file
> Adding the newest trigger

- docs/spfx/web-parts/single-part-app-pages.md
- fixes #7089
Updated link for CLI for Microsoft 365 documentation and code for CLI for Microsoft 365
> Updated link and code for CLI for Microsoft 365

- docs/spfx/use-microsoft-graph-toolkit.md
- docs/spfx/web-parts/get-started/build-web-part-microsoft-graph-toolkit.md
- docs/toc.yml
N/A
- new article explaining what is MGT and why you'd use it in SPFx
- tutorial showing how to build a web part that uses MGT
> Adds information about using MGT in SPFx

- docs/declarative-customization/column-formatting.md
- fixes #7087
Corrected "Formatter Tool helper" hyperlink
> Corrected "Formatter Tool helper" hyperlink

- docs/spfx/extensions/get-started/building-simple-field-customizer.md
- fixes #7093
Corrected typo 'ClientSiteComponentId' to 'ClientSideComponentId'
> Corrected typo 'ClientSiteComponentId'

- docs/sp-add-ins/add-a-workflow-to-a-sharepoint-hosted-sharepoint-add-in.md
Add a note regarding Workflow templates being removed from SharePoint Add-ins in Visual Studio 2022
> Added a note regarding Workflow Item Templates

- docs/spfx/compatibility.md
> fix broken links

- docs/spfx/set-up-your-development-environment.md
- docs/spfx/sharepoint-2016-support.md
- docs/spfx/sharepoint-2019-support.md
> Update docs for SPFx & onprem deployments

- docs/spfx/web-parts/get-started/connect-to-sharepoint.md
> add additional note to avoid confusion

- docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
> update hello world web part docs

- docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md
> correct statment on max cert expiry date

- docs/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries.md
> Add note about limitation with sp2016 & preconf entries

- docs/general-development/how-to-make-custom-css-files-themable-in-sharepoint.md
- docs/general-development/how-to-resolve-errors-and-warnings-when-previewing-a-page-in-sharepoint.md
- docs/general-development/how-to-store-and-retrieve-sharepoint-list-items-on-a-windows-phone.md
- docs/scenario-guidance/Long-running-scheduled-operations.md
- docs/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in.md
- docs/sp-add-ins/include-a-web-part-in-a-webpage-on-the-add-in-web.md
- docs/transform/modernize-blogs.md
- fixes multiple msdocs validation issues
> [[WIP]] Fixup msdocs rules

- docs/declarative-customization/get-started-create-site-design.md
Updated "Get started creating site designs and site scripts" article with few fixes & improved formatting.
> Updated "Get started creating site designs and site scripts"

- docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md
- closes #6848
PR referenced above had merge conflicts... this resolves those and closes that PR
> Fix merge conflicts with existing PR

- docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md
- closes #7122
add caution note about unsupported upload of multiple files
> add caution note about unsupported upload of multiple files

- docs/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator.md
- fixes #7136
- removed the output from the generator
- rely on the latest generator to output usage via `--help` argument
> update to make docs less "point-in-time"

- docs/spfx/deployment-spfx-teams-solutions.md
- fixes #7146
fix incorrect path to teams package
> fix incorrect path to teams package

- docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md
> added arg definitions to substringof and starts with

- docs/spfx/release-1.13.md
Updated "SharePoint Framework v1.13 release notes" article with few content fixes.
> Updated "SharePoint Framework v1.13 release notes"

- docs/spfx/viva/overview-viva-connections.md
Updated "Overview of Viva Connections Extensibility" article with few content fixes.
> Updated "Overview of Viva Connections Extensibility"

- docs/declarative-customization/get-started-create-site-design.md
- fixes #7201
Added the corresponding REST API call for Invoke-SPOSiteDesign, for applying a site design to an existing site collection. This is inline with the rest of article, which provides corresponding REST API calls for each step.
> Added corresponding REST API call for Invoke-SPOSiteDesign

- docs/solution-guidance/portal-rollout.md
> Fixing broken picture

- docs/spfx/viva/get-started/build-first-sharepoint-adaptive-card-extension.md
Wanted to do a typo fix, but it seemed it was already fixed. Still wanted to push the changes I did while reading the content.
> **DELETE THIS LINE BEFORE SUBMITTING** …
> Just a couple of small improvements

- docs/declarative-customization/customize-default-site-design.md
- docs/declarative-customization/get-started-create-site-design.md
- docs/declarative-customization/site-design-overview.md
- Minor edits to template flow
-
> Hokavian site template edits

- docs/apis/site-creation-rest.md
fixes https://github.com/SharePoint/sp-dev-docs/issues/7175
> site-creation-rest.md: fix case of "siteUrl" parameter for delete site operation

- docs/spfx/release-0.0.0.md.template
- docs/spfx/release-1.0.0.md
- docs/spfx/release-1.1.md
- docs/spfx/release-1.10.0.md
- docs/spfx/release-1.11.0.md
- docs/spfx/release-1.12.1.md
- docs/spfx/release-1.13.md
- docs/spfx/release-1.3.md
- docs/spfx/release-1.4.1.md
- docs/spfx/release-1.4.md
- docs/spfx/release-1.5.1.md
- docs/spfx/release-1.5.md
- docs/spfx/release-1.6.md
- docs/spfx/release-1.7.1.md
- docs/spfx/release-1.7.md
- docs/spfx/release-1.8.0.md
- docs/spfx/release-1.8.1.md
- docs/spfx/release-1.8.2.md
- docs/spfx/release-1.9.1.md
- docs/spfx/sharepoint-framework-overview.md
- docs/spfx/sharepoint-framework-why.md
- docs/spfx/spfx-sharepoint-online.md
- docs/spfx/supported-extensibility-platforms-overview.md
- docs/spfx/viva/get-started/build-first-sharepoint-adaptive-card-extension.md
- docs/spfx/viva/overview-viva-connections.md
- docs/toc.yml
- includes/snippets/spfx-release-notes-common.md
- includes/snippets/spfx-release-upgrade-tip.md
- n/a
- refresh TOC
- bump viva connections up
- refresh SPFx overview
- refactor "why" => own page is more of a history
- add "where is SPFx supported" with a new section, docs & reference on overview page
- refresh viva connections overview
- remove special install instructions already covered by release notes
- add additional information to highlight SPFx is _THE_ customization story for desktop/dashboard/mobile viva connections
- refresh release notes
- remove dupe instructions
- add global instructions to refer to common install instructions for each release notes page
- markdown formatting cleanup
> Refresh SPFx & Viva Connections overviews + related docs

- docs/declarative-customization/column-formatting.md
Removed the Note for Location columns about Format this Column not being available since this is no longer accurate
> Removed Location Column format Note

- docs/spfx/deployment-spfx-teams-solutions.md
Fix to the path of the TeamsSPFxApp.zip to be included in the sppkg file.
> Fix to folder path

- docs/spfx/viva/get-started/build-first-sharepoint-adaptive-card-extension.md
Added the semicolon on the statement to resolve the missing semicolon warning.
> Resolved missing semicolon code warning

- docs/spfx/release-1.12.0.md
- fixes #7360
Updated the usage version to v1.12.1
> Updated usage version

- docs/declarative-customization/site-design-overview.md
Fixed typo from "useing" to "using"
Fixed typo from "useing" to "using"
> Fixed typo from "useing" to "using"

- docs/declarative-customization/get-started-create-site-design.md
a) Fixed typo from "WebTemplate1" to "WebTemplate"
b) Removed extra space
> Fixed typo and indentation

- docs/declarative-customization/customize-default-site-design.md
a) Fixed typo from "WebTemplate 1" to "WebTemplate"
> Fixed typo from "WebTemplate 1" to "WebTemplate"

- docs/declarative-customization/column-formatting.md
- docs/declarative-customization/view-formatting.md
- None
- Support `indexOf` and `lastIndexOf` for Arrays
- Support `fillHorizontal` for tiles
- Support `p` tag
- Allow SVG style attributes
- Allow `dragable` attribute
- Support `AverageRating` column
- Support `Likes` column
- Allow `tel:` protocol
- Support `getUserImage` operator
> Column and View formatting documentation update

- docs/schema/field-element-list.md
- fixes #7389
In the definition example added missing line breaks for more readability.
> Added line breaks to the example

- docs/apis/webhooks/sharepoint-webhooks-using-azure-functions.md
Fixed document and added "to" in the statement.
> Fixed document with meaningful grammer

- docs/spfx/release-1.12.0.md
- fixes #7411
Link corrected to SPFx v1.12.1
> Link corrected to v1.12.1

- docs/solution-guidance/multigeo-userprofileexperience.md
- fixes #7425
Updated link to MultiGeo.UserProfileUpdates code sample
> Update incorrect link to MultiGeo.UserProfileUpdates sample

- docs/solution-guidance/query-sharepoint-change-log-with-changequery-and-changeToken.md
- fixes #7469
Corrected spelling mistake on the description for more reading
> Corrected the description

- docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md
Adding link for SPO to Site Templates and Site Scripts
Fixes #7492
- fixes #7492 
Added new documentation link
> Adding link to modern Site Templates documentation

- docs/declarative-customization/formatting-advanced.md
Added steps for makers to grab the ID of solution-aware flows so that these types of instant flows can also be run from a column-formatted button in lists.
> Add steps to get flow ID for solution-aware flows

- docs/spfx/compatibility.md
None
Added SPFx 1.13.1 to the compatibility matrix.
> Updated SPFx matrix to include 1.13.1

- docs/spfx/toolchain/extending-webpack-in-build-pipeline.md
Fix file name in the example code.
> Fix file name in the example code

- docs/spfx/extensions/guidance/using-custom-dialogs-with-spfx.md
- fixes -
- partially -
- mentioned in -
This pull request improves the tutorial with informations that allow the developer to have a functioning solution:
1. Added the answer to the question "Components uses external API" in solution creation phase.
2. Added dependencies installation steps (react, react-dom and their types)
3. Added a components folder creation step to best adhear to the react style guides
> Improved CustomDialog tutorial

- docs/spfx/web-parts/single-part-app-pages.md
As of version [0.3.*-nightly](https://github.com/pnp/powershell/blob/master/CHANGELOG.md) of the PnP PowerShell Cmdlets, the `PnPClientSidePage` Cmdlets have been replaced with matching `PnPPage` Cmdelts. This PR changes the old cmdlet to the new one.
> Updated to reflect change in PowerShell cmdlets

- docs/spfx/library-component-tutorial.md
- fixes #7547
precision to link correctly spfx library
> [feat] - precision to link correctly spfx library

- .github/ISSUE_TEMPLATE/bug-report.yml
Fixed a few mistakes in the default bug report template
> Fixing mistakes in bug report template

- docs/declarative-customization/formatting-advanced.md
- fixes #7579
Removed the single quote from code snippet.
> Corrected code typo

- docs/spfx/release-1.12.1.md
- closes #7611
Fix guidance on Gulp installation
> Update gulp install guidance for SPFx v1.12.1

- docs/sp-add-ins/set-up-a-development-environment-for-sharepoint-add-ins-on-office-365.md
This PR updates the branding from Office 365 to Microsoft 365.
> Changed Office 365 to Microsoft 365.

- docs/spfx/yeoman-generator-for-spfx-intro.md
- docs/toc.yml
- n/a
- include docs for retired prompts
- include explanation of project templates
- show default project creation using the latest generator (1.14)
> Add new page for SPFx generator details

- docs/spfx/compatibility.md
Queued up changes for SPFx 1.14 release
> Added SPFx 1.14

- docs/declarative-customization/formatting-syntax-reference.md
- docs/declarative-customization/view-board-formatting.md
- docs/declarative-customization/view-formatting.md
- docs/declarative-customization/view-gallery-formatting.md
- docs/toc.yml
New feature
1. Board view formatting docs
2. New operator - `getThumbnailImage`
> Formatting docs update

- docs/spfx/viva/get-started/advanced-card-view-functionality.md
Adds documentation related to the client-side caching APIs that will be available starting in the `1.14.0.beta.1` release
> Update Card view tutorial with caching documentation

- docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md
Fixes #7740
- fixes #7740 
An update to the build steps to include a gulp bundle before package-solution
> Update Build Steps to include gulp bundle

- docs/declarative-customization/formatting-syntax-reference.md
New feature
1. New elmType - `filepreview`
2. New prop `filePreviewProps`
> Formatting docs update - filepreview

- docs/declarative-customization/view-board-formatting.md
- docs/declarative-customization/view-calendar-formatting.md
- docs/declarative-customization/view-commandbar-formatting.md
- docs/declarative-customization/view-gallery-formatting.md
- docs/declarative-customization/view-list-formatting.md
- docs/toc.yml
New functionality
`commandBarProps` documentation
> Command bar customization documentation

- docs/spfx/image-helper-api.md
- docs/spfx/release-1.14.md
- references #7752
- update 1.14 release notes to reflect this feature is dev preview
- add note in docs indicating it's dev preview
> move image helper API => dev preview

- docs/spfx/roadmap.md
Updated SPFx roadmap to align with latest announced roadmap as per Feb 24 community call slide
> Updated roadmap with latest community call roadmap

- docs/spfx/release-1.15.md
- fix incorrect version upgrade steps
- fix statements about Microsoft Graph API version, which should explicitly mention "JavaScript SDK"
> Clarify SPFx v1.15 release notes

- docs/spfx/release-1.15.md
Updates v1.15 upgrade guidance replacing the generator package name with a placeholder to clarify what developers should do
- n/a
Updates upgrade guidance to SPFx v1.15 replacing the generator's package name with a placeholder to clarify what developers should do to upgrade their projects
> Updates v1.15 upgrade guidance

- docs/spfx/web-parts/overview-client-side-web-parts.md
-[x] Content fix
-[ ] New Article
a) Renamed "Office UI Fabric React" to "Fluent UI"
> Renamed Office UI Fabric React

- docs/declarative-customization/site-design-json-schema.md
Updates to document structure to match schema 💁‍♂️ verb "addContentTypesFromHub" is a root "action" and not a "subaction" of "createSPList"
> Update article structure to match schema

- docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md
a) Removed redundant word "ensure"
> Removed extra word "ensure"

- docs/spfx/web-parts/basics/integrate-with-property-pane.md
a) Fixed typo from "HellowWorld" to "HelloWorld"
> Fixed typo from "HellowWorld" to "HelloWorld"

- docs/apis/syntex/syntex-model-rest-api.md
Fixing the link path in line 58
> [BrokenLinksH2] Fix path in link

- docs/toc.yml
- n/a
- update TOC with new docs & tutorials for GEOLOC capabilities of ACE's recently added to docs
> Update TOC with ACE geolocation docs & tutorials

- docs/design/semantic_slots.md
- docs/spfx/debug-in-vscode.md
- docs/spfx/set-up-your-development-environment.md
- docs/spfx/sharepoint-2016-support.md
- docs/spfx/sharepoint-2019-support.md
- docs/spfx/sharepoint-framework-why.md
- docs/transform/modernize-guidance.md
- closes #7223
- closes #7592
- closes #7791
- closes #7872
- closes #7904
Fix multiple broken links, typos, & add extra links for references
> Fix typos & broken links on multiple page

- docs/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries.md
a) Fixed typo from "targetting" to "targeting"
> Fixed typo from "targetting" to "targeting"

- docs/support-feedback.md
- closes #7979
- replace uservoice with feedback portal
> Fix doc link & text reference

- docs/spfx/sharepoint-2019-support.md
Changed the recommended version number for on-premises projects from 1.10.1 that does not exist to 1.10.0 which is also referenced elsewhere in the article.
> Change recommended on-premises version number

- docs/scenario-guidance/Performance.md
- docs/scenario-guidance/Responding-to-changes.md
> Validation fixes

- docs/apis/migrate-webparts-with-migrationapi.md
- docs/business-apps/power-automate/guidance/manage-list-item-file-permissions.md
- docs/business-apps/power-automate/guidance/working-with-send-sp-http-request.md
- docs/community/social-media.md
- docs/declarative-customization/site-design-pnp-provisioning.md
- docs/declarative-customization/site-theming/sharepoint-site-theming-csom.md
- docs/design/ui-text-for-web-parts.md
- docs/design/web-part-commanding.md
- docs/features/hub-site/REST-sphubsite-type.md
- docs/features/hub-site/REST-sphubsitedata-type.md
- docs/general-development/accessing-a-schema.md
- docs/general-development/accessing-the-soap-api.md
VALIDATION
- no issue number - part of the Validation cleanup efforts.
This PR fixes 29 issues in 12 files.
> Validation: fix multiple errors

- docs/general-development/custom-security-trimming-for-search-in-sharepoint-server.md
- docs/general-development/custom-word-breakers-in-sharepoint-server.md
- docs/general-development/customizing-search-results-in-sharepoint.md
- docs/general-development/debugging-sharepoint-server-workflows.md
- docs/general-development/deciding-between-sharepoint-add-ins-and-sharepoint-solutions.md
- docs/general-development/develop-access-web-apps.md
- docs/general-development/develop-the-site-design-in-sharepoint.md
- docs/general-development/developing-with-duet-enterprise-2-0.md
- docs/general-development/discovery-in-excel-services-rest-api.md
- docs/general-development/ediscovery-in-sharepoint.md
- docs/general-development/enhancing-the-bdc-model-file-for-search-in-sharepoint.md
- docs/general-development/excel-services-alerts.md
- docs/general-development/excel-services-architecture.md
- docs/general-development/excel-services-best-practices.md
- docs/general-development/excel-services-blogs-forums-and-resources.md
- docs/general-development/excel-services-development-roadmap.md
- docs/general-development/excel-services-ecmascript-javascript-jscript.md
- docs/general-development/excel-services-ecmascript-overview.md
- docs/general-development/excel-services-known-issues-and-tips.md
- docs/general-development/excel-services-rest-api-overview.md
- docs/general-development/excel-services-rest-api.md
- docs/general-development/excel-web-access.md
- docs/general-development/excel-web-services.md
- docs/general-development/external-content-types-in-sharepoint.md
- docs/general-development/fast-query-language-fql-syntax-reference.md
- docs/general-development/follow-content-in-sharepoint.md
- docs/general-development/follow-people-in-sharepoint.md
- docs/general-development/following-people-and-content-rest-api-reference-for-sharepoint.md
- docs/general-development/general-guidelines.md
- docs/general-development/get-started-developing-with-social-features-in-sharepoint.md
This PR fixes 33 issues in 30 files.
> Validation: Description-missing and disallowed-html-tag fixes.

- docs/general-development/get-started-with-business-connectivity-services-in-sharepoint.md
- docs/general-development/get-started-with-workflows-in-sharepoint.md
- docs/general-development/getting-familiar-with-visual-designer-for-workflow-in-sharepoint-designer.md
- docs/general-development/getting-ranges-using-atom-feed-and-html-fragment.md
- docs/general-development/getting-started-with-excel-services.md
- docs/general-development/how-to-access-external-data-with-rest-in-sharepoint.md
- docs/general-development/how-to-add-a-device-channel-panel-snippet-in-sharepoint.md
- docs/general-development/how-to-add-a-security-trim-snippet-in-sharepoint.md
- docs/general-development/how-to-add-a-web-part-zone-snippet-in-sharepoint.md
- docs/general-development/how-to-add-an-edit-mode-panel-snippet-in-sharepoint.md
- docs/general-development/how-to-apply-a-master-page-to-a-site-in-sharepoint.md
- docs/general-development/how-to-back-up-and-restore-a-search-service-application-in-sharepoint-using.md
- docs/general-development/how-to-back-up-and-restore-sharepoint-using-a-vss-requestor.md
- docs/general-development/how-to-brand-snippets-by-using-css-in-sharepoint.md
- docs/general-development/how-to-build-and-deploy-workflow-custom-actions.md
- docs/general-development/how-to-build-search-driven-mobile-apps-with-the-navigation-and-event-logging-res.md
- docs/general-development/how-to-change-the-preview-page-in-sharepoint-design-manager.md
- docs/general-development/how-to-configure-msmq-for-sharepoint-workflows.md
- docs/general-development/how-to-convert-an-add-in-scoped-external-content-type-to-tenant-scoped.md
- docs/general-development/how-to-convert-an-html-file-into-a-master-page-in-sharepoint.md
- docs/general-development/how-to-crawl-associated-external-content-types-in-sharepoint.md
- docs/general-development/how-to-create-a-minimal-master-page-in-sharepoint.md
- docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md
- docs/general-development/how-to-create-a-page-layout-in-sharepoint.md
- docs/general-development/how-to-create-a-vss-requestor-for-use-with-sharepoint.md
- docs/general-development/how-to-create-an-add-in-scoped-external-content-type-in-sharepoint.md
- docs/general-development/how-to-create-an-external-list-using-an-odata-data-source-in-sharepoint.md
- docs/general-development/how-to-create-report-editors-for-performancepoint-services-in-sharepoint.md
- docs/general-development/how-to-create-sharepoint-workflows-using-visual-studio.md
- docs/general-development/how-to-customize-page-layouts-for-a-catalog-based-site-in-sharepoint.md
This PR fixes 42 issues in 30 files.
> Validation: description-missing, disallowed-html-tag, docs-link-absolute, and image-alt-text-duplicated fixes.

- docs/schema/assemblyredirect-element-workflowinfo.md
- docs/schema/assemblyredirects-element-workflowinfo-elementaction4.md
- docs/schema/assemblyredirects-element-workflowinfo.md
- docs/schema/assignment-element-deploymentmanifest.md
- docs/schema/association-element-in-associations-subscription-schema.md
- docs/schema/association-element-in-methodinstances-bdcmetadata-schema.md
- docs/schema/association-element-in-methodinstances-bdcmetadataresource-schema.md
- docs/schema/association-element-workflowconfig.md
- docs/schema/association-element.md
- docs/schema/associationcategories-element-workflow.md
- docs/schema/associationdata-element-workflow.md
- docs/schema/associationgroup-element-in-associationgroups-bdcmetadata-schema.md
- docs/schema/associationgroup-element-in-associationgroups-bdcmetadataresource-schema.md
- docs/schema/associationgroups-element-in-entity-bdcmetadata-schema.md
- docs/schema/associationgroups-element-in-entity-bdcmetadataresource-schema.md
- docs/schema/associationreference-element-in-associationgroup-bdcmetadata-schema.md
- docs/schema/associations-element-in-subscription-subscription-schema.md
- docs/schema/associations-element.md
This pull request fixes 42 issues across 18 files.
> BULK VALIDATION misc fixes

- docs/schema/attachment-element-deploymentmanifest.md
- docs/schema/attachments-element-deploymentmanifest.md
- docs/schema/authenticationdata-complextype-sps15xsdsearchset2.md
- docs/schema/authenticationdata-element-sps15xsdsearchset2.md
- docs/schema/authenticationinformation-complextype-sps15xsdsearchset2.md
- docs/schema/authenticationinformation-element-sps15xsdsearchset2.md
- docs/schema/authenticationtype-element-authenticationinformation-complextypesps15xsdsearchse.md
- docs/schema/authinfo-element-source-complextypesps15xsdsearchset1.md
- docs/schema/autodeployedwebapplication-element-appprincipaldefinition-complextypesharepoint.md
- docs/schema/autodeployedwebapplicationdebuginfoappurldefinition-simpletype-sharepoint-add-in.md
- docs/schema/autodeployedwebapplicationdebuginfodefinition-complextype-sharepoint-add-in-mani.md
- docs/schema/baseinfo-complextype-sps15xsdsearchset2.md
- docs/schema/baseinfo-element-sps15xsdsearchset2.md
- docs/schema/baseinfocollectionofaliasinfotzwwwpjw-complextype-sps15xsdsearchset2.md
- docs/schema/baseinfocollectionofaliasinfotzwwwpjw-element-sps15xsdsearchset2.md
- docs/schema/baseinfocollectionofcrawledpropertyinfotzwwwpjw-complextype-sps15xsdsearchset2.md
- docs/schema/baseinfocollectionofcrawledpropertyinfotzwwwpjw-element-sps15xsdsearchset2.md
- docs/schema/baseinfocollectionofmanagedpropertyinfotzwwwpjw-complextype-sps15xsdsearchset2.md
- docs/schema/baseinfocollectionofmanagedpropertyinfotzwwwpjw-element-sps15xsdsearchset2.md
- docs/schema/baseinfocollectionofmappinginfotzwwwpjw-complextype-sps15xsdsearchset2.md
- docs/schema/baseinfocollectionofmappinginfotzwwwpjw-element-sps15xsdsearchset2.md
- docs/schema/baseinfocollectionofoverrideinfotzwwwpjw-complextype-sps15xsdsearchset2.md
- docs/schema/baseinfocollectionofoverrideinfotzwwwpjw-element-sps15xsdsearchset2.md
This pull request fixes 44 issues across 23 files.
> BULK VALIDATION various fixes

- docs/schema/manifestfiles-element-deploymentsystemdata.md
- docs/schema/manifesturi-simpletype-sharepoint-add-in-manifest.md
- docs/schema/mapfile-element-feature.md
- docs/schema/mappedcrawledproperties-element-managedpropertyinfo-complextypesps15xsdsearchset.md
- docs/schema/mappedmanagedproperties-element-crawledpropertyinfo-complextypesps15xsdsearchset.md
- docs/schema/mappingdisallowed-element-managedpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/mappinginfo-complextype-sps15xsdsearchset2.md
- docs/schema/mappinginfo-element-sps15xsdsearchset2.md
- docs/schema/mappinginfocollection-complextype-sps15xsdsearchset2.md
- docs/schema/mappinginfocollection-element-sps15xsdsearchset2.md
- docs/schema/mappingorder-element-mappinginfo-complextypesps15xsdsearchset2.md
- docs/schema/mappings-element-searchschemaconfigurationsettings-complextypesps15xsdsearchset3.md
- docs/schema/mappingsoverridden-element-overrideinfo-complextypesps15xsdsearchset2.md
- docs/schema/maptocontenttype-element-view.md
- docs/schema/matchingoptions-element-sps15xsdsearchset4.md
- docs/schema/matchingoptions-simpletype-sps15xsdsearchset4.md
This PR fixes 29 issues across 16 files.
> [Bulk] Validation: validation fixes JM 6/8c

- docs/schema/hashtablesource-element-workflowinfo.md
- docs/schema/hasmultiplevalues-element-managedpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/haspermissiontoreadauthinfo-element-source-complextypesps15xsdsearchset1.md
- docs/schema/hidecustomaction-element.md
- docs/schema/id-element-apppartconfigdefinition-complextypeapppartconfigdefinition.md
- docs/schema/id-element-resultitemtype-complextypesps15xsdsearchset2.md
- docs/schema/id-element-source-complextypesps15xsdsearchset1.md
- docs/schema/id-element-view.md
- docs/schema/identifier-element-in-identifiers-bdcmetadata-schema.md
- docs/schema/identifier-element-in-identifiers-bdcmetadataresource-schema.md
- docs/schema/identifiers-element-in-entity-bdcmetadata-schema.md
- docs/schema/identifiers-element-in-entity-bdcmetadataresource-schema.md
- docs/schema/identities-element-in-subscription-subscription-schema.md
- docs/schema/identity-element-in-identities-subscription-schema.md
- docs/schema/immediatenotificationexcludedfields-element-alerttemplates.md
- docs/schema/indexoffset-element-source-complextypesps15xsdsearchset1.md
- docs/schema/indexoptions-element-managedpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/initiation-element-workflowconfig.md
- docs/schema/initiationcategories-element-workflow.md
- docs/schema/initiationtype-element-workflow.md
- docs/schema/inserttable-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
- docs/schema/installedeventendpoint-element-propertiesdefinition-complextypesharepoint-add-in.md
- docs/schema/internal-element-appprincipaldefinition-complextypesharepoint-add-in-manifest.md
- docs/schema/internalid-element-resultitemtype-complextypesps15xsdsearchset2.md
- docs/schema/interpretation-element-in-typedescriptor-bdcmetadata-schema.md
This pull request fixes 52 issues across 25 files.
> BULK VALIDATION issue fixes

- docs/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2.md
- docs/schema/builtin-element-source-complextypesps15xsdsearchset1.md
- docs/schema/business-connectivity-services-bcs-schemas.md
- docs/schema/button-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
- docs/schema/calendarviewstyles-element-deploymentmanifestspview.md
- docs/schema/calendarviewstyles-element-deploymentmanifestspwebpart.md
- docs/schema/categories-element-workflow.md
- docs/schema/categoriesandcrawledproperties-element-searchschemaconfigurationsettings-complex.md
- docs/schema/categoryname-element-crawledpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/checkbox-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
- docs/schema/children-element-in-container-layoutdefinitions-schema.md
- docs/schema/class-element-event.md
- docs/schema/client-web-part-definition-schema.md
- docs/schema/clientwebpart-element-elementdefinitioncollection-complextypeapphostwebfeatures.md
- docs/schema/clientwebpartdefinitioncontent-complextype-apphostwebfeatures.md
- docs/schema/clientwebpartdefinitioncontenttype-simpletype-apphostwebfeatures.md
- docs/schema/clientwebpartenumitem-complextype-apphostwebfeatures.md
This PR fixes 31 issues across 17 files.
> [Bulk] Validation: validation fixes JM 6/7b

- docs/schema/filter-element-event.md
- docs/schema/filter-element-list.md
- docs/schema/filtervalue-element-in-filtervalues-subscription-schema.md
- docs/schema/filtervalues-element-in-association-subscription-schema.md
- docs/schema/filtervalues-element-in-query-subscription-schema.md
- docs/schema/flow-element-flows-elementworkflowinfo-elementaction4.md
- docs/schema/flows-element-workflowinfo-elementaction4.md
- docs/schema/flyoutanchor-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
- docs/schema/folder-element-contenttype.md
- docs/schema/folder-element-deploymentmanifest.md
- docs/schema/folderviewdefinition-element.md
- docs/schema/foreach-element-view.md
- docs/schema/form-element-deploymentmanifest.md
- docs/schema/formats-element-deploymentmanifestspview.md
- docs/schema/formats-element-deploymentmanifestspwebpart.md
- docs/schema/formregion-element.md
- docs/schema/formregions-element.md
- docs/schema/formsauthcredentials-complextype-sps15xsdsearchset2.md
- docs/schema/formsauthcredentials-element-sps15xsdsearchset2.md
This PR fixes 30 issues across 19 files.
> [Bulk] Validation: validation fixes JM 6/8b

- docs/schema/feature-element-feature.md
- docs/schema/feature-element-featuretemplatereferences-complextypeapphostwebfeatures.md
- docs/schema/feature-site-template-associations.md
- docs/schema/feature-xml-files.md
- docs/schema/featurepropertydefinition-complextype-apphostwebfeatures.md
- docs/schema/featurepropertydefinitions-complextype-apphostwebfeatures.md
- docs/schema/featurescope-simpletype-apphostwebfeatures.md
- docs/schema/featuresitetemplateassociation-element-featuresitetemplateassociation.md
- docs/schema/featuretemplatereference-complextype-apphostwebfeatures.md
- docs/schema/featuretemplatereferences-complextype-apphostwebfeatures.md
- docs/schema/featureversion-simpletype-apphostwebfeatures.md
- docs/schema/federationauthtype-element-sps15xsdsearchset2.md
- docs/schema/federationauthtype-simpletype-sps15xsdsearchset2.md
- docs/schema/field-definitions.md
- docs/schema/field-element-deploymentmanifestdeploymentfieldtemplate.md
- docs/schema/field-element-deploymentmanifestfielddatacollection.md
- docs/schema/field-element-deploymentmanifestspfieldcollection.md
- docs/schema/fieldbind-element-ruledesignertype-complextypeaction4.md
- docs/schema/fieldbind-element-workflowactions.md
- docs/schema/fieldbind-element-workflowinfo.md
This PR fixes 94 issues across 20 files.
> Validation: Fix multiple issues

- docs/schema/keywordinclusion-element-sps15xsdsearchset5.md
- docs/schema/keywordinclusion-simpletype-sps15xsdsearchset5.md
- docs/schema/label-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
- docs/schema/lastitemname-element-baseinfocollectionofaliasinfotzwwwpjw-complextypesps15xsdse.md
- docs/schema/lastitemname-element-baseinfocollectionofcrawledpropertyinfotzwwwpjw-complextype.md
- docs/schema/lastitemname-element-baseinfocollectionofmanagedpropertyinfotzwwwpjw-complextype.md
- docs/schema/lastitemname-element-baseinfocollectionofmappinginfotzwwwpjw-complextypesps15xsd.md
- docs/schema/lastitemname-element-baseinfocollectionofoverrideinfotzwwwpjw-complextypesps15xs.md
- docs/schema/lastmodifieddate-element-resultitemtype-complextypesps15xsdsearchset2.md
- docs/schema/lastmodifieddate-element-source-complextypesps15xsdsearchset1.md
- docs/schema/layout-element-in-layouts-solutionmanifestdeclarativeextensions-schema.md
- docs/schema/layoutdefinitions-schema.md
- docs/schema/layouts-element-in-declarativecontextdefinition-solutionmanifestdeclarativeexten.md
- docs/schema/length-element-view.md
- docs/schema/licensetype-element-sps15xsdsearchset4.md
- docs/schema/licensetype-simpletype-sps15xsdsearchset4.md
This PR fixes 100 issues across 16 files.
> Validation: Fix multiple changes 

- docs/schema/matchtype-element-reorderingrule-complextypesps15xsdsearchset5.md
- docs/schema/matchvalue-element-reorderingrule-complextypesps15xsdsearchset5.md
- docs/schema/maximumresponselength-element-source-complextypesps15xsdsearchset1.md
- docs/schema/maxsize-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
- docs/schema/member-element-deploymentusergroupmap.md
- docs/schema/menu-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
- docs/schema/menu-element.md
- docs/schema/menusection-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
- docs/schema/metadata-element-workflow.md
- docs/schema/method-element-in-methods-bdcmetadata-schema.md
- docs/schema/method-element-in-methods-bdcmetadataresource-schema.md
This PR fixes 31 issues across 11 files.
> [Bulk] Validation: validation fixes JM 6/9

- docs/schema/mrusplitbutton-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
- docs/schema/name-element-baseinfo-complextypesps15xsdsearchset2.md
- docs/schema/name-element-event.md
- docs/schema/name-element-propertyruleoperator-complextypesps15xsdsearchset2.md
- docs/schema/name-element-resultitemtype-complextypesps15xsdsearchset2.md
- docs/schema/name-element-source-complextypesps15xsdsearchset1.md
- docs/schema/namedefinition-simpletype-sharepoint-add-in-manifest.md
- docs/schema/namelsid-element-propertyruleoperator-complextypesps15xsdsearchset2.md
- docs/schema/navbarpage-element-module.md
- docs/schema/navbarpage-element-sitenavbar.md
- docs/schema/nestedinitiationfieldnodes-element-schemasource-elementdatasourcetype-complextyp.md
- docs/schema/nestedinitiationfieldnodes-element-workflowactions.md
- docs/schema/nestedinitiationfieldnodes-element-workflowinfo.md
- docs/schema/normalizedatetime-element-in-interpretation-bdcmetadata-schema.md
- docs/schema/obpart-element-in-arrayofobpart-layoutdefinitions-schema.md
- docs/schema/officeitemcustomizations-element-in-contextdefinition-solutionmanifestdefinition.md
- docs/schema/officeitemproperties-element.md
This PR fixes 30 issues across 17 files.
> [Bulk] Validation: validation fixes JM 6/9a

- docs/schema/officeitemproperty-element.md
- docs/schema/optimizeforfrequentuse-element-resultitemtype-complextypesps15xsdsearchset2.md
- docs/schema/option-element-fieldbind-elementruledesignertype-complextypeaction4.md
- docs/schema/option-element-workflowactions.md
- docs/schema/option-element-workflowinfo.md
- docs/schema/other-sharepoint-schemas.md
- docs/schema/outlookfolder-element.md
- docs/schema/outlookitemcustomizations-element.md
- docs/schema/overrideinfo-complextype-sps15xsdsearchset2.md
- docs/schema/overrideinfo-element-sps15xsdsearchset2.md
- docs/schema/overrideinfocollection-complextype-sps15xsdsearchset2.md
- docs/schema/overrideinfocollection-element-sps15xsdsearchset2.md
- docs/schema/overrides-element-searchschemaconfigurationsettings-complextypesps15xsdsearchset.md
- docs/schema/owner-element-resultitemtype-complextypesps15xsdsearchset2.md
- docs/schema/owner-element-source-complextypesps15xsdsearchset1.md
- docs/schema/pagedclientcallbackrowset-element-deploymentmanifestspview.md
- docs/schema/pagedclientcallbackrowset-element-deploymentmanifestspwebpart.md
- docs/schema/pagedrecurrencerowset-element-deploymentmanifestspview.md
- docs/schema/pagedrecurrencerowset-element-deploymentmanifestspwebpart.md
- docs/schema/pagedrowset-element-deploymentmanifestspview.md
- docs/schema/pagedrowset-element-deploymentmanifestspwebpart.md
This PR fixes 30 issues across 21 files.
> [Bulk] Validation: validation fixes JM 6/10

- docs/schema/propertiestype-complextype-action4.md
- docs/schema/property-bag-schema.md
- docs/schema/property-element-apppermissionrequestdefinition-complextypesharepoint-add-in-man.md
- docs/schema/property-element-clientwebpartproperties-complextypeapphostwebfeatures.md
- docs/schema/property-element-delegate-control.md
- docs/schema/property-element-deploymentmanifest.md
- docs/schema/property-element-feature.md
- docs/schema/property-element-featurepropertydefinitions-complextypeapphostwebfeatures.md
- docs/schema/property-element-featuresitetemplateassociation.md
- docs/schema/property-element-in-properties-bdcmetadata-schema.md
- docs/schema/property-element-in-properties-bdcmetadataresource-schema.md
- docs/schema/property-element-in-properties-subscription-schema.md
- docs/schema/property-element-list-instance.md
- docs/schema/property-element-list.md
- docs/schema/property-element-module.md
- docs/schema/property-element-propertiestype-complextypeaction4.md
- docs/schema/property-element-property-bag.md
- docs/schema/property-element-propertybagdefinition-complextypeapphostwebfeatures.md
- docs/schema/propertybag-element-property-bag.md
- docs/schema/propertybagdefinition-complextype-apphostwebfeatures.md
- docs/schema/propertybagparenttypedefinition-simpletype-apphostwebfeatures.md
- docs/schema/propertybagtype-simpletype-apphostwebfeatures.md
- docs/schema/propertyname-element-propertyrule-complextypesps15xsdsearchset2.md
This PR fixes 89 issues across 23 files.
> Validation: Fix multiple changes  

- docs/general-development/add-in-scoped-external-content-types-in-sharepoint.md
**Global effort to fix build validation errors**
Fixes missing description.
> [Bulk] Validation: fix missing description

- docs/schema/propertyoperator-element-propertyrule-complextypesps15xsdsearchset2.md
- docs/schema/propertyrule-complextype-sps15xsdsearchset2.md
- docs/schema/propertyrule-element-arrayofpropertyrule-complextypesps15xsdsearchset2.md
- docs/schema/propertyrule-element-sps15xsdsearchset2.md
- docs/schema/propertyrulecollection-complextype-sps15xsdsearchset2.md
- docs/schema/propertyrulecollection-element-sps15xsdsearchset2.md
- docs/schema/propertyruleoperator-complextype-sps15xsdsearchset2.md
- docs/schema/propertyruleoperator-element-sps15xsdsearchset2.md
- docs/schema/propertyrules-element-propertyrulecollection-complextypesps15xsdsearchset2.md
- docs/schema/propertyvalueattributedefinition-complextype-apphostwebfeatures.md
- docs/schema/propertyvalues-element-propertyrule-complextypesps15xsdsearchset2.md
- docs/schema/propset-element-crawledpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/providerid-element-source-complextypesps15xsdsearchset1.md
- docs/schema/proxy-element-in-lobsystem-bdcmetadata-schema.md
- docs/schema/qat-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
This PR fixes 30 issues across 15 files.
> [Bulk] Validation: validation fixes JM 6/10c

- docs/schema/intervals-element-refinerconfiguration-complextypesps15xsdsearchset2.md
- docs/schema/isdeleted-element-resultitemtype-complextypesps15xsdsearchset2.md
- docs/schema/isfunction-element-propertyruleoperator-complextypesps15xsdsearchset2.md
- docs/schema/ismappedtocontents-element-crawledpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/isnameenum-element-crawledpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/isquoted-element-propertyruleoperator-complextypesps15xsdsearchset2.md
- docs/schema/isreadonly-element-managedpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/joinedbyor-element-propertyruleoperator-complextypesps15xsdsearchset2.md
This pull request fixes 16 issues across 8 files.
> BULK Validation - desc, column headers, ms.date

- docs/schema/remoteendpoints-element-appdefinition-complextypesharepoint-add-in-manifest.md
- docs/schema/remotewebapplication-element-appprincipaldefinition-complextypesharepoint-add-in.md
- docs/schema/removeduplicates-element-managedpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/removefieldref-element-contenttype.md
- docs/schema/reorderingrule-complextype-sps15xsdsearchset5.md
- docs/schema/reorderingrule-element-arrayofreorderingrule-complextypesps15xsdsearchset5.md
- docs/schema/reorderingrule-element-sps15xsdsearchset5.md
- docs/schema/reorderingrulematchtype-element-sps15xsdsearchset5.md
- docs/schema/reorderingrulematchtype-simpletype-sps15xsdsearchset5.md
- docs/schema/representation-element-propertyruleoperator-complextypesps15xsdsearchset2.md
- no issue numbers; changes are part of the Validation cleanup efforts
This PR fixes 29 issues in 10 files.
> Validation: fix multiple issues on multiple files

- docs/schema/action-element-actions-elementworkflowinfo-elementaction4.md
- docs/schema/action-element-in-actions-bdcmetadata-schema.md
- docs/schema/action-element-in-actions-bdcmetadataresource-schema.md
- docs/schema/action-element-workflowactions.md
- docs/schema/actionconditions-element-action-elementactions-elementworkflowinfo-elementaction.md
- docs/schema/actionconditions-element-workflowactions.md
- docs/schema/actionconditions-element-workflowinfo.md
- docs/schema/actionname-element-in-arrayofactions-layoutdefinitions-schema.md
- docs/schema/actionnames-element-in-obpart-layoutdefinitions-schema.md
- docs/schema/actionparameter-element-in-actionparameters-bdcmetadata-schema.md
- docs/schema/actionparameter-element-in-actionparameters-bdcmetadataresource-schema.md
- [] New article
No issue part of validation
This PR fixes 30 issues for 11 files.
> [BULK] Validation: fixes to multiple files 

- docs/schema/document-converter.md
- docs/schema/document-icons-schema.md
- docs/schema/documentconverter-element-document-converter.md
- docs/schema/documentlibrary-element-deploymentmanifest.md
- docs/schema/documenttemplate-element-contenttype.md
- docs/schema/draftvisibilitytype-simple-type-deploymentmanifest.md
- docs/schema/dropdown-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
Fixed missing descriptions in 7 files.
> [Bulk] Validation: fixed issues

- docs/schema/elements-element-contenttype.md
- docs/schema/elements-element-contenttypebinding.md
- docs/schema/elements-element-delegate-control.md
- docs/schema/elements-element-document-converter.md
- docs/schema/elements-element-event.md
- docs/schema/elements-element-featuresitetemplateassociation.md
- docs/schema/elements-element-field.md
- docs/schema/elements-element-list-instance.md
- docs/schema/elements-element-list-template.md
- docs/schema/elements-element-module.md
- docs/schema/elements-element-property-bag.md
- docs/schema/elements-element-workflow.md
- docs/schema/elements-sharepoint-add-in-manifest.md
- docs/schema/elements-web-template.md
- docs/schema/elements-workflow-actions.md
- docs/schema/enabledforscoping-element-managedpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/entities-element-in-contextdefinition-solutionmanifestdefinitions-schema.md
- docs/schema/entities-element-in-lobsystem-bdcmetadata-schema.md
- docs/schema/entities-element-in-lobsystem-bdcmetadataresource-schema.md
- docs/schema/entity-element-in-entities-bdcmetadata-schema.md
- docs/schema/entity-element-in-entities-bdcmetadataresource-schema.md
- docs/schema/entity-element-in-entities-solutionmanifestdefinitions-schema.md
Fixed missing descriptions and various other issues in 22 articles.
> [Bulk] Validation: Fix issues 6/13

- docs/schema/entityextractorbitmap-element-managedpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/enumitem-element-clientwebpartenumitems-complextypeapphostwebfeatures.md
- docs/schema/enumitems-element-clientwebpartproperty-complextypeapphostwebfeatures.md
- docs/schema/evaluation-element-datasourcetype-complextypeaction4.md
- docs/schema/evaluation-element-workflowactions.md
- docs/schema/evaluation-element-workflowinfo.md
- docs/schema/event-element-events-elementworkflowinfo-elementaction4.md
- docs/schema/event-registrations.md
- docs/schema/eventreceiver-element-deploymentmanifest.md
- docs/schema/eventreceivers-element-deploymentmanifestspfile.md
- docs/schema/eventreceivers-element-deploymentmanifestsplist.md
- docs/schema/eventreceivers-element-deploymentmanifestsplistitem.md
- docs/schema/eventreceivers-element-deploymentmanifestspweb.md
- docs/schema/events-element-workflowinfo-elementaction4.md
- docs/schema/exportobjects-element-deploymentexportsettings.md
- docs/schema/exportsettings-element-deploymentexportsettings.md
- docs/schema/expressionparameter-element-in-actionparameterdefinitions-solutionmanifestdeclar.md
- docs/schema/extendedstatuscolumnvalues-element-workflow.md
- docs/schema/extraproperties-element-overrideinfo-complextypesps15xsdsearchset2.md
- docs/schema/feature-element-apphostwebfeatures.md
- docs/schema/feature-element-deploymentmanifest.md
- docs/schema/featureactivationdependencydefinition-complextype-apphostwebfeatures.md
- docs/schema/featureactivationdependencydefinitions-complextype-apphostwebfeatures.md
- docs/schema/featuredefinition-complextype-apphostwebfeatures.md
Fixed issues related to missing descriptions and column headers in 24 files.
> [Bulk] Validation: Fixed issues II 6/13

- docs/schema/type-element-event.md
- docs/schema/type-element-refinerconfiguration-complextypesps15xsdsearchset2.md
- docs/schema/typedefinition-simpletype-sharepoint-add-in-manifest.md
- docs/schema/typedescriptor-element-bdcmetadata-schema.md
- docs/schema/typedescriptor-element-in-parameter-bdcmetadataresource-schema.md
- docs/schema/typedescriptor-element-in-typedescriptors-bdcmetadataresource-schema.md
- docs/schema/typedescriptors-element-in-typedescriptor-bdcmetadata-schema.md
- docs/schema/typedescriptors-element-in-typedescriptor-bdcmetadataresource-schema.md
- docs/schema/types-apphostwebfeatures.md
- docs/schema/types-apppartconfigdefinition.md
- docs/schema/types-sharepoint-add-in-manifest.md
This PR fixes 42 issues across 10 files.
> Validation: Fix multiple issues 

- docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md
- docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md
- docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md
- docs/schema/accesscontrollist-element-bdcmetadata-schema.md
- docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md
- docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md
- docs/schema/actionbody-element-action-elementactions-elementworkflowinfo-elementaction4.md
- docs/schema/actionbody-element-workflowactions.md
- docs/schema/actionbody-element-workflowinfo.md
- [] New article
No issue part of validation
This PR fixes 31 issues for 9 files.
> [BULK] Validation: fixes to multiple files

- docs/spfx/build-for-teams-me-experience.md
> Validation: Removed Absolute Links

- docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md
- docs/spfx/extensions/get-started/query-suggestion-tutorial-building.md
Removed duplicate alt text and removed an absolute link.
> Validation: Removed Duplicate Alt Text and Absolute Link

- docs/schema/sources-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset3.md
- docs/schema/sourcetype-element-events.md
- docs/schema/spbasetype-simple-type-deploymentmanifest.md
- docs/schema/spdeploymentobjecttype-simple-type-deploymentexportsettings.md
- docs/schema/spdeploymentobjecttype-simple-type-deploymentrootobjectmap.md
- docs/schema/spdeploymentobjecttype-simple-type-deploymentsystemdata.md
- docs/schema/spdictionaryentryaccess-simple-type-deploymentmanifest.md
- docs/schema/spdictionaryentryvaluetype-simple-type-deploymentmanifest.md
- docs/schema/spellcheckmode-element-sps15xsdsearchset5.md
- docs/schema/spellcheckmode-simpletype-sps15xsdsearchset5.md
- docs/schema/speventhosttype-simple-type-deploymentmanifest.md
- docs/schema/speventreceivertype-simple-type-deploymentmanifest.md
- docs/schema/spexportmethodtype-simple-type-deploymentexportsettings.md
- docs/schema/spfarmid-element-searchobjectowner-complextypesps15xsdsearchset2.md
- docs/schema/spincludedescendents-simple-type-deploymentexportsettings.md
- docs/schema/spincludesecurity-simple-type-deploymentexportsettings.md
- docs/schema/spincludeversions-simple-type-deploymentexportsettings.md
- docs/schema/spinner-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
- docs/schema/splisttemplatetype-simple-type-deploymentmanifest.md
- docs/schema/splitbutton-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
- docs/schema/spmoderationstatustype-simple-type-deploymentmanifest.md
- docs/schema/spobject-element-deploymentmanifest.md
- docs/schema/spobjects-element-deploymentmanifest.md
- docs/schema/spobjecttype-simple-type-deploymentmanifest.md
- docs/schema/sprequirementobjecttype-simple-type-deploymentrequirements.md
- docs/schema/spsiteid-element-searchobjectowner-complextypesps15xsdsearchset2.md
- docs/schema/spsitesubscriptionid-element-searchobjectowner-complextypesps15xsdsearchset2.md
- docs/schema/spviewscope-simple-type-deploymentmanifest.md
- docs/schema/spwebid-element-searchobjectowner-complextypesps15xsdsearchset2.md
- docs/schema/ssoauthdata-complextype-sps15xsdsearchset2.md
Fix issues related to missing descriptions and column headers.
> [Bulk] Validation: fix issues III 6/13

- docs/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions.md
- docs/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions.md
- docs/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions.md
- docs/spfx/extensions/guidance/migrate-jslink-to-spfx-extensions.md
- docs/spfx/extensions/guidance/migrate-user-customactions-to-spfx-extensions.md
Added missing descriptions and removed absolute links.
> Validation: Added Missing Descriptions

- docs/spfx/web-parts/guidance/supporting-section-backgrounds.md
- docs/spfx/web-parts/guidance/use-existing-javascript-libraries.md
Added Unique alt text to resolve duplicate alt text descriptions.
> Validation: Added Unique Alt Text

- docs/schema/queries-element-in-subscription-subscription-schema.md
- docs/schema/queryable-element-managedpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/queryactionenableonclickthroughoptions-element-sps15xsdsearchset4.md
- docs/schema/queryactionenableonclickthroughoptions-simpletype-sps15xsdsearchset4.md
- docs/schema/queryauthenticationtype-element-sps15xsdsearchset5.md
- docs/schema/queryauthenticationtype-simpletype-sps15xsdsearchset5.md
- docs/schema/right-element-in-accesscontrolentry-bdcmetadataresource-schema.md
- docs/schema/role-element-deploymentmanifest.md
- docs/schema/roleassignment-element-deploymentmanifest.md
- docs/schema/roleassignments-element-deploymentmanifest.md
- docs/schema/roleassignmentx-element-deploymentmanifest.md
- docs/schema/roles-element-deploymentmanifest.md
- docs/schema/rolex-element-deploymentmanifest.md
- docs/schema/rootobject-element-deploymentrootobjectmap.md
- docs/schema/rootobjects-element-deploymentrootobjectmap.md
- docs/schema/row-element-list-instance.md
- docs/schema/row-element-site.md
- docs/schema/rowlimit-element-deploymentmanifestspview.md
- docs/schema/rowlimit-element-deploymentmanifestspwebpart.md
- docs/schema/rowlimitexceeded-element-deploymentmanifestspview.md
- docs/schema/rowlimitexceeded-element-deploymentmanifestspwebpart.md
- docs/schema/rows-element-list-instance.md
This PR fixes 30 issues across 22 files.
> [Bulk] Validation: validation fixes JM 6/14

- docs/schema/ssoauthdata-element-sps15xsdsearchset2.md
- docs/schema/startpage-element-propertiesdefinition-complextypesharepoint-add-in-manifest.md
- docs/schema/statuspageurl-element-workflow.md
- docs/schema/subscription-element-subscription-schema.md
- docs/schema/subscription-schema.md
- docs/schema/supportedlanguages-element-propertiesdefinition-complextypesharepoint-add-in-man.md
- docs/schema/supportedlanguagesdefinition-simpletype-sharepoint-add-in-manifest.md
- docs/schema/supportedlocale-element-supportedlocalesdefinition-complextypesharepoint-add-in.md
- docs/schema/supportedlocaledefinition-complextype-sharepoint-add-in-manifest.md
- docs/schema/supportedlocales-element-propertiesdefinition-complextypesharepoint-add-in-manif.md
- docs/schema/supportedlocalesdefinition-complextype-sharepoint-add-in-manifest.md
- docs/schema/synchronization-element-event.md
- docs/schema/systemdata-element-deploymentsystemdata.md
- docs/schema/systemobject-element-deploymentsystemdata.md
- docs/schema/systemobjects-element-deploymentsystemdata.md
- docs/schema/tab-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
- docs/schema/tabs-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
- docs/schema/template-element-workflowconfig.md
- docs/schema/textbox-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
- docs/schema/textbox-element.md
- docs/schema/title-element-propertiesdefinition-complextypesharepoint-add-in-manifest.md
- docs/schema/titlebar-element-in-obpart-layoutdefinitions-schema.md
- docs/schema/titledefinition-simpletype-sharepoint-add-in-manifest.md
- docs/schema/togglebutton-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
- docs/schema/tokennormalization-element-managedpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/tokennormalization-element-overrideinfo-complextypesps15xsdsearchset2.md
- docs/schema/toolbar-element-deploymentmanifestspview.md
- docs/schema/totalcount-element-managedpropertyinfocollection-complextypesps15xsdsearchset2.md
- docs/schema/truefalse-simple-type-deploymentmanifest.md
**Global effort to fix build validation errors**
Fixed issues related to missing descriptions and column headers.
> [Bulk] Validation: fixed issues 6/14

- docs/schema/ruledesigner-element-action-elementactions-elementworkflowinfo-elementaction4.md
- docs/schema/ruledesigner-element-condition-elementconditions-elementworkflowinfo-elementacti.md
- docs/schema/ruledesigner-element-default-elementconditions-elementworkflowinfo-elementaction.md
- docs/schema/ruledesigner-element-defaultelementtype-complextypeaction4.md
- docs/schema/ruledesigner-element-flow-elementflows-elementworkflowinfo-elementaction4.md
- docs/schema/ruledesigner-element-workflowactions.md
- docs/schema/ruledesigner-element-workflowinfo.md
- docs/schema/ruledesignertype-complextype-action4.md
- docs/schema/rulenamelsid-element-propertyrule-complextypesps15xsdsearchset2.md
- docs/schema/rulepriority-element-resultitemtype-complextypesps15xsdsearchset2.md
- docs/schema/rules-element-resultitemtype-complextypesps15xsdsearchset2.md
- docs/schema/safeforanonymous-element-managedpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/samples-element-crawledpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/scale-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
- docs/schema/scaling-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
- docs/schema/schemaid-element-aliasinfo-complextypesps15xsdsearchset2.md
- docs/schema/schemaid-element-crawledpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/schemaid-element-mappinginfo-complextypesps15xsdsearchset2.md
- docs/schema/schemaid-element-overrideinfo-complextypesps15xsdsearchset2.md
This PR fixes 30 issues across 19 files.
> [Bulk] Validation: validation fixes JM 6/14a

- docs/schema/types-workflow-actions.md
- docs/schema/uiversion-simpletype-apphostwebfeatures.md
- docs/schema/uninstallingeventendpoint-element-propertiesdefinition-complextypesharepoint-add.md
- docs/schema/updategroup-element-managedpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/updatehandlerclassname-element-alerttemplates.md
- docs/schema/upgrade-definition-schema.md
- docs/schema/upgradeactions-element-feature.md
- docs/schema/upgradeactions-element-featuredefinition-complextypeapphostwebfeatures.md
- docs/schema/upgradeactionsdefinition-complextype-apphostwebfeatures.md
- docs/schema/upgradedeventendpoint-element-propertiesdefinition-complextypesharepoint-add-in.md
- docs/schema/urlaction-element-customactiondefinition-complextypeapphostwebfeatures.md
- docs/schema/urlaction-element-in-actions-solutionmanifestdeclarativeextensions-schema.md
- docs/schema/urlaction-element.md
- docs/schema/urlactiondefinition-complextype-apphostwebfeatures.md
This PR fixes 30 issues across 14 files.
> [Bulk] Validation: validation fixes JM 6/14b

- docs/schema/activationdependency-element-featureactivationdependencydefinitions-complextypea.md
- docs/schema/activationdependency-element-solution.md
- docs/schema/active-element-source-complextypesps15xsdsearchset1.md
- docs/schema/activitybody-element-parameter-elementcoercionparameterstype-complextypeaction4.md
- docs/schema/activitysource-element-evaluation-elementdatasourcetype-complextypeaction4.md
- docs/schema/activitysource-element-workflowactions.md
- docs/schema/activitysource-element-workflowinfo.md
- docs/schema/addcontenttypefield-element-feature.md
- docs/schema/aggregations-element-deployment-manifestspview.md
- docs/schema/aggregations-element-deploymentmanifestspwebpart.md
- docs/schema/alertchangetype-element-sps15xsdsearchset5.md
- docs/schema/aliases-element-managedpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/aliases-element-searchschemaconfigurationsettings-complextypesps15xsdsearchset3.md
- docs/schema/aliasesoverridden-element-overrideinfo-complextypesps15xsdsearchset2.md
- docs/schema/aliasinfo-complextype-sps15xsdsearchset2.md
- docs/schema/aliasinfo-element-sps15xsdsearchset2.md
- docs/schema/aliasinfocollection-complextype-sps15xsdsearchset2.md
- docs/schema/aliasinfocollection-element-sps15xsdsearchset2.md
- [] New article
No issue part of validation
This PR fixes 32 issues for 11 files.
> [BULK] Validation: Description, tables and link fixes

- docs/schema/alluserswebpart-element-module.md
- docs/schema/anchoring-element-refinerconfiguration-complextypesps15xsdsearchset2.md
- docs/schema/anonymousstate-simple-type-deploymentmanifest.md
- docs/schema/app-element-sharepoint-add-in-manifest.md
- docs/schema/app_globalresourcefile-element-solution.md
- docs/schema/appdefinition-complextype-sharepoint-add-in-manifest.md
- docs/schema/apphostwebfeatures-schema-reference.md
- docs/schema/appliestotypes-simpletype-action4.md
- docs/schema/applyelementmanifests-element-feature.md
- docs/schema/applyelementmanifests-element-upgradeactionsgroup-groupapphostwebfeatures.md
This PR fixes 15 issues across 10 files.
> Validation: Multiple fixes.

- docs/schema/urlelementdefinition-complextype-sharepoint-add-in-manifest.md
- docs/schema/user-element-deploymentusergroupmap.md
- docs/schema/usergroupmap-element-deploymentusergroupmap.md
- docs/schema/users-element-deploymentusergroupmap.md
- docs/schema/usersegments-element-searchqueryconfigurationsettings-complextypesps15xsdsearchs.md
- docs/schema/userx-element-deploymentmanifest.md
- docs/schema/validation-element-list.md
- docs/schema/variabletype-element-variabletypes-elementworkflowinfo-elementaction4.md
- docs/schema/variabletype-element-workflowinfo.md
- docs/schema/variabletypes-element-workflowinfo-elementaction4.md
- docs/schema/variabletypes-element-workflowinfo.md
- docs/schema/versiondefinition-simpletype-sharepoint-add-in-manifest.md
- docs/schema/versionrange-element-feature.md
- docs/schema/versionrange-element-upgradeactionsdefinition-complextypeapphostwebfeatures.md
- docs/schema/versions-element-deploymentmanifestspfile.md
- docs/schema/versions-element-deploymentmanifestsplistitem.md
- docs/schema/view-body-element-deploymentmanifestspview.md
- docs/schema/view-body-element-deploymentmanifestspwebpart.md
- docs/schema/view-element-deploymentmanifest.md
- docs/schema/view-element-in-entityinstancedefinition-solutionmanifestdefinitions-schema.md
- docs/schema/view-element-module.md
- docs/schema/viewbidiheader-element-deploymentmanifestspview.md
- docs/schema/viewbidiheader-element-deploymentmanifestspwebpart.md
- docs/schema/viewdata-element-deploymentmanifestspview.md
- docs/schema/viewdata-element-deploymentmanifestspwebpart.md
- docs/schema/viewempty-element-deploymentmanifestspview.md
- docs/schema/viewempty-element-deploymentmanifestspwebpart.md
- docs/schema/viewfields-element-deploymentmanifestspview.md
- docs/schema/viewfields-element-deploymentmanifestspwebpart.md
- docs/schema/viewfooter-element-deploymentmanifestspview.md
Fixes related to missing description and column headers in 30 files.
> [Bulk] Validation: fixed issues in 30 files

- docs/schema/schema-map-apphostwebfeatures.md
- docs/schema/schema-map-apppartconfigdefinition.md
- docs/schema/schema-map-sharepoint-add-in-manifest.md
- docs/schema/schema-map-workflow-actions.md
- docs/schema/schema-reference-for-sharepoint.md
- docs/schema/schemasource-element-datasourcetype-complextypeaction4.md
- docs/schema/schemasource-element-workflowactions.md
- docs/schema/schemasource-element-workflowinfo.md
- docs/schema/schemaversion-element-deploymentsystemdata.md
- docs/schema/script-element-deploymentmanifestspview.md
- docs/schema/script-element-deploymentmanifestspwebpart.md
- docs/schema/searchable-element-managedpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/searchconfigurationsettings-complextype-sps15xsdsearchset3.md
- docs/schema/searchconfigurationsettings-element-sps15xsdsearchset3.md
- docs/schema/searchobjectowner-complextype-sps15xsdsearchset2.md
- docs/schema/searchobjectowner-element-sps15xsdsearchset2.md
- docs/schema/searchprovider-element-sps15xsdsearchset5.md
- docs/schema/searchprovider-simpletype-sps15xsdsearchset5.md
- docs/schema/searchqueryconfigurationsettings-complextype-sps15xsdsearchset3.md
- docs/schema/searchqueryconfigurationsettings-element-arrayofsearchqueryconfigurationsettings.md
- docs/schema/searchqueryconfigurationsettings-element-searchconfigurationsettings-complextype.md
- docs/schema/searchqueryconfigurationsettings-element-sps15xsdsearchset3.md
- docs/schema/searchrankingmodelconfigurationsettings-complextype-sps15xsdsearchset3.md
- docs/schema/searchrankingmodelconfigurationsettings-element-searchconfigurationsettings-comp.md
- docs/schema/searchrankingmodelconfigurationsettings-element-sps15xsdsearchset3.md
- docs/schema/searchschemaconfigurationsettings-complextype-sps15xsdsearchset3.md
- docs/schema/searchschemaconfigurationsettings-element-searchconfigurationsettings-complextyp.md
- docs/schema/searchschemaconfigurationsettings-element-sps15xsdsearchset3.md
- docs/schema/securableauthdata-complextype-sps15xsdsearchset2.md
- docs/schema/securableauthdata-element-sps15xsdsearchset2.md
This pull request fixes 49 issues across 30 files.
> BULK VALIDATION description, ms.date, column headers

- docs/schema/appprincipal-element-appdefinition-complextypesharepoint-add-in-manifest.md
- docs/schema/appprincipaldefinition-complextype-sharepoint-add-in-manifest.md
- docs/schema/appprincipaltypedefinition-simpletype-sharepoint-add-in-manifest.md
- docs/schema/arrayofcrawledpropertyinfo-complextype-sps15xsdsearchset2.md
- docs/schema/arrayofcrawledpropertyinfo-element-sps15xsdsearchset2.md
- docs/schema/arrayofmanagedpropertyinfo-complextype-sps15xsdsearchset2.md
- docs/schema/arrayofmanagedpropertyinfo-element-sps15xsdsearchset2.md
- docs/schema/arrayofproperty-element-list.md
- docs/schema/arrayofpropertyrule-complextype-sps15xsdsearchset2.md
- docs/schema/arrayofpropertyrule-element-sps15xsdsearchset2.md
- docs/schema/arrayofreorderingrule-complextype-sps15xsdsearchset5.md
- docs/schema/arrayofreorderingrule-element-sps15xsdsearchset5.md
- docs/schema/arrayofresultitemtype-complextype-sps15xsdsearchset2.md
- docs/schema/arrayofresultitemtype-element-sps15xsdsearchset2.md
- docs/schema/arrayofsearchqueryconfigurationsettings-complextype-sps15xsdsearchset3.md
- docs/schema/arrayofsearchqueryconfigurationsettings-element-sps15xsdsearchset3.md
- docs/schema/arrayofsource-complextype-sps15xsdsearchset1.md
- docs/schema/arrayofsource-element-sps15xsdsearchset1.md
- docs/schema/assembly-element-event.md
- docs/schema/assemblyredirect-element-assemblyredirects-elementworkflowinfo-elementaction4.md
- [] New article
No issue part of validation
This PR fixes 38 issues for 20 files.
> [BULK] Validation: Description, tables fixes

- docs/schema/securitymodificationtype-simple-type-deploymentmanifest.md
- docs/schema/selected-type-definitions.md
- docs/schema/sequencenumber-element-event.md
- docs/schema/serializablesecurablenamevaluepairs-element-securableauthdata-complextypesps15xs.md
- docs/schema/settingspage-element-propertiesdefinition-complextypesharepoint-add-in-manifest.md
- docs/schema/sharepoint-add-in-schemas.md
- docs/schema/sharepoint-features-schemas.md
- docs/schema/similartype-element-sps15xsdsearchset5.md
- docs/schema/similartype-simpletype-sps15xsdsearchset5.md
- docs/schema/simplepropertydefinition-complextype-apphostwebfeatures.md
- docs/schema/site-definition-onet-xml-files.md
- docs/schema/site-deletion-confirmation-schema.md
- docs/schema/site-element-deploymentmanifest.md
- docs/schema/site-schema-elements-a-l.md
- docs/schema/site-schema-elements-m-z.md
- docs/schema/site-schema.md
- docs/schema/solutiondefinition-element-solutionmanifestdefinitions-schema.md
- docs/schema/solutionid-element-event.md
- docs/schema/solutionmanifestdeclarativeextensions-schema.md
- docs/schema/solutionmanifestdefinitions-schema.md
- docs/schema/solutionsettings-element-in-solutiondefinition-solutionmanifestdefinitions-schem.md
- docs/schema/sortable-element-managedpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/sortabletype-element-managedpropertyinfo-complextypesps15xsdsearchset2.md
- docs/schema/sortabletype-element-sps15xsdsearchset2.md
- docs/schema/sortabletype-simpletype-sps15xsdsearchset2.md
The pull request fixes 36 issues across 25 files.
> BULK VALIDATION misc. issue fixes

- docs/schema/elementdefinitioncollection-complextype-apphostwebfeatures.md
- docs/schema/elementfile-element-elementmanifestreferences-complextypeapphostwebfeatures.md
- docs/schema/elementfile-element-feature.md
- docs/schema/elementmanifest-element-elementmanifestreferences-complextypeapphostwebfeatures.md
- docs/schema/elementmanifest-element-feature.md
- docs/schema/elementmanifestreference-complextype-apphostwebfeatures.md
- docs/schema/elementmanifestreferences-complextype-apphostwebfeatures.md
- docs/schema/elementmanifests-element-feature.md
- docs/schema/elementmanifests-element-featuredefinition-complextypeapphostwebfeatures.md
- docs/schema/elements-apphostwebfeatures.md
- docs/schema/elements-apppartconfigdefinition.md
- docs/schema/elements-element-apphostwebfeatures.md
This PR fixes 31 issues across 12 files.
> Validation: Fix descriptions and missing columns

- docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md
- docs/spfx/viva/design/design-intro.md
- docs/spfx/viva/design/designing-card.md
- docs/spfx/viva/design/designing-quick-view.md
- docs/spfx/viva/design/quick-view-samples.md
Added missing alt text, added missing description, and changed duplicate H1.
> Validation: Added Missing Alt Text

- docs/schema/actionparameters-element-in-action-bdcmetadata-schema.md
- docs/schema/actionparameters-element-in-action-bdcmetadataresource-schema.md
- docs/schema/actions-element-in-declarativecontextdefinition-solutionmanifestdeclarativeexten.md
- docs/schema/actions-element-in-entity-bdcmetadata-schema.md
- docs/schema/actions-element-in-entity-bdcmetadataresource-schema.md
- docs/schema/actions-element-workflowinfo-elementaction4.md
- docs/schema/actions-element-workflowinfo.md
- docs/schema/actions-file-example-workflowinfo.md
- docs/schema/actions-schema-reference-workflowinfo.md
- docs/schema/actionvariables-element-action-elementactions-elementworkflowinfo-elementaction4.md
- docs/schema/actionvariables-element-workflowactions.md
- docs/schema/actionvariables-element-workflowinfo.md
- docs/schema/activationdependencies-element-feature.md
- docs/schema/activationdependencies-element-featuredefinition-complextypeapphostwebfeatures.md
- docs/schema/activationdependencies-element-solution.md
- [] New Article
- Build validation fixes - No issue related to this fix
This is a bulk update.
This PR is to fix issues related to build validation messages.
> Validation issues | 1 (BULK) 

- docs/docfx.json
Hello, this content needs to use the Microsoft 365 product-level header. Please let me know if you have any questions.
-Rachel, DevRel Information Architect
P.S., If you're wondering "What is a product-level header?" please see:  https://review.docs.microsoft.com/en-us/help/onboard/admin/navigation-product-level-header?branch=main#what-is-product-level-navigation-for
> **DELETE THIS LINE BEFORE SUBMITTING** | *If this fixes …
> Use Microsoft 365 header

- docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md
- fixes #8286
Update spfx generator prompts to match current
> Update spfx generator prompts to match current

- docs/solution-guidance/Introducing-the-PnP-Provisioning-Engine.md
- fixes #8273
Fixes broken link
> Fix broken link in docs

- docs/solution-guidance/modern-experience-customizations-customize-pages.md
- fixes #8202
Remove broken link & fixup markdown
> Remove broken link & fixup markdown

- docs/spfx/extensions/get-started/building-form-customizer.md
> Fixed typo in <title>

- docs/declarative-customization/site-design-json-schema.md
none known
Adds a TIP to the section about triggering a Flow from a site script.
> Added reference to tutorial for triggering a Flow

- docs/spfx/compatibility.md
- fixes #8352
Added SPFx v1.15.2 compatibility specs to the general SPFx compatibility matrix.
> Adds SPFx version 1.15.2 to SPFx compatibility matrix

- docs/spfx/release-1.15.md
Updated the quick view template json for geolocation and media action types.
> Updated the quick view template json

- docs/spfx/release-1.15.md
- partially #8374
- update formatting for one deprecation to be more user readable
- remove support for node.js v12 (related #8374)
> update spfx 1.15 release notes

- docs/sp-add-ins/working-with-folders-and-files-with-rest.md
- fixes #8377
Corrected code samples to include missing quotes.
> Corrected code samples

- docs/spfx/set-up-your-development-environment.md
- fixes #8386
Corrected cmder url
> Corrected cmder url

- docs/spfx/web-parts/get-started/using-microsoft-graph-apis.md
- fixes #8395
Updated code and fixed Style errors
> Updated code and fixed Style errors

- docs/spfx/release-1.15.md
- ref: 6d692779e1c99f8f04e678590b4411ca4d36e6b9
- related: #8397
- revert change to drop Node v12 support
- ref: 6d692779e1c99f8f04e678590b4411ca4d36e6b9
> update spfx v1.15 release notes

- docs/declarative-customization/formatting-syntax-reference.md
None
Added directionalHint valid values
> Added directionalHint valid values

- docs/spfx/viva/get-started/advanced-quick-view-functionality.md
The first two steps in the create a new quick view section are duplicates
N/A
Fix to documentation
> Removed duplicated step

- docs/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in.md
Example has `<webPart xmlns="https://schemas.microsoft.com/WebPart/v3">`, however this fails in with an incorrect namespace error:
```
Web Part Error: Cannot recognize the XML namespace of this Web Part. Correlation ID: 751853a0-d0d4-1000-5e8e-ce46b644d262.
```
Correct value should `<webPart xmlns="http://schemas.microsoft.com/WebPart/v3">`.
> Schema namespace incorrect

- docs/business-apps/power-apps/get-started/create-your-first-custom-form.md
Removal of the Next Steps section
> Clean up invalid reference

- docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md
Added notes about deprecated triggers and actions.
> Add notes about deprecated trigger and actions

- docs/scenario-guidance/Development-models.md
- docs/scenario-guidance/Line-of-Business-integration.md
- docs/scenario-guidance/Responding-to-changes.md
- docs/scenario-guidance/Site-provisioning.md
- docs/scenario-guidance/Solutions-deployment.md
- docs/schema/propertyrules-element-propertyrulecollection-complextypesps15xsdsearchset2.md
- docs/solution-guidance/security-apponly-azureacs.md
- docs/solution-guidance/security-apponly-azuread.md
- docs/solution-guidance/security-apponly.md
- docs/solution-guidance/security-webapppolicies.md
No related issues.
**Global effort to improve metadata quality across the Learn platform**
These changes make reports cleaner, easier to use, more consistent, and more reflective of our current business. After you accept these changes and they're merged, they will be reflected in standard dashboards and reports maintained by C+E Skilling Business & Customer Success. You'll need to use new filter values in these reports, and you may need to update any custom dashboards or Kusto queries. If you have any questions, please contact Learn Platform Metadata (learn-metadata@microsoft.com).
> Bulk Metadata Update - Replacing ms.topic values.

- docs/declarative-customization/formatting-syntax-reference.md
Corrected split operator syntax and expression in examples
> Corrected split operator syntax

- docs/general-development/debugging-sharepoint-server-workflows.md
- docs/general-development/how-to-create-custom-sharepoint-server-workflow-forms-with-visual-studio-20.md
- docs/general-development/how-to-create-sharepoint-workflows-using-visual-studio.md
- docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md
- docs/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model.md
- docs/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer.md
- docs/general-development/working-with-web-services-in-sharepoint-workflows-using-visual-studio-2012.md
- docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md
- n/a
Update links that were breaking or unnecessary redirecting
> correct broken & redirection links

- docs/solution-guidance/security-apponly-azureacs.md
Renamed PnP Sites Core library to PnP Framework library because the former is now archived and not supported, while the latter is the new one. Code samples are already using the new one.
> **DELETE THIS LINE BEFORE SUBMITTING** | *If this fixes (aka: closes) or references an issue, please reference it here. This helps maintaining the issue list as it will (1) link the PR to the issue & (2) automatically close the issue when …
> Updated security-apponly-azureacs.md

- docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
> Added links to dev blog for rate limit headers

- docs/solution-guidance/the-pnp-office-open-xml-file-format.md
Fixes #8547
Fixes #8547
Command Updates
> Update PnP PowerShell Commands

- docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md
Sample is using PnP PowerShell, it's confusing that it asks users to open SharePoint Online Management Shell.
- fixes #8551
Content Update
> Updating Document for Clarity

- docs/spfx/extensions/overview-extensions.md
Added basic information about SPFx form customizer in the Extensions overview file as we have now the 4th type of Extension supported with the 1.15 version.
> Added information about Form customizer to overview of extension section

- docs/spfx/web-parts/guidance/getting-started-with-top-actions.md
Creates documentation for the SharePoint Framework Top Actions feature.
> Adds SharePoint Framework Top Actions documentation

- docs/spfx/compatibility.md
None, should I create one?
Added SPFx v1.16 compatibility specs.
> Adds spfx v1.16 compatibility

- docs/sp-add-ins/add-a-custom-content-type-to-a-sharepoint-hosted-sharepoint-add-in.md
- docs/sp-add-ins/programmatically-deploy-a-custom-button-in-the-provider-hosted-add-in.md
- docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md
- docs/spfx/extensions/get-started/building-simple-field-customizer.md
- docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md
- docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md
- fixes #8601 
Updates the use of `element.xml` to `elements.xml` (plural)
> Updates use of element.xml notation

- docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md
- docs/general-development/themes-overview-for-sharepoint.md
- closes #8588
Fix doc markdown formatting errors
> 📜🧼 fix numerous markdown formatting errors

- docs/spfx/web-parts/get-started/connect-to-sharepoint.md
- fixes #8470
Fix floating promise warning trigger in tutorial
> Update tutorial to address eslint floating promise warning

- docs/spfx/web-parts/get-started/using-microsoft-graph-apis.md
- fixes #8606
Added missing div with id `spListContainer` in the sample code's render method.
> Added missing div in render

- docs/spfx/compatibility.md
None
Adds SPFx v1.16.1 to the compatibility matrix.
> Adds version SPFx v1.16.1 to compatibility matrix

- docs/apis/site-creation-rest.md
Included the "SensitivityLabel" parameter, as the "Classification" parameter does not apply a label on the site collection. The "Classification" parameter only sets a value on the Site Collection, but it doesn't apply a sensitivity label. You need to include the "SensitivityLabel" parameter with the ID to set the label. The "Classification" parameter is not needed anymore if you use the new parameter.
> - Follow our guidance on [How To Create Good Pull …
> Added SensitivityLabel parameter

- docs/spfx/use-aad-tutorial.md
Updated the reference for MSGraphClient to MSGraphClientV3
> updated the reference for MSGraphClient to MSGraphClientV3

- docs/spfx/viva/get-started/actions/media-upload/MediaUploadDocumentation.md
Changed "MediaType.Image" to MediaType.Image
N/A
Updating the MediaType from "MediaType.Image" to MediaType.Image.
> Update documentation to fix mediaType

- docs/sp-add-ins/working-with-folders-and-files-with-rest.md
- fixes #8663 
A new DELETE Request Sample for Attachment Files
> Adding DELETE sample for Attachment Files

- docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md
Renamed from Deploy to Enable app.
ms.date 01/19/2023
> Rename button name from Deploy to Enable app

- docs/business-apps/power-automate/guidance/working-with-send-sp-http-request.md
- closes #8016
- link had the locale missing & some locales aren't translated, such as in the case of `de-de`
- changed to use a locale-hard coded link
> ♻️ fixup markdown, fixup link

- docs/spfx/integrate-with-teams-introduction.md
> 🐞♻️ fixup code reference typo

- docs/spfx/toolchain/configure-sass.md
- docs/toc.yml
- n/a
- added a new article on how to configure the SASS processor
> 📜 add article on configuring SASS for spfx

- docs/spfx/use-aadhttpclient.md
N/A
Fixes typo in `use-aadhttpclient.md`
> Fixes typo in use-aadhttpclient.md

- docs/declarative-customization/view-calendar-formatting.md
Without adding columns into view, the formatters won't work properly and have been causing customer ICMs. highlighting some key steps in documentation to avoid confusion.
> highlight prerequisite step needed for formatting

- docs/solution-guidance/security-apponly-azureacs.md
- docs/solution-guidance/security-apponly-azuread.md
- includes/snippets/open-source/pnp-framework.md
- includes/snippets/open-source/pnp-sites-core.md
- closes #6504
Updating SharePoint Online AAD App / ACS App-Only granting process with PnP Framework, removing references to PnP Sites Core.
> Update SPO AAD App / ACS App-Only articles with PnP Framework references

- docs/solution-guidance/Add-a-custom-ribbon-to-your-SharePoint-site.md
- No related issues
Updated address in hyperlink - broken before, now pointing to repository it self.
> Updated address in PnP.Framework hyperlink

- docs/toc.yml
- n/a
- correct wording references to microsoft learn[ing paths]
- add link to new module on creating ACEs
> 📚 update toc wording & add link to ace module

- docs/design/ui-text-for-web-parts.md
- docs/scenario-guidance/Development-models.md
- docs/solution-guidance/Sandbox-Solution-Transformation-Guidance-WebParts.md
- docs/sp-add-ins/access-sharepoint-data-from-add-ins-using-the-cross-domain-library.md
- docs/sp-add-ins/creating-sharepoint-add-ins-that-use-the-cross-domain-library.md
- docs/sp-add-ins/important-aspects-of-the-sharepoint-add-in-architecture-and-development-landscap.md
- docs/sp-add-ins/sharepoint-add-ins-ux-design-guidelines.md
- docs/sp-add-ins/sharepoint-add-ins.md
- docs/spfx/build-for-teams-considerations.md
- docs/spfx/css-recommendations.md
- docs/spfx/enterprise-guidance.md
- docs/spfx/release-1.14.md
- docs/spfx/release-1.8.0.md
- docs/spfx/web-parts/isolated-web-parts.md
- docs/spfx/yeoman-generator-for-spfx-intro.md
- n/a
- there's no word 'iframe' so the content is incorrect
- replaced with code reference to the HTML element
> 🐞 fix iframe references in docs

- docs/spfx/viva/get-started/actions/geolocation/GeolocationDocumentation.md
- docs/spfx/viva/get-started/actions/geolocation/GeolocationPropertyPane.md
- docs/spfx/viva/get-started/actions/geolocation/GeolocationTutorial.md
- docs/spfx/viva/get-started/actions/media-upload/MediaUploadDocumentation.md
- docs/spfx/viva/get-started/actions/media-upload/MediaUploadPropertyPane.md
- docs/spfx/viva/get-started/actions/media-upload/MediaUploadTutorial.md
- docs/spfx/viva/get-started/adaptive-card-extensions-and-teams.md
- docs/spfx/viva/get-started/advanced-card-view-functionality.md
- docs/spfx/viva/get-started/advanced-quick-view-functionality.md
- docs/spfx/viva/get-started/build-first-sharepoint-adaptive-card-extension.md
- docs/spfx/viva/overview-viva-connections.md
- n/a
- fix markdown issues
- remove outdated preview/beta references
- fix alerts
- fix code formatting
- add additiona content when applicable
- add link to new MSL module on SPFx ACEs
> 📚 update viva connections ace docs

- docs/spfx/release-1.17.md
- n/a
- fixed markdown errors
- fixed typos
- fix code formatting
> 🐞 fix release notes for spfx v1.17

- docs/design/authoring-pages.md
- docs/design/reactive-and-nonreactive-web-parts.md
- docs/design/ui-text-for-web-parts.md
- docs/solution-guidance/Personalize-search-results-sample-app-for-SharePoint.md
- docs/solution-guidance/Read-or-update-user-profile-properties-sample-app-for-SharePoint.md
- docs/solution-guidance/Records-management-extensions-sample-app-for-SharePoint.md
- docs/solution-guidance/customize-onedrive-for-business-sites.md
- docs/spfx/web-parts/guidance/migrate-angular-1-x-applications-to-sharepoint-framework.md
- n/a
- fixup img References
- convert html img element references to markdown
- fixed various markdown issues
- improve readability (acrolyix score)
> Fix img references

- .github/PULL_REQUEST_TEMPLATE.md
- docs/general-development/keyword-query-language-kql-syntax-reference.md
- not related to an issue number
Clarfication about don't support wildcard operator (*) as prefix.
> Update content about prefix

- docs/spfx/release-1.17.md
Just some minor typo fixes that I found in the release notes. (PS: I don't want to be nitpicking, they just stood out when I read the documentation 😄)
> Minor typos in SPFx 1.17 release notes

- docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
Fix a broken link, and clarify that the limit is applied org-wide and only to REST/CSOM.
> Fix broken link for Microsoft Graph people search

- docs/spfx/sharepoint-2019-and-subscription-edition-support.md
- n/a
- fix typos & markdown errors in SP 2019 + SP SE doc
> 🐞 typos & markdown errors

- docs/apis/migration-perm-guidance.md
- n/a
♻️ improve readability with acrolinx
> ♻️ improve readability with acrolinx

- docs/spfx/web-parts/guidance/getting-started-with-top-actions.md
Updating the Top Actions to be GA'd as part of the 1.17 release - and updating tutorial to match the GA features.
> Update for the GA of Top Actions

- docs/spfx/compatibility.md
- fixes #8867
Added v1.17.0 to the SPFx compatibility matrix.
> Updates SPFx compatibility matrix with v1.17.0

- docs/declarative-customization/formatting-syntax-reference.md
- No Related issues. This is a content update for changes to customization functionality, specific to images.
- Guidelines for using images within formatting 
- update referencing HTML Field Security Documentation
> update for img src tags

- docs/spfx/compatibility.md
None
Adds SPFx v1.17.1 to the SPFx compatibility matrix.
> Adds SPFx 1.17.1 to compatibility matrix

- docs/spfx/release-1.17.1.md
- docs/spfx/release-1.17.md
- n/a
- remove absolute links
- fix inconsistent markdown
- remove pinning to specific page modes/versions in links
> 🐞 fixup markdown & build errors flagged by msdocs

- docs/spfx/release-1.17.md
- docs/spfx/use-aadtokenprovider.md
- docs/toc.yml
- ref #8881
- add doc explaining the scenario & how to implement it
- update release notes where feature added to point to the doc
- add to toc
> 📜 new article doc'ing AADTokenProvider.popupEvent

- docs/transform/modernize-workflows.md
> 2013 WF retirement details were added

- docs/general-development/get-started-with-workflows-in-sharepoint.md
> 2013 WF retirement details added

- docs/general-development/keyword-query-language-kql-syntax-reference.md
- [] Example checked item (*delete this line*)
Clarify documentation.
> Correct docs to mention what property support prop:*

- docs/spfx/set-up-your-development-environment.md
> SPFx version number updated from 1.16 to 1.17.1

- docs/general-development/site-collection-app-catalog.md
- fixes #8974 
Update the cli cmdlet with correct parameter.
> Correct cli cmdlet

- docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md
Update the way to replace an expiring client secret of addin.
> update replace client secret

- docs/spfx/viva/get-started/migrate-to-spfx-1-18.md
- docs/toc.yml
The PR includes a new article that describes how to migrate existing ACEs to new configuration model introduced in SPFx 1.18
> ACE migration to spfx 1.18

- docs/spfx/viva/features/focus-feature/FocusFeatureTutorial.md
- docs/spfx/viva/get-started/actions/geolocation/GeolocationTutorial.md
- docs/spfx/viva/get-started/actions/media-upload/MediaUploadTutorial.md
- docs/spfx/viva/get-started/advanced-card-view-functionality.md
- docs/spfx/viva/get-started/advanced-quick-view-functionality.md
- docs/spfx/viva/get-started/build-first-sharepoint-adaptive-card-extension.md
- docs/spfx/viva/get-started/build-people-search-adaptive-card-extension.md
- docs/spfx/viva/get-started/migrate-to-spfx-1-18.md
- docs/toc.yml
- addresses issues in #9022, #9025, #9035
- fix typos/misspellings
- fix casing issues
- markdown issues
- always add line break between bullet lists, paragraphs, code snippets, etc
- never use `bash` code lexicon, use `console` for xplat
- only use inline code formatting for CODE (interfaces, function names, code, etc)
- only use BOLD for file names, labels, command line prompts, etc
- maintain consistent style with bullet points
- don't indent code within a fenced code block; code should be right aligned within the block
> 🧼 clean recent doc submissions

- docs/spfx/viva/design/designing-card.md
> formating changes

- docs/spfx/use-aadtokenprovider.md
Fixed broken link in article - Working with the AADTokenProvider
> Fixed broken link in article

- docs/sp-add-ins/add-first-run-logic-to-the-provider-hosted-add-in.md
- docs/sp-add-ins/add-sharepoint-write-operations-to-the-provider-hosted-add-in.md
- docs/sp-add-ins/give-your-provider-hosted-add-in-the-sharepoint-look-and-feel.md
- docs/sp-add-ins/handle-add-in-events-in-the-provider-hosted-add-in.md
- docs/sp-add-ins/handle-list-item-events-in-the-provider-hosted-add-in.md
- docs/sp-add-ins/include-a-custom-button-in-the-provider-hosted-add-in.md
- docs/sp-add-ins/include-an-add-in-part-in-the-provider-hosted-add-in.md
- docs/sp-add-ins/programmatically-deploy-a-custom-button-in-the-provider-hosted-add-in.md
- Replaces 15 instances of "Hong Kong" with "Hong Kong SAR"
This PR addresses the following Policheck bugs: 
•	https://dev.azure.com/msft-skilling/learn-platform-policheck/_queries/edit/116195
•	https://dev.azure.com/msft-skilling/learn-platform-policheck/_queries/edit/116200
•	https://dev.azure.com/msft-skilling/learn-platform-policheck/_queries/edit/116206
•	https://dev.azure.com/msft-skilling/learn-platform-policheck/_queries/edit/116209
•	https://dev.azure.com/msft-skilling/learn-platform-policheck/_queries/edit/116202
•	https://dev.azure.com/msft-skilling/learn-platform-policheck/_queries/edit/116208
•	https://dev.azure.com/msft-skilling/learn-platform-policheck/_queries/edit/116211
•	https://dev.azure.com/msft-skilling/learn-platform-policheck/_queries/edit/116213
> Policheck update - June 28 | Bulk Update

- docs/spfx/release-1.18.md
Updates for 1.18.0 release notes to include 1.18.0-beta.2 changes
> 1.18.0-beta.2 release notes

- docs/sp-add-ins/add-first-run-logic-to-the-provider-hosted-add-in.md
- docs/sp-add-ins/add-sharepoint-write-operations-to-the-provider-hosted-add-in.md
- docs/sp-add-ins/give-your-provider-hosted-add-in-the-sharepoint-look-and-feel.md
- docs/sp-add-ins/handle-add-in-events-in-the-provider-hosted-add-in.md
- docs/sp-add-ins/handle-list-item-events-in-the-provider-hosted-add-in.md
- docs/sp-add-ins/include-a-custom-button-in-the-provider-hosted-add-in.md
- docs/sp-add-ins/include-an-add-in-part-in-the-provider-hosted-add-in.md
- docs/sp-add-ins/programmatically-deploy-a-custom-button-in-the-provider-hosted-add-in.md
- docs/spfx/release-1.18.md
- docs/spfx/release-1.5.1.md
- docs/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts.md
> Main to Live

- docs/spfx/release-1.18.md
Update SPFx 1.18.0 release notes with beta.3 changes
> SPFx 1.18.0-beta.3

- docs/solution-guidance/security-webapppolicies.md
Fixed spelling
Fixed spelling.  Changed on to one
> Changed on to one

- docs/spfx/use-microsoft-graph-toolkit.md
> remove iframe tag

- docs/declarative-customization/site-design-pnp-provisioning.md
Updated the **site-design-pnp-provisioning.md** file
Put a note that the Request trigger is now PREMIUM and will therefore require additional licensing.
> Michal ziemba patch 1

- docs/sp-add-ins-modernize/from-acs-to-aad-apps.md
- docs/sp-add-ins-modernize/from-app-parts-to-modern-web-parts.md
- docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md
- docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md
- docs/sp-add-ins/secure-data-access-and-client-object-models-for-sharepoint-add-ins.md
- docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md
- docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md
- ref #9194
- fixup link issues across multiple docs exposed in previously auto-submitted PR
> 🐞♻️ fixup doc issues exposed in PR9194

- docs/solution-guidance/pnp-provisioning-tenant-templates.md
N/A
Updated the PnP cmdlets so they actually do what it said they would do
> Updated the PnP cmdlets in the Tenant provisioning documentation

- docs/design/accessibility.md
- docs/schema/currency-element-regional-settings.md
This PR contains updates to sensitive terms identified by Policheck in the following bug:
https://dev.azure.com/msft-skilling/learn-platform-policheck/_queries/edit/116188
- fixes #1
This bulk PR addresses Policheck issues.
> Policheck update: Update to place name and reference to visual impairments | 10/2/2023

- docs/spfx/viva/design/designing-quick-view.md
- docs/spfx/viva/get-started/making-quickview-compatable-darkmode-mobile.md
This Pull Request changes the documentation related to quickview dark mode API for Viva Connections Mobile.  This PR introduces a new way to provide theming support for quickViews in VCM.
> added new dark mode api documentation changes

- docs/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties.md
Fixed broken hyperlink in article
> Fixed broken links in use-cascading-dropdowns-in-web-part-properties.md

- docs/spfx/set-up-your-development-environment.md
- fixes #9296
- mentioned in #9296
Fixes a broken link to NodeJS website.
> Fix broken NodeJS link

- docs/docfx.json
This PR brings breadcrumb implementation into alignment with [platform architecture requirements](https://review.learn.microsoft.com/en-us/help/platform/navigation-overview?branch=main#requirements-for-content-ecosystems). This PR is part of a previously announced batch of breadcrumb fixes across the Learn platform and will be auto-merged if there are no build warnings. This PR may include removing the “extend breadcrumb” feature from any docfx files that are still using it, fixing breadcrumb file references in the docfx file, and rewriting breadcrumb files to match the [approved breadcrumb pattern](https://review.learn.microsoft.com/en-us/help/platform/navigation-breadcrumbs-overview?branch=main#breadcrumbs-in-documentation) for a given product’s documentation. 
> **DELETE THIS LINE …
> Fix breadcrumbs

- docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
- docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md
- docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md
- [] Example checked item (*delete this line*)
N/A
Updated core web part tutorials as per SPFx 1.18 version
> Updated core web part tutorials as per SPFx 1.18 version

- docs/spfx/compatibility.md
Updated the compatability matrix to add support for SPFx 1.18.1
> Added SPFx version 1.18.1 compatibility

- docs/spfx/compatibility.md
Quick content fix, linking to the SPFx 1.18.2 release
> Updated with SPFx 1.18.2 compatibility

- docs/sp-add-ins-modernize/understanding-aad-and-oauth-for-spo-modern.md
While reading the article at https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins-modernize/understanding-aad-and-oauth-for-spo-modern, I noticed a few spelling and wording issues, a broken image, and a broken documentation link. I am proposing improvements to those in this PR.
> Fix spelling/wording issues and broken URLs in understanding-aad-and-oauth-for-spo-modern.md

- docs/embedded/concepts/app-concepts/app-architecture.md
- docs/embedded/concepts/app-concepts/auth.md
- docs/embedded/concepts/app-concepts/containertypes.md
- docs/embedded/concepts/app-concepts/limits-calling.md
- docs/embedded/concepts/app-concepts/sharing-and-perm.md
- docs/embedded/concepts/app-concepts/terms-and-def.md
- docs/embedded/concepts/content-experiences/office-experience.md
- docs/embedded/concepts/content-experiences/user-experiences-overview.md
- docs/embedded/terms-of-service.md
- docs/embedded/tutorials/launch-experience.md
- docs/embedded/tutorials/register-ct.md
- docs/embedded/tutorials/using-file-preview.md
- n/a
Fixes lots of markdown & content bugs in the following SP Embedded sections:
- ./docs/embedded/concepts/app-concepts
- ./docs/embedded/concepts/content-experiences
- ./docs/embedded/tutorials
> Scrub & fixup 🐞 in spembedded docs

- docs/embedded/terms-of-service.md
No related issues
We made changes to our pricing meters i.e. removed the Graph API Transaction Class B meter on the approval of Business Planning and Legal.
> Update Terms of Service for SharePoint Embedded

- docs/toc.yml
no related issues
fixed a broken link to security and compliance article
> - Review all build checks and address the automated errors, warnings, and suggestions.
> - *NOTE: The live site is based on the `live` branch. Site owners periodically refresh …
> Fix link to table of contents

- docs/spfx/viva/get-started/advanced-card-view-functionality.md
- n/a
Add developer preview notice to ACE card view caching page
> 🐞 add devpreview notice to ACE cardview caching

- docs/general-development/client-side-web-parts-maintenance-mode.md
> Add missing parameter to sample

- docs/docfx.json
- docs/embedded/adoptions-and-use.md
- docs/embedded/concepts/admin-exp/billing.md
- docs/embedded/concepts/admin-exp/cta.md
- docs/embedded/concepts/admin-exp/dev-admin.md
- docs/embedded/concepts/app-concepts/app-architecture.md
- docs/embedded/concepts/app-concepts/auth.md
- docs/embedded/concepts/app-concepts/containertypes.md
- docs/embedded/concepts/app-concepts/limits-calling.md
- docs/embedded/concepts/app-concepts/sharing-and-perm.md
- docs/embedded/concepts/app-concepts/terms-and-def.md
- docs/embedded/concepts/content-experiences/office-experience.md
- docs/embedded/concepts/content-experiences/user-experiences-overview.md
- docs/embedded/concepts/security-and-compliance.md
- docs/embedded/getting-started/enable-sharepoint-embedded.md
- docs/embedded/mslearn/m01-01-intro.md
- docs/embedded/mslearn/m01-04-unit.md
- docs/embedded/mslearn/m01-05-hol.md
- docs/embedded/mslearn/m01-07-hol.md
- docs/embedded/mslearn/m02-01-intro.md
- docs/embedded/mslearn/m02-02-unit.md
- docs/embedded/mslearn/m02-03-hol.md
- docs/embedded/mslearn/m02-04-unit.md
- docs/embedded/overview.md
- docs/embedded/terms-of-service.md
- docs/embedded/tutorials/launch-experience.md
- docs/embedded/tutorials/register-ct.md
- docs/embedded/tutorials/using-file-preview.md
- n/a
- change **Microsoft Entra** to **Microsoft Entra ID**
- fix missed link reference
- fix markdown bold formatting
> fix formatting, broken link, and correct reference to entra apps

- docs/embedded/mslearn/m01-05-hol.md
- docs/embedded/mslearn/m02-03-hol.md
- docs/embedded/mslearn/m02-05-hol.md
- docs/embedded/mslearn/m02-07-hol.md
- n/a
When proofing, found multiple typos, markdown issues, and a minor step missing.
> ♻️ fix typos & markdown issues for SPEmbedded modules

- docs/spfx/debug-modern-pages.md
- docs/spfx/extensions/get-started/build-a-hello-world-extension.md
- docs/spfx/extensions/get-started/building-form-customizer.md
- docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md
- docs/spfx/extensions/get-started/building-simple-field-customizer.md
- docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md
- docs/spfx/viva/features/focus-feature/FocusFeatureTutorial.md
- docs/spfx/viva/get-started/actions/geolocation/GeolocationTutorial.md
- docs/spfx/viva/get-started/actions/media-upload/MediaUploadTutorial.md
- docs/spfx/viva/get-started/build-first-sharepoint-adaptive-card-extension.md
- docs/spfx/viva/get-started/build-people-search-adaptive-card-extension.md
- docs/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts.md
- N/A
> changes related to $schema refererence update related to SPFx 1.18.x
> changes related to $schema refererence update related to SPFx 1.18.x

- docs/embedded/mslearn/m02-02-unit.md
- docs/embedded/mslearn/m02-03-hol.md
- docs/embedded/mslearn/m02-04-unit.md
- docs/embedded/mslearn/m02-07-hol.md
- n/a
- fix typos
- fix markdown formatting 
- fix outdated step in developer lab
> 🐞 typos and fix some setup instructions

- docs/embedded/mslearn/m01-05-hol.md
- fixes #9417
- fixed in another page in d2c7295483dc0646a8051e3150d5bdbba066eabc, but missed this one
> 🐞 correct powershell script

- docs/general-development/client-side-web-parts-maintenance-mode.md
Fix docs to match what is needed in the product.
> Remove =1 on the disable3PCode param

- docs/embedded/concepts/content-experiences/search-content.md
- [ x] New article
Publish a new article on how to search SPE content.
> Publish article on search SPE content

- docs/spfx/set-up-your-developer-tenant.md
- docs/training/training.md
Updated with the approved text for referring to the Microsoft 365 Developer Program subscription.
> - Review all build checks and address the automated errors, warnings, and …
> Updated the reference to the Developer Program.

- docs/apis/export-amr-api.md
Recently we are seeing a lot of performance-related issues on AMR usage, so we need to update ISVs urgently.
Added a warning for performance.
> Adding an important performance warning to the document.

- docs/embedded/concepts/fluid.md
- n/a
- filenames shoudl be BOLD, not inline code
- bullet lists shouldn't have empty lines between bullets
- don't include locale in Microsoft links
- don't use absolute links
> ♻️ fix markdown issues & conventions

- docs/toc.yml
Edits `toc.yml` to include Fluid article from #9563
> Fluid patch1

- docs/embedded/tutorials/doc-processing-acs.md
- docs/embedded/tutorials/using-webhooks.md
- docs/toc.yml
- ref #9543
- run new tutorials through Acronlinx & fix to improve readability score
- always use full name "Microsoft Graph" when refering to it
- fix code indentation & missing `{` for readability & correctness
- replace tabs with spaces for bullets
- add listings in TOC for new tutorials (otherwise will only find via search)
> Fix formatting, word choice, & add SPE tutorials to TOC

- docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md
- n/a
update link that points to endpoint that's currently HTTP 301'ing.
> 🐞 update link to point to target vs. HTTP 301

- docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md
…-2012.md
Corrected/clarified SharePoint Server versioning information that caused previous version of this document to be very difficult to understand.
- n/a
The changes in this Pull Request clarify the versions of SharePoint Server to which the content applies today, and that the information was provided originally in SharePoint Server 2013.  It also corrects the content type display name for the 'Workflow Task' that was introduced with SharePoint Server 2013. It makes the article more understandable,  more factually accurate, and provides a fuller context for the information.
> Update to document with useful corrections and clarifications.

- docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md
- partially #9582
- removed unnecessary line breaks
- markdown fixes
- empty lines
- numbered & unordered list formatting
- indentation
- update old links to the correct locations
- related #9582
> 🐞🧼 typos, grammar & markdown fixes, link updates

- docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md
- fixes regression in ##9592 that was originally fixed in #9582
- remove version number from `Visual Studio 2012`
- this was done in #9582...
- ... but i reverted incorrectly in #9592
- ... made aware by #9582's OP @geoffrey-citron-nnl
- this fixes that
> 🐞 fix content regression from community contrib

- docs/toc.yml
- [c] Content fix
- n/a
fixes broken link in site-modernization section of TOC
> 🐞 fix broken link in TOC

- docs/solution-guidance/modern-experience-customizations.md
- fixes #9607
- fix accidental merge of PR #9607 before OP fixed issues
- fix markdown errors
> 🐞 fix mistaken pr merge & fixup markdown

- docs/declarative-customization/column-formatting.md
- docs/declarative-customization/customize-default-site-design.md
- docs/declarative-customization/formatting-advanced.md
- docs/declarative-customization/formatting-syntax-reference.md
- docs/declarative-customization/get-started-create-site-design.md
- docs/declarative-customization/list-form-conditional-show-hide.md
- docs/declarative-customization/list-form-configuration.md
- n/a
Fix numerous MSDocs, formatting, grammatical, markdown errors and typos.
> ♻️ proof & fix numerous msdocs, typos, formating, and gramatical errors

- docs/apis/addin-management-apis.md
We added a new param for the addin apis, the old param only accept relative url, but the new param accept both relative url and full url.
> - Review all build checks and address the automated errors, …
> update the addin apis to accept full url as input

- docs/apis/amr-api-reference.md
- docs/apis/migration-api-reference.md
- docs/apis/migration-azure.md
Clarified the permission requirement on containers.
> Clarification of permission requirement on containers.

- docs/toc.yml
- fixes #9689
Fixed typo in the menu.
> Fixed typo in the menu

- docs/spfx/web-parts/isolated-web-parts-retirement.md
- docs/spfx/web-parts/isolated-web-parts.md
- docs/toc.yml
- n/a
- also updated TOC entry to match format of other retirement announcements
> ♻️ fix typo & markdown formatting

- docs/spfx/release-1.19.md
- [c] Content fix
- n/a
typo in page title
> 🐞 fix typo

- docs/spfx/set-up-your-development-environment.md
- fixes #9684
- small typo fixup
- corrected broken link to postman
- added two new optional tools: Teams Toolkit VS Code and SPFx Toolkit VS Code
> Fixup in set-up-your-development-environment. Closes: #9684

- docs/embedded/concepts/admin-exp/adminrole.md
- docs/embedded/concepts/admin-exp/billing/billing.md
- docs/embedded/concepts/admin-exp/billing/billingmanagement.md
- docs/embedded/concepts/admin-exp/billing/meters.md
- docs/embedded/concepts/admin-exp/consuming-tenant-admin/cta.md
- docs/embedded/concepts/admin-exp/consuming-tenant-admin/ctaUX.md
- docs/embedded/concepts/admin-exp/consuming-tenant-admin/ctapowershell.md
- docs/embedded/concepts/admin-exp/developer-admin/dev-admin.md
- docs/embedded/concepts/app-concepts/app-architecture.md
- docs/embedded/concepts/app-concepts/auth.md
- docs/embedded/concepts/app-concepts/containertypes.md
- docs/embedded/concepts/app-concepts/limits-calling.md
- docs/embedded/concepts/app-concepts/register-api-documentation.md
- docs/embedded/concepts/app-concepts/sharing-and-perm.md
- docs/embedded/concepts/content-experiences/office-experience.md
- docs/embedded/concepts/content-experiences/search-content.md
- docs/embedded/concepts/content-experiences/user-experiences-overview.md
- docs/embedded/concepts/fluid.md
- docs/embedded/getting-started/spembedded-for-vscode.md
- docs/embedded/overview.md
- docs/embedded/scenarios-and-use-cases.md
- docs/embedded/tutorials/doc-processing-acs.md
- docs/embedded/tutorials/launch-experience.md
- docs/embedded/tutorials/using-file-preview.md
- docs/embedded/tutorials/using-webhooks.md
- quality pass for #9707 
- various markdown fixes to conform to msdocs rules
- fixes multiple acrolinx findings
- correct typos
> address markdown & acrolinx findings

- .openpublishing.redirection.json
- fixup redirects to moved content fro #9707 
redirect updates
> fixup spe ga redirects

- docs/apis/webhooks/webhooks-reference-implementation.md
- references #9732
- fix typos
- fix markdown
- fix code listings
- fix video reference
> fixes to pile on from recent pr9732

- docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
Link to the PBI: https://onedrive.visualstudio.com/SPIN/_workitems/edit/2090630
This pull request is generated as a fix to the PBI: https://onedrive.visualstudio.com/SPIN/_workitems/edit/2090630
> Updating Throttling Document

- docs/sp-add-ins/sharepoint-admin-apis-authentication-and-authorization.md
- docs/toc.yml
This change adds documentation that explains how we do authentication and authorization for SharePoint admin APIs.
> Add documentation for SharePoint admin APIs authentication and authorization

- docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
> update on documentation for security limit on throttling

- docs/embedded/tutorials/migrate-abs-to-spe.md
- fixes issues in #9840 
- address findings from acrolynx
- fix markdown linting issues with lists
> ♻️ improve readaibility score

- docs/spfx/set-up-your-development-environment.md
- n/a
add additional info on the envvar for new env config
> add mention of spfx envvar to set on dev env

- docs/toc.yml
> No related issues
> Add new tutorial to Table of Content
> Add Migrate ABS 2 SPE to TOC

- docs/spfx/set-up-your-development-environment.md
- small fixup to #9867
formatting fixup
> fix formatting typo

- docs/embedded/concepts/app-concepts/auth.md
Updating auth article to reflect new container permission ManageContent
> Add ManageContent

- docs/embedded/concepts/content-experiences/search-content.md
- fixes BUG 2160957
Update search-content.md to include search by contaienr custom property scenario
> - Review all build checks and address the automated errors, warnings, and suggestions.
> - *NOTE: The live site is based on the `live` branch. Site owners periodically …
> Update search-content.md to include search by contaienr custom property scenario

- docs/embedded/concepts/admin-exp/billing/billing.md
We heard some feedback that customers are not able to find the set up guide for DTB billing. In this PR I moved the DTC set up guide to the main page of billing
> Billing update

- docs/design/use-brand-center-fonts-in-spfx-components.md
- n/a
remove "preview" label for brand center
> update brand center preview statement

- docs/sp-add-ins/add-first-run-logic-to-the-provider-hosted-add-in.md
- docs/sp-add-ins/add-sharepoint-write-operations-to-the-provider-hosted-add-in.md
- docs/sp-add-ins/get-a-quick-overview-of-the-sharepoint-object-model.md
- docs/sp-add-ins/handle-add-in-events-in-the-provider-hosted-add-in.md
- docs/sp-add-ins/handle-list-item-events-in-the-provider-hosted-add-in.md
- docs/sp-add-ins/include-a-custom-button-in-the-provider-hosted-add-in.md
- docs/sp-add-ins/include-an-add-in-part-in-the-provider-hosted-add-in.md
- docs/sp-add-ins/programmatically-deploy-a-custom-button-in-the-provider-hosted-add-in.md
- related #10104
- changes in #10104 generated broken links in other docs in this PR, this fixes the broken links + markdown issues in this doc
- numbered lists should only use `1.` & let the engine render
- fix code block indents
- fix grammar issues
- correct inline code use (steps & files are bold, not code)
- bullets should be surrounded by line breaks
> fix broken links + markdown issues

- docs/sp-add-ins/get-started-creating-provider-hosted-sharepoint-add-ins.md
For now, when developers develop the provider hosted addins, they need to generate the ACS app manually and apply it to the development environment. So add some steps about this process.
> - Review all …
> Add steps for developing provider hosted addin

- docs/declarative-customization/formatting-syntax-reference.md
> Remove extra , (Update formatting-syntax-reference.md)

- .openpublishing.redirection.json
> Fix redirect links

- docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
N/A
Just a minor typo in the docs.
> SharePoint, not Sharepoint

- .github/policies/resourceManagement.yml
Enable the issue tracking and monitoring automation based on this doc: https://eng.ms/docs/more/github-inside-microsoft/policies/resource-management
> Added configuration to enable tracking and monitoring of GitHub issues

- docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
name change for app prioritization
> Name change for app prioritization

- docs/embedded/development/auth.md
Clarifies the admin consent method to use for SharePoint Embedded applications on consuming tenants.
> Clarify instructions to grant admin consent for SPE application

- docs/embedded/development/declarative-agent/spe-da.md
- docs/embedded/development/declarative-agent/spe-da2.md
Updating SPE copilot --> SPE agent
Cleaned up verbiage here for entire doc:
* SPE copilot -> SPE agent
* Updated FAQ to reflect current status of PAYG
* Note section: cleaned up run on sentence
> - …
> Update SPE agent spe-da.md

- docs/declarative-customization/view-commandbar-formatting.md
Minor update `uploadCommand` => `UploadCommand`
> Minor Update view-commandbar-formatting.md

- docs/toc.yml
- fixes #10249 
#10249 update the filename from spe-da.md to spe-da2.md. Updating the TOC accordingly. Also update terminology from copilot to agent.
> Fix TOC entries for SharePoint Embedded agent

- docs/apis/migration-api-overview.md
- docs/apis/migration-api-reference.md
- docs/apis/migration-job-progress-api-reference.md
- N/A
Add notice on using GetMigrationJobProgress API for retrieval of job status.
> Add notice on GetMigrationJobProgress API in Migration API Overview

- docs/declarative-customization/formatting-syntax-reference.md
Added the output unit for clarity
Number(Date('12/26/1981'))" results in 378190800000` milliseconds since Jan 1, 1970`
> Minor update

- docs/general-development/keyword-query-language-kql-syntax-reference.md
> Change KQL ->KeyQL (keyword-query-language-kql-syntax-reference.md)
